01-16 11:21:52 jdbc[2]: SQLException
org.h2.jdbc.JdbcSQLException: Table BILANCIO not found; SQL statement:
alter table BILANCIO drop constraint FK631D379757CF560B [42102-69]
	at org.h2.message.Message.getSQLException(Message.java:91)
	at org.h2.message.Message.getSQLException(Message.java:95)
	at org.h2.message.Message.getSQLException(Message.java:73)
	at org.h2.command.Parser.readTableOrView(Parser.java:4025)
	at org.h2.command.Parser.readTableOrView(Parser.java:4005)
	at org.h2.command.Parser.parseAlterTable(Parser.java:4050)
	at org.h2.command.Parser.parseAlter(Parser.java:3622)
	at org.h2.command.Parser.parsePrepared(Parser.java:302)
	at org.h2.command.Parser.parse(Parser.java:285)
	at org.h2.command.Parser.parse(Parser.java:257)
	at org.h2.command.Parser.prepareCommand(Parser.java:229)
	at org.h2.engine.Session.prepareLocal(Session.java:236)
	at org.h2.engine.Session.prepareCommand(Session.java:218)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1020)
	at org.h2.jdbc.JdbcStatement.executeUpdate(JdbcStatement.java:104)
	at org.hibernate.tool.hbm2ddl.SchemaExport.execute(SchemaExport.java:308)
	at org.hibernate.tool.hbm2ddl.SchemaExport.drop(SchemaExport.java:284)
	at org.hibernate.tool.hbm2ddl.SchemaExport.execute(SchemaExport.java:186)
	at org.hibernate.tool.hbm2ddl.SchemaExport.create(SchemaExport.java:133)
	at org.hibernate.impl.SessionFactoryImpl.<init>(SessionFactoryImpl.java:311)
	at org.hibernate.cfg.Configuration.buildSessionFactory(Configuration.java:1300)
	at store.util.HibernateUtil.<clinit>(HibernateUtil.java:8)
	at test.testStore.TestSet01_HibernateUtil.testFactory(TestSet01_HibernateUtil.java:35)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:585)
	at junit.framework.TestCase.runTest(TestCase.java:164)
	at junit.framework.TestCase.runBare(TestCase.java:130)
	at junit.framework.TestResult$1.protect(TestResult.java:106)
	at junit.framework.TestResult.runProtected(TestResult.java:124)
	at junit.framework.TestResult.run(TestResult.java:109)
	at junit.framework.TestCase.run(TestCase.java:120)
	at junit.framework.TestSuite.runTest(TestSuite.java:230)
	at junit.framework.TestSuite.run(TestSuite.java:225)
	at org.eclipse.jdt.internal.junit.runner.junit3.JUnit3TestReference.run(JUnit3TestReference.java:130)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:460)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:673)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:386)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:196)
01-16 11:21:52 jdbc[2]: SQLException
org.h2.jdbc.JdbcSQLException: Table BILANCIO not found; SQL statement:
alter table BILANCIO drop constraint FK631D3797C56C4797 [42102-69]
	at org.h2.message.Message.getSQLException(Message.java:91)
	at org.h2.message.Message.getSQLException(Message.java:95)
	at org.h2.message.Message.getSQLException(Message.java:73)
	at org.h2.command.Parser.readTableOrView(Parser.java:4025)
	at org.h2.command.Parser.readTableOrView(Parser.java:4005)
	at org.h2.command.Parser.parseAlterTable(Parser.java:4050)
	at org.h2.command.Parser.parseAlter(Parser.java:3622)
	at org.h2.command.Parser.parsePrepared(Parser.java:302)
	at org.h2.command.Parser.parse(Parser.java:285)
	at org.h2.command.Parser.parse(Parser.java:257)
	at org.h2.command.Parser.prepareCommand(Parser.java:229)
	at org.h2.engine.Session.prepareLocal(Session.java:236)
	at org.h2.engine.Session.prepareCommand(Session.java:218)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1020)
	at org.h2.jdbc.JdbcStatement.executeUpdate(JdbcStatement.java:104)
	at org.hibernate.tool.hbm2ddl.SchemaExport.execute(SchemaExport.java:308)
	at org.hibernate.tool.hbm2ddl.SchemaExport.drop(SchemaExport.java:284)
	at org.hibernate.tool.hbm2ddl.SchemaExport.execute(SchemaExport.java:186)
	at org.hibernate.tool.hbm2ddl.SchemaExport.create(SchemaExport.java:133)
	at org.hibernate.impl.SessionFactoryImpl.<init>(SessionFactoryImpl.java:311)
	at org.hibernate.cfg.Configuration.buildSessionFactory(Configuration.java:1300)
	at store.util.HibernateUtil.<clinit>(HibernateUtil.java:8)
	at test.testStore.TestSet01_HibernateUtil.testFactory(TestSet01_HibernateUtil.java:35)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:585)
	at junit.framework.TestCase.runTest(TestCase.java:164)
	at junit.framework.TestCase.runBare(TestCase.java:130)
	at junit.framework.TestResult$1.protect(TestResult.java:106)
	at junit.framework.TestResult.runProtected(TestResult.java:124)
	at junit.framework.TestResult.run(TestResult.java:109)
	at junit.framework.TestCase.run(TestCase.java:120)
	at junit.framework.TestSuite.runTest(TestSuite.java:230)
	at junit.framework.TestSuite.run(TestSuite.java:225)
	at org.eclipse.jdt.internal.junit.runner.junit3.JUnit3TestReference.run(JUnit3TestReference.java:130)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:460)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:673)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:386)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:196)
01-16 11:21:52 jdbc[2]: SQLException
org.h2.jdbc.JdbcSQLException: Table CASSA not found; SQL statement:
alter table CASSA drop constraint FK3CEF4C3D52A1D3F [42102-69]
	at org.h2.message.Message.getSQLException(Message.java:91)
	at org.h2.message.Message.getSQLException(Message.java:95)
	at org.h2.message.Message.getSQLException(Message.java:73)
	at org.h2.command.Parser.readTableOrView(Parser.java:4025)
	at org.h2.command.Parser.readTableOrView(Parser.java:4005)
	at org.h2.command.Parser.parseAlterTable(Parser.java:4050)
	at org.h2.command.Parser.parseAlter(Parser.java:3622)
	at org.h2.command.Parser.parsePrepared(Parser.java:302)
	at org.h2.command.Parser.parse(Parser.java:285)
	at org.h2.command.Parser.parse(Parser.java:257)
	at org.h2.command.Parser.prepareCommand(Parser.java:229)
	at org.h2.engine.Session.prepareLocal(Session.java:236)
	at org.h2.engine.Session.prepareCommand(Session.java:218)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1020)
	at org.h2.jdbc.JdbcStatement.executeUpdate(JdbcStatement.java:104)
	at org.hibernate.tool.hbm2ddl.SchemaExport.execute(SchemaExport.java:308)
	at org.hibernate.tool.hbm2ddl.SchemaExport.drop(SchemaExport.java:284)
	at org.hibernate.tool.hbm2ddl.SchemaExport.execute(SchemaExport.java:186)
	at org.hibernate.tool.hbm2ddl.SchemaExport.create(SchemaExport.java:133)
	at org.hibernate.impl.SessionFactoryImpl.<init>(SessionFactoryImpl.java:311)
	at org.hibernate.cfg.Configuration.buildSessionFactory(Configuration.java:1300)
	at store.util.HibernateUtil.<clinit>(HibernateUtil.java:8)
	at test.testStore.TestSet01_HibernateUtil.testFactory(TestSet01_HibernateUtil.java:35)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:585)
	at junit.framework.TestCase.runTest(TestCase.java:164)
	at junit.framework.TestCase.runBare(TestCase.java:130)
	at junit.framework.TestResult$1.protect(TestResult.java:106)
	at junit.framework.TestResult.runProtected(TestResult.java:124)
	at junit.framework.TestResult.run(TestResult.java:109)
	at junit.framework.TestCase.run(TestCase.java:120)
	at junit.framework.TestSuite.runTest(TestSuite.java:230)
	at junit.framework.TestSuite.run(TestSuite.java:225)
	at org.eclipse.jdt.internal.junit.runner.junit3.JUnit3TestReference.run(JUnit3TestReference.java:130)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:460)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:673)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:386)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:196)
01-16 11:21:52 jdbc[2]: SQLException
org.h2.jdbc.JdbcSQLException: Table CASSA not found; SQL statement:
alter table CASSA drop constraint FK3CEF4C3C56C4797 [42102-69]
	at org.h2.message.Message.getSQLException(Message.java:91)
	at org.h2.message.Message.getSQLException(Message.java:95)
	at org.h2.message.Message.getSQLException(Message.java:73)
	at org.h2.command.Parser.readTableOrView(Parser.java:4025)
	at org.h2.command.Parser.readTableOrView(Parser.java:4005)
	at org.h2.command.Parser.parseAlterTable(Parser.java:4050)
	at org.h2.command.Parser.parseAlter(Parser.java:3622)
	at org.h2.command.Parser.parsePrepared(Parser.java:302)
	at org.h2.command.Parser.parse(Parser.java:285)
	at org.h2.command.Parser.parse(Parser.java:257)
	at org.h2.command.Parser.prepareCommand(Parser.java:229)
	at org.h2.engine.Session.prepareLocal(Session.java:236)
	at org.h2.engine.Session.prepareCommand(Session.java:218)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1020)
	at org.h2.jdbc.JdbcStatement.executeUpdate(JdbcStatement.java:104)
	at org.hibernate.tool.hbm2ddl.SchemaExport.execute(SchemaExport.java:308)
	at org.hibernate.tool.hbm2ddl.SchemaExport.drop(SchemaExport.java:284)
	at org.hibernate.tool.hbm2ddl.SchemaExport.execute(SchemaExport.java:186)
	at org.hibernate.tool.hbm2ddl.SchemaExport.create(SchemaExport.java:133)
	at org.hibernate.impl.SessionFactoryImpl.<init>(SessionFactoryImpl.java:311)
	at org.hibernate.cfg.Configuration.buildSessionFactory(Configuration.java:1300)
	at store.util.HibernateUtil.<clinit>(HibernateUtil.java:8)
	at test.testStore.TestSet01_HibernateUtil.testFactory(TestSet01_HibernateUtil.java:35)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:585)
	at junit.framework.TestCase.runTest(TestCase.java:164)
	at junit.framework.TestCase.runBare(TestCase.java:130)
	at junit.framework.TestResult$1.protect(TestResult.java:106)
	at junit.framework.TestResult.runProtected(TestResult.java:124)
	at junit.framework.TestResult.run(TestResult.java:109)
	at junit.framework.TestCase.run(TestCase.java:120)
	at junit.framework.TestSuite.runTest(TestSuite.java:230)
	at junit.framework.TestSuite.run(TestSuite.java:225)
	at org.eclipse.jdt.internal.junit.runner.junit3.JUnit3TestReference.run(JUnit3TestReference.java:130)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:460)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:673)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:386)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:196)
01-16 11:21:52 jdbc[2]: SQLException
org.h2.jdbc.JdbcSQLException: Table MOVIMENTO_CASSA not found; SQL statement:
alter table MOVIMENTO_CASSA drop constraint FKE865F2C0C2467AFD [42102-69]
	at org.h2.message.Message.getSQLException(Message.java:91)
	at org.h2.message.Message.getSQLException(Message.java:95)
	at org.h2.message.Message.getSQLException(Message.java:73)
	at org.h2.command.Parser.readTableOrView(Parser.java:4025)
	at org.h2.command.Parser.readTableOrView(Parser.java:4005)
	at org.h2.command.Parser.parseAlterTable(Parser.java:4050)
	at org.h2.command.Parser.parseAlter(Parser.java:3622)
	at org.h2.command.Parser.parsePrepared(Parser.java:302)
	at org.h2.command.Parser.parse(Parser.java:285)
	at org.h2.command.Parser.parse(Parser.java:257)
	at org.h2.command.Parser.prepareCommand(Parser.java:229)
	at org.h2.engine.Session.prepareLocal(Session.java:236)
	at org.h2.engine.Session.prepareCommand(Session.java:218)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1020)
	at org.h2.jdbc.JdbcStatement.executeUpdate(JdbcStatement.java:104)
	at org.hibernate.tool.hbm2ddl.SchemaExport.execute(SchemaExport.java:308)
	at org.hibernate.tool.hbm2ddl.SchemaExport.drop(SchemaExport.java:284)
	at org.hibernate.tool.hbm2ddl.SchemaExport.execute(SchemaExport.java:186)
	at org.hibernate.tool.hbm2ddl.SchemaExport.create(SchemaExport.java:133)
	at org.hibernate.impl.SessionFactoryImpl.<init>(SessionFactoryImpl.java:311)
	at org.hibernate.cfg.Configuration.buildSessionFactory(Configuration.java:1300)
	at store.util.HibernateUtil.<clinit>(HibernateUtil.java:8)
	at test.testStore.TestSet01_HibernateUtil.testFactory(TestSet01_HibernateUtil.java:35)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:585)
	at junit.framework.TestCase.runTest(TestCase.java:164)
	at junit.framework.TestCase.runBare(TestCase.java:130)
	at junit.framework.TestResult$1.protect(TestResult.java:106)
	at junit.framework.TestResult.runProtected(TestResult.java:124)
	at junit.framework.TestResult.run(TestResult.java:109)
	at junit.framework.TestCase.run(TestCase.java:120)
	at junit.framework.TestSuite.runTest(TestSuite.java:230)
	at junit.framework.TestSuite.run(TestSuite.java:225)
	at org.eclipse.jdt.internal.junit.runner.junit3.JUnit3TestReference.run(JUnit3TestReference.java:130)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:460)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:673)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:386)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:196)
01-16 11:21:52 jdbc[2]: SQLException
org.h2.jdbc.JdbcSQLException: Table MOVIMENTO_CASSA not found; SQL statement:
alter table MOVIMENTO_CASSA drop constraint FKE865F2C0EC7432A8 [42102-69]
	at org.h2.message.Message.getSQLException(Message.java:91)
	at org.h2.message.Message.getSQLException(Message.java:95)
	at org.h2.message.Message.getSQLException(Message.java:73)
	at org.h2.command.Parser.readTableOrView(Parser.java:4025)
	at org.h2.command.Parser.readTableOrView(Parser.java:4005)
	at org.h2.command.Parser.parseAlterTable(Parser.java:4050)
	at org.h2.command.Parser.parseAlter(Parser.java:3622)
	at org.h2.command.Parser.parsePrepared(Parser.java:302)
	at org.h2.command.Parser.parse(Parser.java:285)
	at org.h2.command.Parser.parse(Parser.java:257)
	at org.h2.command.Parser.prepareCommand(Parser.java:229)
	at org.h2.engine.Session.prepareLocal(Session.java:236)
	at org.h2.engine.Session.prepareCommand(Session.java:218)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1020)
	at org.h2.jdbc.JdbcStatement.executeUpdate(JdbcStatement.java:104)
	at org.hibernate.tool.hbm2ddl.SchemaExport.execute(SchemaExport.java:308)
	at org.hibernate.tool.hbm2ddl.SchemaExport.drop(SchemaExport.java:284)
	at org.hibernate.tool.hbm2ddl.SchemaExport.execute(SchemaExport.java:186)
	at org.hibernate.tool.hbm2ddl.SchemaExport.create(SchemaExport.java:133)
	at org.hibernate.impl.SessionFactoryImpl.<init>(SessionFactoryImpl.java:311)
	at org.hibernate.cfg.Configuration.buildSessionFactory(Configuration.java:1300)
	at store.util.HibernateUtil.<clinit>(HibernateUtil.java:8)
	at test.testStore.TestSet01_HibernateUtil.testFactory(TestSet01_HibernateUtil.java:35)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:585)
	at junit.framework.TestCase.runTest(TestCase.java:164)
	at junit.framework.TestCase.runBare(TestCase.java:130)
	at junit.framework.TestResult$1.protect(TestResult.java:106)
	at junit.framework.TestResult.runProtected(TestResult.java:124)
	at junit.framework.TestResult.run(TestResult.java:109)
	at junit.framework.TestCase.run(TestCase.java:120)
	at junit.framework.TestSuite.runTest(TestSuite.java:230)
	at junit.framework.TestSuite.run(TestSuite.java:225)
	at org.eclipse.jdt.internal.junit.runner.junit3.JUnit3TestReference.run(JUnit3TestReference.java:130)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:460)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:673)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:386)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:196)
01-16 11:21:52 jdbc[2]: SQLException
org.h2.jdbc.JdbcSQLException: Table MOVIMENTO_CASSA not found; SQL statement:
alter table MOVIMENTO_CASSA drop constraint FKE865F2C0BE71F91 [42102-69]
	at org.h2.message.Message.getSQLException(Message.java:91)
	at org.h2.message.Message.getSQLException(Message.java:95)
	at org.h2.message.Message.getSQLException(Message.java:73)
	at org.h2.command.Parser.readTableOrView(Parser.java:4025)
	at org.h2.command.Parser.readTableOrView(Parser.java:4005)
	at org.h2.command.Parser.parseAlterTable(Parser.java:4050)
	at org.h2.command.Parser.parseAlter(Parser.java:3622)
	at org.h2.command.Parser.parsePrepared(Parser.java:302)
	at org.h2.command.Parser.parse(Parser.java:285)
	at org.h2.command.Parser.parse(Parser.java:257)
	at org.h2.command.Parser.prepareCommand(Parser.java:229)
	at org.h2.engine.Session.prepareLocal(Session.java:236)
	at org.h2.engine.Session.prepareCommand(Session.java:218)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1020)
	at org.h2.jdbc.JdbcStatement.executeUpdate(JdbcStatement.java:104)
	at org.hibernate.tool.hbm2ddl.SchemaExport.execute(SchemaExport.java:308)
	at org.hibernate.tool.hbm2ddl.SchemaExport.drop(SchemaExport.java:284)
	at org.hibernate.tool.hbm2ddl.SchemaExport.execute(SchemaExport.java:186)
	at org.hibernate.tool.hbm2ddl.SchemaExport.create(SchemaExport.java:133)
	at org.hibernate.impl.SessionFactoryImpl.<init>(SessionFactoryImpl.java:311)
	at org.hibernate.cfg.Configuration.buildSessionFactory(Configuration.java:1300)
	at store.util.HibernateUtil.<clinit>(HibernateUtil.java:8)
	at test.testStore.TestSet01_HibernateUtil.testFactory(TestSet01_HibernateUtil.java:35)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:585)
	at junit.framework.TestCase.runTest(TestCase.java:164)
	at junit.framework.TestCase.runBare(TestCase.java:130)
	at junit.framework.TestResult$1.protect(TestResult.java:106)
	at junit.framework.TestResult.runProtected(TestResult.java:124)
	at junit.framework.TestResult.run(TestResult.java:109)
	at junit.framework.TestCase.run(TestCase.java:120)
	at junit.framework.TestSuite.runTest(TestSuite.java:230)
	at junit.framework.TestSuite.run(TestSuite.java:225)
	at org.eclipse.jdt.internal.junit.runner.junit3.JUnit3TestReference.run(JUnit3TestReference.java:130)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:460)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:673)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:386)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:196)
01-16 11:21:52 jdbc[2]: SQLException
org.h2.jdbc.JdbcSQLException: Table PAGAMENTO not found; SQL statement:
alter table PAGAMENTO drop constraint FKD4B223062F175BF2 [42102-69]
	at org.h2.message.Message.getSQLException(Message.java:91)
	at org.h2.message.Message.getSQLException(Message.java:95)
	at org.h2.message.Message.getSQLException(Message.java:73)
	at org.h2.command.Parser.readTableOrView(Parser.java:4025)
	at org.h2.command.Parser.readTableOrView(Parser.java:4005)
	at org.h2.command.Parser.parseAlterTable(Parser.java:4050)
	at org.h2.command.Parser.parseAlter(Parser.java:3622)
	at org.h2.command.Parser.parsePrepared(Parser.java:302)
	at org.h2.command.Parser.parse(Parser.java:285)
	at org.h2.command.Parser.parse(Parser.java:257)
	at org.h2.command.Parser.prepareCommand(Parser.java:229)
	at org.h2.engine.Session.prepareLocal(Session.java:236)
	at org.h2.engine.Session.prepareCommand(Session.java:218)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1020)
	at org.h2.jdbc.JdbcStatement.executeUpdate(JdbcStatement.java:104)
	at org.hibernate.tool.hbm2ddl.SchemaExport.execute(SchemaExport.java:308)
	at org.hibernate.tool.hbm2ddl.SchemaExport.drop(SchemaExport.java:284)
	at org.hibernate.tool.hbm2ddl.SchemaExport.execute(SchemaExport.java:186)
	at org.hibernate.tool.hbm2ddl.SchemaExport.create(SchemaExport.java:133)
	at org.hibernate.impl.SessionFactoryImpl.<init>(SessionFactoryImpl.java:311)
	at org.hibernate.cfg.Configuration.buildSessionFactory(Configuration.java:1300)
	at store.util.HibernateUtil.<clinit>(HibernateUtil.java:8)
	at test.testStore.TestSet01_HibernateUtil.testFactory(TestSet01_HibernateUtil.java:35)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:585)
	at junit.framework.TestCase.runTest(TestCase.java:164)
	at junit.framework.TestCase.runBare(TestCase.java:130)
	at junit.framework.TestResult$1.protect(TestResult.java:106)
	at junit.framework.TestResult.runProtected(TestResult.java:124)
	at junit.framework.TestResult.run(TestResult.java:109)
	at junit.framework.TestCase.run(TestCase.java:120)
	at junit.framework.TestSuite.runTest(TestSuite.java:230)
	at junit.framework.TestSuite.run(TestSuite.java:225)
	at org.eclipse.jdt.internal.junit.runner.junit3.JUnit3TestReference.run(JUnit3TestReference.java:130)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:460)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:673)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:386)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:196)
01-16 11:21:52 jdbc[2]: SQLException
org.h2.jdbc.JdbcSQLException: Table PAGAMENTO not found; SQL statement:
alter table PAGAMENTO drop constraint FKD4B22306A1EC25D7 [42102-69]
	at org.h2.message.Message.getSQLException(Message.java:91)
	at org.h2.message.Message.getSQLException(Message.java:95)
	at org.h2.message.Message.getSQLException(Message.java:73)
	at org.h2.command.Parser.readTableOrView(Parser.java:4025)
	at org.h2.command.Parser.readTableOrView(Parser.java:4005)
	at org.h2.command.Parser.parseAlterTable(Parser.java:4050)
	at org.h2.command.Parser.parseAlter(Parser.java:3622)
	at org.h2.command.Parser.parsePrepared(Parser.java:302)
	at org.h2.command.Parser.parse(Parser.java:285)
	at org.h2.command.Parser.parse(Parser.java:257)
	at org.h2.command.Parser.prepareCommand(Parser.java:229)
	at org.h2.engine.Session.prepareLocal(Session.java:236)
	at org.h2.engine.Session.prepareCommand(Session.java:218)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1020)
	at org.h2.jdbc.JdbcStatement.executeUpdate(JdbcStatement.java:104)
	at org.hibernate.tool.hbm2ddl.SchemaExport.execute(SchemaExport.java:308)
	at org.hibernate.tool.hbm2ddl.SchemaExport.drop(SchemaExport.java:284)
	at org.hibernate.tool.hbm2ddl.SchemaExport.execute(SchemaExport.java:186)
	at org.hibernate.tool.hbm2ddl.SchemaExport.create(SchemaExport.java:133)
	at org.hibernate.impl.SessionFactoryImpl.<init>(SessionFactoryImpl.java:311)
	at org.hibernate.cfg.Configuration.buildSessionFactory(Configuration.java:1300)
	at store.util.HibernateUtil.<clinit>(HibernateUtil.java:8)
	at test.testStore.TestSet01_HibernateUtil.testFactory(TestSet01_HibernateUtil.java:35)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:585)
	at junit.framework.TestCase.runTest(TestCase.java:164)
	at junit.framework.TestCase.runBare(TestCase.java:130)
	at junit.framework.TestResult$1.protect(TestResult.java:106)
	at junit.framework.TestResult.runProtected(TestResult.java:124)
	at junit.framework.TestResult.run(TestResult.java:109)
	at junit.framework.TestCase.run(TestCase.java:120)
	at junit.framework.TestSuite.runTest(TestSuite.java:230)
	at junit.framework.TestSuite.run(TestSuite.java:225)
	at org.eclipse.jdt.internal.junit.runner.junit3.JUnit3TestReference.run(JUnit3TestReference.java:130)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:460)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:673)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:386)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:196)
01-16 11:21:52 jdbc[2]: SQLException
org.h2.jdbc.JdbcSQLException: Table PAGAMENTO not found; SQL statement:
alter table PAGAMENTO drop constraint FKD4B22306A2884757 [42102-69]
	at org.h2.message.Message.getSQLException(Message.java:91)
	at org.h2.message.Message.getSQLException(Message.java:95)
	at org.h2.message.Message.getSQLException(Message.java:73)
	at org.h2.command.Parser.readTableOrView(Parser.java:4025)
	at org.h2.command.Parser.readTableOrView(Parser.java:4005)
	at org.h2.command.Parser.parseAlterTable(Parser.java:4050)
	at org.h2.command.Parser.parseAlter(Parser.java:3622)
	at org.h2.command.Parser.parsePrepared(Parser.java:302)
	at org.h2.command.Parser.parse(Parser.java:285)
	at org.h2.command.Parser.parse(Parser.java:257)
	at org.h2.command.Parser.prepareCommand(Parser.java:229)
	at org.h2.engine.Session.prepareLocal(Session.java:236)
	at org.h2.engine.Session.prepareCommand(Session.java:218)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1020)
	at org.h2.jdbc.JdbcStatement.executeUpdate(JdbcStatement.java:104)
	at org.hibernate.tool.hbm2ddl.SchemaExport.execute(SchemaExport.java:308)
	at org.hibernate.tool.hbm2ddl.SchemaExport.drop(SchemaExport.java:284)
	at org.hibernate.tool.hbm2ddl.SchemaExport.execute(SchemaExport.java:186)
	at org.hibernate.tool.hbm2ddl.SchemaExport.create(SchemaExport.java:133)
	at org.hibernate.impl.SessionFactoryImpl.<init>(SessionFactoryImpl.java:311)
	at org.hibernate.cfg.Configuration.buildSessionFactory(Configuration.java:1300)
	at store.util.HibernateUtil.<clinit>(HibernateUtil.java:8)
	at test.testStore.TestSet01_HibernateUtil.testFactory(TestSet01_HibernateUtil.java:35)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:585)
	at junit.framework.TestCase.runTest(TestCase.java:164)
	at junit.framework.TestCase.runBare(TestCase.java:130)
	at junit.framework.TestResult$1.protect(TestResult.java:106)
	at junit.framework.TestResult.runProtected(TestResult.java:124)
	at junit.framework.TestResult.run(TestResult.java:109)
	at junit.framework.TestCase.run(TestCase.java:120)
	at junit.framework.TestSuite.runTest(TestSuite.java:230)
	at junit.framework.TestSuite.run(TestSuite.java:225)
	at org.eclipse.jdt.internal.junit.runner.junit3.JUnit3TestReference.run(JUnit3TestReference.java:130)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:460)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:673)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:386)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:196)
01-16 11:21:52 jdbc[2]: SQLException
org.h2.jdbc.JdbcSQLException: Table PAGAMENTO not found; SQL statement:
alter table PAGAMENTO drop constraint FKD4B223066AA91D9D [42102-69]
	at org.h2.message.Message.getSQLException(Message.java:91)
	at org.h2.message.Message.getSQLException(Message.java:95)
	at org.h2.message.Message.getSQLException(Message.java:73)
	at org.h2.command.Parser.readTableOrView(Parser.java:4025)
	at org.h2.command.Parser.readTableOrView(Parser.java:4005)
	at org.h2.command.Parser.parseAlterTable(Parser.java:4050)
	at org.h2.command.Parser.parseAlter(Parser.java:3622)
	at org.h2.command.Parser.parsePrepared(Parser.java:302)
	at org.h2.command.Parser.parse(Parser.java:285)
	at org.h2.command.Parser.parse(Parser.java:257)
	at org.h2.command.Parser.prepareCommand(Parser.java:229)
	at org.h2.engine.Session.prepareLocal(Session.java:236)
	at org.h2.engine.Session.prepareCommand(Session.java:218)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1020)
	at org.h2.jdbc.JdbcStatement.executeUpdate(JdbcStatement.java:104)
	at org.hibernate.tool.hbm2ddl.SchemaExport.execute(SchemaExport.java:308)
	at org.hibernate.tool.hbm2ddl.SchemaExport.drop(SchemaExport.java:284)
	at org.hibernate.tool.hbm2ddl.SchemaExport.execute(SchemaExport.java:186)
	at org.hibernate.tool.hbm2ddl.SchemaExport.create(SchemaExport.java:133)
	at org.hibernate.impl.SessionFactoryImpl.<init>(SessionFactoryImpl.java:311)
	at org.hibernate.cfg.Configuration.buildSessionFactory(Configuration.java:1300)
	at store.util.HibernateUtil.<clinit>(HibernateUtil.java:8)
	at test.testStore.TestSet01_HibernateUtil.testFactory(TestSet01_HibernateUtil.java:35)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:585)
	at junit.framework.TestCase.runTest(TestCase.java:164)
	at junit.framework.TestCase.runBare(TestCase.java:130)
	at junit.framework.TestResult$1.protect(TestResult.java:106)
	at junit.framework.TestResult.runProtected(TestResult.java:124)
	at junit.framework.TestResult.run(TestResult.java:109)
	at junit.framework.TestCase.run(TestCase.java:120)
	at junit.framework.TestSuite.runTest(TestSuite.java:230)
	at junit.framework.TestSuite.run(TestSuite.java:225)
	at org.eclipse.jdt.internal.junit.runner.junit3.JUnit3TestReference.run(JUnit3TestReference.java:130)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:460)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:673)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:386)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:196)
01-16 11:21:52 jdbc[2]: SQLException
org.h2.jdbc.JdbcSQLException: Table PAGAMENTO not found; SQL statement:
alter table PAGAMENTO drop constraint FKD4B22306D92D4FAA [42102-69]
	at org.h2.message.Message.getSQLException(Message.java:91)
	at org.h2.message.Message.getSQLException(Message.java:95)
	at org.h2.message.Message.getSQLException(Message.java:73)
	at org.h2.command.Parser.readTableOrView(Parser.java:4025)
	at org.h2.command.Parser.readTableOrView(Parser.java:4005)
	at org.h2.command.Parser.parseAlterTable(Parser.java:4050)
	at org.h2.command.Parser.parseAlter(Parser.java:3622)
	at org.h2.command.Parser.parsePrepared(Parser.java:302)
	at org.h2.command.Parser.parse(Parser.java:285)
	at org.h2.command.Parser.parse(Parser.java:257)
	at org.h2.command.Parser.prepareCommand(Parser.java:229)
	at org.h2.engine.Session.prepareLocal(Session.java:236)
	at org.h2.engine.Session.prepareCommand(Session.java:218)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1020)
	at org.h2.jdbc.JdbcStatement.executeUpdate(JdbcStatement.java:104)
	at org.hibernate.tool.hbm2ddl.SchemaExport.execute(SchemaExport.java:308)
	at org.hibernate.tool.hbm2ddl.SchemaExport.drop(SchemaExport.java:284)
	at org.hibernate.tool.hbm2ddl.SchemaExport.execute(SchemaExport.java:186)
	at org.hibernate.tool.hbm2ddl.SchemaExport.create(SchemaExport.java:133)
	at org.hibernate.impl.SessionFactoryImpl.<init>(SessionFactoryImpl.java:311)
	at org.hibernate.cfg.Configuration.buildSessionFactory(Configuration.java:1300)
	at store.util.HibernateUtil.<clinit>(HibernateUtil.java:8)
	at test.testStore.TestSet01_HibernateUtil.testFactory(TestSet01_HibernateUtil.java:35)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:585)
	at junit.framework.TestCase.runTest(TestCase.java:164)
	at junit.framework.TestCase.runBare(TestCase.java:130)
	at junit.framework.TestResult$1.protect(TestResult.java:106)
	at junit.framework.TestResult.runProtected(TestResult.java:124)
	at junit.framework.TestResult.run(TestResult.java:109)
	at junit.framework.TestCase.run(TestCase.java:120)
	at junit.framework.TestSuite.runTest(TestSuite.java:230)
	at junit.framework.TestSuite.run(TestSuite.java:225)
	at org.eclipse.jdt.internal.junit.runner.junit3.JUnit3TestReference.run(JUnit3TestReference.java:130)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:460)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:673)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:386)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:196)
01-16 11:21:52 jdbc[2]: SQLException
org.h2.jdbc.JdbcSQLException: Table PAGAMENTO not found; SQL statement:
alter table PAGAMENTO drop constraint FKD4B22306D4E54CE4 [42102-69]
	at org.h2.message.Message.getSQLException(Message.java:91)
	at org.h2.message.Message.getSQLException(Message.java:95)
	at org.h2.message.Message.getSQLException(Message.java:73)
	at org.h2.command.Parser.readTableOrView(Parser.java:4025)
	at org.h2.command.Parser.readTableOrView(Parser.java:4005)
	at org.h2.command.Parser.parseAlterTable(Parser.java:4050)
	at org.h2.command.Parser.parseAlter(Parser.java:3622)
	at org.h2.command.Parser.parsePrepared(Parser.java:302)
	at org.h2.command.Parser.parse(Parser.java:285)
	at org.h2.command.Parser.parse(Parser.java:257)
	at org.h2.command.Parser.prepareCommand(Parser.java:229)
	at org.h2.engine.Session.prepareLocal(Session.java:236)
	at org.h2.engine.Session.prepareCommand(Session.java:218)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1020)
	at org.h2.jdbc.JdbcStatement.executeUpdate(JdbcStatement.java:104)
	at org.hibernate.tool.hbm2ddl.SchemaExport.execute(SchemaExport.java:308)
	at org.hibernate.tool.hbm2ddl.SchemaExport.drop(SchemaExport.java:284)
	at org.hibernate.tool.hbm2ddl.SchemaExport.execute(SchemaExport.java:186)
	at org.hibernate.tool.hbm2ddl.SchemaExport.create(SchemaExport.java:133)
	at org.hibernate.impl.SessionFactoryImpl.<init>(SessionFactoryImpl.java:311)
	at org.hibernate.cfg.Configuration.buildSessionFactory(Configuration.java:1300)
	at store.util.HibernateUtil.<clinit>(HibernateUtil.java:8)
	at test.testStore.TestSet01_HibernateUtil.testFactory(TestSet01_HibernateUtil.java:35)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:585)
	at junit.framework.TestCase.runTest(TestCase.java:164)
	at junit.framework.TestCase.runBare(TestCase.java:130)
	at junit.framework.TestResult$1.protect(TestResult.java:106)
	at junit.framework.TestResult.runProtected(TestResult.java:124)
	at junit.framework.TestResult.run(TestResult.java:109)
	at junit.framework.TestCase.run(TestCase.java:120)
	at junit.framework.TestSuite.runTest(TestSuite.java:230)
	at junit.framework.TestSuite.run(TestSuite.java:225)
	at org.eclipse.jdt.internal.junit.runner.junit3.JUnit3TestReference.run(JUnit3TestReference.java:130)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:460)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:673)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:386)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:196)
01-16 11:21:52 jdbc[2]: SQLException
org.h2.jdbc.JdbcSQLException: Table PERSONA not found; SQL statement:
alter table PERSONA drop constraint FK25B5B8CFB9359D6 [42102-69]
	at org.h2.message.Message.getSQLException(Message.java:91)
	at org.h2.message.Message.getSQLException(Message.java:95)
	at org.h2.message.Message.getSQLException(Message.java:73)
	at org.h2.command.Parser.readTableOrView(Parser.java:4025)
	at org.h2.command.Parser.readTableOrView(Parser.java:4005)
	at org.h2.command.Parser.parseAlterTable(Parser.java:4050)
	at org.h2.command.Parser.parseAlter(Parser.java:3622)
	at org.h2.command.Parser.parsePrepared(Parser.java:302)
	at org.h2.command.Parser.parse(Parser.java:285)
	at org.h2.command.Parser.parse(Parser.java:257)
	at org.h2.command.Parser.prepareCommand(Parser.java:229)
	at org.h2.engine.Session.prepareLocal(Session.java:236)
	at org.h2.engine.Session.prepareCommand(Session.java:218)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1020)
	at org.h2.jdbc.JdbcStatement.executeUpdate(JdbcStatement.java:104)
	at org.hibernate.tool.hbm2ddl.SchemaExport.execute(SchemaExport.java:308)
	at org.hibernate.tool.hbm2ddl.SchemaExport.drop(SchemaExport.java:284)
	at org.hibernate.tool.hbm2ddl.SchemaExport.execute(SchemaExport.java:186)
	at org.hibernate.tool.hbm2ddl.SchemaExport.create(SchemaExport.java:133)
	at org.hibernate.impl.SessionFactoryImpl.<init>(SessionFactoryImpl.java:311)
	at org.hibernate.cfg.Configuration.buildSessionFactory(Configuration.java:1300)
	at store.util.HibernateUtil.<clinit>(HibernateUtil.java:8)
	at test.testStore.TestSet01_HibernateUtil.testFactory(TestSet01_HibernateUtil.java:35)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:585)
	at junit.framework.TestCase.runTest(TestCase.java:164)
	at junit.framework.TestCase.runBare(TestCase.java:130)
	at junit.framework.TestResult$1.protect(TestResult.java:106)
	at junit.framework.TestResult.runProtected(TestResult.java:124)
	at junit.framework.TestResult.run(TestResult.java:109)
	at junit.framework.TestCase.run(TestCase.java:120)
	at junit.framework.TestSuite.runTest(TestSuite.java:230)
	at junit.framework.TestSuite.run(TestSuite.java:225)
	at org.eclipse.jdt.internal.junit.runner.junit3.JUnit3TestReference.run(JUnit3TestReference.java:130)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:460)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:673)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:386)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:196)
01-16 11:21:52 jdbc[2]: SQLException
org.h2.jdbc.JdbcSQLException: Table PERSONA_FISICA not found; SQL statement:
alter table PERSONA_FISICA drop constraint FKA86B908A6AA91D9D [42102-69]
	at org.h2.message.Message.getSQLException(Message.java:91)
	at org.h2.message.Message.getSQLException(Message.java:95)
	at org.h2.message.Message.getSQLException(Message.java:73)
	at org.h2.command.Parser.readTableOrView(Parser.java:4025)
	at org.h2.command.Parser.readTableOrView(Parser.java:4005)
	at org.h2.command.Parser.parseAlterTable(Parser.java:4050)
	at org.h2.command.Parser.parseAlter(Parser.java:3622)
	at org.h2.command.Parser.parsePrepared(Parser.java:302)
	at org.h2.command.Parser.parse(Parser.java:285)
	at org.h2.command.Parser.parse(Parser.java:257)
	at org.h2.command.Parser.prepareCommand(Parser.java:229)
	at org.h2.engine.Session.prepareLocal(Session.java:236)
	at org.h2.engine.Session.prepareCommand(Session.java:218)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1020)
	at org.h2.jdbc.JdbcStatement.executeUpdate(JdbcStatement.java:104)
	at org.hibernate.tool.hbm2ddl.SchemaExport.execute(SchemaExport.java:308)
	at org.hibernate.tool.hbm2ddl.SchemaExport.drop(SchemaExport.java:284)
	at org.hibernate.tool.hbm2ddl.SchemaExport.execute(SchemaExport.java:186)
	at org.hibernate.tool.hbm2ddl.SchemaExport.create(SchemaExport.java:133)
	at org.hibernate.impl.SessionFactoryImpl.<init>(SessionFactoryImpl.java:311)
	at org.hibernate.cfg.Configuration.buildSessionFactory(Configuration.java:1300)
	at store.util.HibernateUtil.<clinit>(HibernateUtil.java:8)
	at test.testStore.TestSet01_HibernateUtil.testFactory(TestSet01_HibernateUtil.java:35)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:585)
	at junit.framework.TestCase.runTest(TestCase.java:164)
	at junit.framework.TestCase.runBare(TestCase.java:130)
	at junit.framework.TestResult$1.protect(TestResult.java:106)
	at junit.framework.TestResult.runProtected(TestResult.java:124)
	at junit.framework.TestResult.run(TestResult.java:109)
	at junit.framework.TestCase.run(TestCase.java:120)
	at junit.framework.TestSuite.runTest(TestSuite.java:230)
	at junit.framework.TestSuite.run(TestSuite.java:225)
	at org.eclipse.jdt.internal.junit.runner.junit3.JUnit3TestReference.run(JUnit3TestReference.java:130)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:460)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:673)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:386)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:196)
01-16 11:21:52 jdbc[2]: SQLException
org.h2.jdbc.JdbcSQLException: Table PERSONA_GIURIDICA not found; SQL statement:
alter table PERSONA_GIURIDICA drop constraint FK4B2CB2DA6AA91D9D [42102-69]
	at org.h2.message.Message.getSQLException(Message.java:91)
	at org.h2.message.Message.getSQLException(Message.java:95)
	at org.h2.message.Message.getSQLException(Message.java:73)
	at org.h2.command.Parser.readTableOrView(Parser.java:4025)
	at org.h2.command.Parser.readTableOrView(Parser.java:4005)
	at org.h2.command.Parser.parseAlterTable(Parser.java:4050)
	at org.h2.command.Parser.parseAlter(Parser.java:3622)
	at org.h2.command.Parser.parsePrepared(Parser.java:302)
	at org.h2.command.Parser.parse(Parser.java:285)
	at org.h2.command.Parser.parse(Parser.java:257)
	at org.h2.command.Parser.prepareCommand(Parser.java:229)
	at org.h2.engine.Session.prepareLocal(Session.java:236)
	at org.h2.engine.Session.prepareCommand(Session.java:218)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1020)
	at org.h2.jdbc.JdbcStatement.executeUpdate(JdbcStatement.java:104)
	at org.hibernate.tool.hbm2ddl.SchemaExport.execute(SchemaExport.java:308)
	at org.hibernate.tool.hbm2ddl.SchemaExport.drop(SchemaExport.java:284)
	at org.hibernate.tool.hbm2ddl.SchemaExport.execute(SchemaExport.java:186)
	at org.hibernate.tool.hbm2ddl.SchemaExport.create(SchemaExport.java:133)
	at org.hibernate.impl.SessionFactoryImpl.<init>(SessionFactoryImpl.java:311)
	at org.hibernate.cfg.Configuration.buildSessionFactory(Configuration.java:1300)
	at store.util.HibernateUtil.<clinit>(HibernateUtil.java:8)
	at test.testStore.TestSet01_HibernateUtil.testFactory(TestSet01_HibernateUtil.java:35)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:585)
	at junit.framework.TestCase.runTest(TestCase.java:164)
	at junit.framework.TestCase.runBare(TestCase.java:130)
	at junit.framework.TestResult$1.protect(TestResult.java:106)
	at junit.framework.TestResult.runProtected(TestResult.java:124)
	at junit.framework.TestResult.run(TestResult.java:109)
	at junit.framework.TestCase.run(TestCase.java:120)
	at junit.framework.TestSuite.runTest(TestSuite.java:230)
	at junit.framework.TestSuite.run(TestSuite.java:225)
	at org.eclipse.jdt.internal.junit.runner.junit3.JUnit3TestReference.run(JUnit3TestReference.java:130)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:460)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:673)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:386)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:196)
01-16 11:21:52 jdbc[2]: SQLException
org.h2.jdbc.JdbcSQLException: Table PERSONA_GIURIDICA not found; SQL statement:
alter table PERSONA_GIURIDICA drop constraint FK4B2CB2DAE0AC6D57 [42102-69]
	at org.h2.message.Message.getSQLException(Message.java:91)
	at org.h2.message.Message.getSQLException(Message.java:95)
	at org.h2.message.Message.getSQLException(Message.java:73)
	at org.h2.command.Parser.readTableOrView(Parser.java:4025)
	at org.h2.command.Parser.readTableOrView(Parser.java:4005)
	at org.h2.command.Parser.parseAlterTable(Parser.java:4050)
	at org.h2.command.Parser.parseAlter(Parser.java:3622)
	at org.h2.command.Parser.parsePrepared(Parser.java:302)
	at org.h2.command.Parser.parse(Parser.java:285)
	at org.h2.command.Parser.parse(Parser.java:257)
	at org.h2.command.Parser.prepareCommand(Parser.java:229)
	at org.h2.engine.Session.prepareLocal(Session.java:236)
	at org.h2.engine.Session.prepareCommand(Session.java:218)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1020)
	at org.h2.jdbc.JdbcStatement.executeUpdate(JdbcStatement.java:104)
	at org.hibernate.tool.hbm2ddl.SchemaExport.execute(SchemaExport.java:308)
	at org.hibernate.tool.hbm2ddl.SchemaExport.drop(SchemaExport.java:284)
	at org.hibernate.tool.hbm2ddl.SchemaExport.execute(SchemaExport.java:186)
	at org.hibernate.tool.hbm2ddl.SchemaExport.create(SchemaExport.java:133)
	at org.hibernate.impl.SessionFactoryImpl.<init>(SessionFactoryImpl.java:311)
	at org.hibernate.cfg.Configuration.buildSessionFactory(Configuration.java:1300)
	at store.util.HibernateUtil.<clinit>(HibernateUtil.java:8)
	at test.testStore.TestSet01_HibernateUtil.testFactory(TestSet01_HibernateUtil.java:35)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:585)
	at junit.framework.TestCase.runTest(TestCase.java:164)
	at junit.framework.TestCase.runBare(TestCase.java:130)
	at junit.framework.TestResult$1.protect(TestResult.java:106)
	at junit.framework.TestResult.runProtected(TestResult.java:124)
	at junit.framework.TestResult.run(TestResult.java:109)
	at junit.framework.TestCase.run(TestCase.java:120)
	at junit.framework.TestSuite.runTest(TestSuite.java:230)
	at junit.framework.TestSuite.run(TestSuite.java:225)
	at org.eclipse.jdt.internal.junit.runner.junit3.JUnit3TestReference.run(JUnit3TestReference.java:130)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:460)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:673)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:386)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:196)
01-16 11:21:52 jdbc[2]: SQLException
org.h2.jdbc.JdbcSQLException: Table PIANO_PAGAMENTI not found; SQL statement:
alter table PIANO_PAGAMENTI drop constraint FKD2BB036AA2884757 [42102-69]
	at org.h2.message.Message.getSQLException(Message.java:91)
	at org.h2.message.Message.getSQLException(Message.java:95)
	at org.h2.message.Message.getSQLException(Message.java:73)
	at org.h2.command.Parser.readTableOrView(Parser.java:4025)
	at org.h2.command.Parser.readTableOrView(Parser.java:4005)
	at org.h2.command.Parser.parseAlterTable(Parser.java:4050)
	at org.h2.command.Parser.parseAlter(Parser.java:3622)
	at org.h2.command.Parser.parsePrepared(Parser.java:302)
	at org.h2.command.Parser.parse(Parser.java:285)
	at org.h2.command.Parser.parse(Parser.java:257)
	at org.h2.command.Parser.prepareCommand(Parser.java:229)
	at org.h2.engine.Session.prepareLocal(Session.java:236)
	at org.h2.engine.Session.prepareCommand(Session.java:218)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1020)
	at org.h2.jdbc.JdbcStatement.executeUpdate(JdbcStatement.java:104)
	at org.hibernate.tool.hbm2ddl.SchemaExport.execute(SchemaExport.java:308)
	at org.hibernate.tool.hbm2ddl.SchemaExport.drop(SchemaExport.java:284)
	at org.hibernate.tool.hbm2ddl.SchemaExport.execute(SchemaExport.java:186)
	at org.hibernate.tool.hbm2ddl.SchemaExport.create(SchemaExport.java:133)
	at org.hibernate.impl.SessionFactoryImpl.<init>(SessionFactoryImpl.java:311)
	at org.hibernate.cfg.Configuration.buildSessionFactory(Configuration.java:1300)
	at store.util.HibernateUtil.<clinit>(HibernateUtil.java:8)
	at test.testStore.TestSet01_HibernateUtil.testFactory(TestSet01_HibernateUtil.java:35)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:585)
	at junit.framework.TestCase.runTest(TestCase.java:164)
	at junit.framework.TestCase.runBare(TestCase.java:130)
	at junit.framework.TestResult$1.protect(TestResult.java:106)
	at junit.framework.TestResult.runProtected(TestResult.java:124)
	at junit.framework.TestResult.run(TestResult.java:109)
	at junit.framework.TestCase.run(TestCase.java:120)
	at junit.framework.TestSuite.runTest(TestSuite.java:230)
	at junit.framework.TestSuite.run(TestSuite.java:225)
	at org.eclipse.jdt.internal.junit.runner.junit3.JUnit3TestReference.run(JUnit3TestReference.java:130)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:460)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:673)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:386)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:196)
01-16 11:21:52 jdbc[2]: SQLException
org.h2.jdbc.JdbcSQLException: Table PIANO_PAGAMENTI_ORDINARIO not found; SQL statement:
alter table PIANO_PAGAMENTI_ORDINARIO drop constraint FK76685728D4E54CE4 [42102-69]
	at org.h2.message.Message.getSQLException(Message.java:91)
	at org.h2.message.Message.getSQLException(Message.java:95)
	at org.h2.message.Message.getSQLException(Message.java:73)
	at org.h2.command.Parser.readTableOrView(Parser.java:4025)
	at org.h2.command.Parser.readTableOrView(Parser.java:4005)
	at org.h2.command.Parser.parseAlterTable(Parser.java:4050)
	at org.h2.command.Parser.parseAlter(Parser.java:3622)
	at org.h2.command.Parser.parsePrepared(Parser.java:302)
	at org.h2.command.Parser.parse(Parser.java:285)
	at org.h2.command.Parser.parse(Parser.java:257)
	at org.h2.command.Parser.prepareCommand(Parser.java:229)
	at org.h2.engine.Session.prepareLocal(Session.java:236)
	at org.h2.engine.Session.prepareCommand(Session.java:218)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1020)
	at org.h2.jdbc.JdbcStatement.executeUpdate(JdbcStatement.java:104)
	at org.hibernate.tool.hbm2ddl.SchemaExport.execute(SchemaExport.java:308)
	at org.hibernate.tool.hbm2ddl.SchemaExport.drop(SchemaExport.java:284)
	at org.hibernate.tool.hbm2ddl.SchemaExport.execute(SchemaExport.java:186)
	at org.hibernate.tool.hbm2ddl.SchemaExport.create(SchemaExport.java:133)
	at org.hibernate.impl.SessionFactoryImpl.<init>(SessionFactoryImpl.java:311)
	at org.hibernate.cfg.Configuration.buildSessionFactory(Configuration.java:1300)
	at store.util.HibernateUtil.<clinit>(HibernateUtil.java:8)
	at test.testStore.TestSet01_HibernateUtil.testFactory(TestSet01_HibernateUtil.java:35)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:585)
	at junit.framework.TestCase.runTest(TestCase.java:164)
	at junit.framework.TestCase.runBare(TestCase.java:130)
	at junit.framework.TestResult$1.protect(TestResult.java:106)
	at junit.framework.TestResult.runProtected(TestResult.java:124)
	at junit.framework.TestResult.run(TestResult.java:109)
	at junit.framework.TestCase.run(TestCase.java:120)
	at junit.framework.TestSuite.runTest(TestSuite.java:230)
	at junit.framework.TestSuite.run(TestSuite.java:225)
	at org.eclipse.jdt.internal.junit.runner.junit3.JUnit3TestReference.run(JUnit3TestReference.java:130)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:460)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:673)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:386)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:196)
01-16 11:21:52 jdbc[2]: SQLException
org.h2.jdbc.JdbcSQLException: Table PIANO_PAGAMENTI_STRAORDINARIO not found; SQL statement:
alter table PIANO_PAGAMENTI_STRAORDINARIO drop constraint FKAFF00358C6AE3230 [42102-69]
	at org.h2.message.Message.getSQLException(Message.java:91)
	at org.h2.message.Message.getSQLException(Message.java:95)
	at org.h2.message.Message.getSQLException(Message.java:73)
	at org.h2.command.Parser.readTableOrView(Parser.java:4025)
	at org.h2.command.Parser.readTableOrView(Parser.java:4005)
	at org.h2.command.Parser.parseAlterTable(Parser.java:4050)
	at org.h2.command.Parser.parseAlter(Parser.java:3622)
	at org.h2.command.Parser.parsePrepared(Parser.java:302)
	at org.h2.command.Parser.parse(Parser.java:285)
	at org.h2.command.Parser.parse(Parser.java:257)
	at org.h2.command.Parser.prepareCommand(Parser.java:229)
	at org.h2.engine.Session.prepareLocal(Session.java:236)
	at org.h2.engine.Session.prepareCommand(Session.java:218)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1020)
	at org.h2.jdbc.JdbcStatement.executeUpdate(JdbcStatement.java:104)
	at org.hibernate.tool.hbm2ddl.SchemaExport.execute(SchemaExport.java:308)
	at org.hibernate.tool.hbm2ddl.SchemaExport.drop(SchemaExport.java:284)
	at org.hibernate.tool.hbm2ddl.SchemaExport.execute(SchemaExport.java:186)
	at org.hibernate.tool.hbm2ddl.SchemaExport.create(SchemaExport.java:133)
	at org.hibernate.impl.SessionFactoryImpl.<init>(SessionFactoryImpl.java:311)
	at org.hibernate.cfg.Configuration.buildSessionFactory(Configuration.java:1300)
	at store.util.HibernateUtil.<clinit>(HibernateUtil.java:8)
	at test.testStore.TestSet01_HibernateUtil.testFactory(TestSet01_HibernateUtil.java:35)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:585)
	at junit.framework.TestCase.runTest(TestCase.java:164)
	at junit.framework.TestCase.runBare(TestCase.java:130)
	at junit.framework.TestResult$1.protect(TestResult.java:106)
	at junit.framework.TestResult.runProtected(TestResult.java:124)
	at junit.framework.TestResult.run(TestResult.java:109)
	at junit.framework.TestCase.run(TestCase.java:120)
	at junit.framework.TestSuite.runTest(TestSuite.java:230)
	at junit.framework.TestSuite.run(TestSuite.java:225)
	at org.eclipse.jdt.internal.junit.runner.junit3.JUnit3TestReference.run(JUnit3TestReference.java:130)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:460)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:673)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:386)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:196)
01-16 11:21:52 jdbc[2]: SQLException
org.h2.jdbc.JdbcSQLException: Table PIANO_PAGAMENTI_STRAORDINARIO not found; SQL statement:
alter table PIANO_PAGAMENTI_STRAORDINARIO drop constraint FKAFF00358D4E54CE4 [42102-69]
	at org.h2.message.Message.getSQLException(Message.java:91)
	at org.h2.message.Message.getSQLException(Message.java:95)
	at org.h2.message.Message.getSQLException(Message.java:73)
	at org.h2.command.Parser.readTableOrView(Parser.java:4025)
	at org.h2.command.Parser.readTableOrView(Parser.java:4005)
	at org.h2.command.Parser.parseAlterTable(Parser.java:4050)
	at org.h2.command.Parser.parseAlter(Parser.java:3622)
	at org.h2.command.Parser.parsePrepared(Parser.java:302)
	at org.h2.command.Parser.parse(Parser.java:285)
	at org.h2.command.Parser.parse(Parser.java:257)
	at org.h2.command.Parser.prepareCommand(Parser.java:229)
	at org.h2.engine.Session.prepareLocal(Session.java:236)
	at org.h2.engine.Session.prepareCommand(Session.java:218)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1020)
	at org.h2.jdbc.JdbcStatement.executeUpdate(JdbcStatement.java:104)
	at org.hibernate.tool.hbm2ddl.SchemaExport.execute(SchemaExport.java:308)
	at org.hibernate.tool.hbm2ddl.SchemaExport.drop(SchemaExport.java:284)
	at org.hibernate.tool.hbm2ddl.SchemaExport.execute(SchemaExport.java:186)
	at org.hibernate.tool.hbm2ddl.SchemaExport.create(SchemaExport.java:133)
	at org.hibernate.impl.SessionFactoryImpl.<init>(SessionFactoryImpl.java:311)
	at org.hibernate.cfg.Configuration.buildSessionFactory(Configuration.java:1300)
	at store.util.HibernateUtil.<clinit>(HibernateUtil.java:8)
	at test.testStore.TestSet01_HibernateUtil.testFactory(TestSet01_HibernateUtil.java:35)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:585)
	at junit.framework.TestCase.runTest(TestCase.java:164)
	at junit.framework.TestCase.runBare(TestCase.java:130)
	at junit.framework.TestResult$1.protect(TestResult.java:106)
	at junit.framework.TestResult.runProtected(TestResult.java:124)
	at junit.framework.TestResult.run(TestResult.java:109)
	at junit.framework.TestCase.run(TestCase.java:120)
	at junit.framework.TestSuite.runTest(TestSuite.java:230)
	at junit.framework.TestSuite.run(TestSuite.java:225)
	at org.eclipse.jdt.internal.junit.runner.junit3.JUnit3TestReference.run(JUnit3TestReference.java:130)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:460)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:673)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:386)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:196)
01-16 11:21:52 jdbc[2]: SQLException
org.h2.jdbc.JdbcSQLException: Table PROPRIETA not found; SQL statement:
alter table PROPRIETA drop constraint FK7BB8CE58464E24E7 [42102-69]
	at org.h2.message.Message.getSQLException(Message.java:91)
	at org.h2.message.Message.getSQLException(Message.java:95)
	at org.h2.message.Message.getSQLException(Message.java:73)
	at org.h2.command.Parser.readTableOrView(Parser.java:4025)
	at org.h2.command.Parser.readTableOrView(Parser.java:4005)
	at org.h2.command.Parser.parseAlterTable(Parser.java:4050)
	at org.h2.command.Parser.parseAlter(Parser.java:3622)
	at org.h2.command.Parser.parsePrepared(Parser.java:302)
	at org.h2.command.Parser.parse(Parser.java:285)
	at org.h2.command.Parser.parse(Parser.java:257)
	at org.h2.command.Parser.prepareCommand(Parser.java:229)
	at org.h2.engine.Session.prepareLocal(Session.java:236)
	at org.h2.engine.Session.prepareCommand(Session.java:218)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1020)
	at org.h2.jdbc.JdbcStatement.executeUpdate(JdbcStatement.java:104)
	at org.hibernate.tool.hbm2ddl.SchemaExport.execute(SchemaExport.java:308)
	at org.hibernate.tool.hbm2ddl.SchemaExport.drop(SchemaExport.java:284)
	at org.hibernate.tool.hbm2ddl.SchemaExport.execute(SchemaExport.java:186)
	at org.hibernate.tool.hbm2ddl.SchemaExport.create(SchemaExport.java:133)
	at org.hibernate.impl.SessionFactoryImpl.<init>(SessionFactoryImpl.java:311)
	at org.hibernate.cfg.Configuration.buildSessionFactory(Configuration.java:1300)
	at store.util.HibernateUtil.<clinit>(HibernateUtil.java:8)
	at test.testStore.TestSet01_HibernateUtil.testFactory(TestSet01_HibernateUtil.java:35)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:585)
	at junit.framework.TestCase.runTest(TestCase.java:164)
	at junit.framework.TestCase.runBare(TestCase.java:130)
	at junit.framework.TestResult$1.protect(TestResult.java:106)
	at junit.framework.TestResult.runProtected(TestResult.java:124)
	at junit.framework.TestResult.run(TestResult.java:109)
	at junit.framework.TestCase.run(TestCase.java:120)
	at junit.framework.TestSuite.runTest(TestSuite.java:230)
	at junit.framework.TestSuite.run(TestSuite.java:225)
	at org.eclipse.jdt.internal.junit.runner.junit3.JUnit3TestReference.run(JUnit3TestReference.java:130)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:460)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:673)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:386)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:196)
01-16 11:21:52 jdbc[2]: SQLException
org.h2.jdbc.JdbcSQLException: Table PROPRIETA_PERSONE not found; SQL statement:
alter table PROPRIETA_PERSONE drop constraint FKDB7BF8A96AA91D9D [42102-69]
	at org.h2.message.Message.getSQLException(Message.java:91)
	at org.h2.message.Message.getSQLException(Message.java:95)
	at org.h2.message.Message.getSQLException(Message.java:73)
	at org.h2.command.Parser.readTableOrView(Parser.java:4025)
	at org.h2.command.Parser.readTableOrView(Parser.java:4005)
	at org.h2.command.Parser.parseAlterTable(Parser.java:4050)
	at org.h2.command.Parser.parseAlter(Parser.java:3622)
	at org.h2.command.Parser.parsePrepared(Parser.java:302)
	at org.h2.command.Parser.parse(Parser.java:285)
	at org.h2.command.Parser.parse(Parser.java:257)
	at org.h2.command.Parser.prepareCommand(Parser.java:229)
	at org.h2.engine.Session.prepareLocal(Session.java:236)
	at org.h2.engine.Session.prepareCommand(Session.java:218)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1020)
	at org.h2.jdbc.JdbcStatement.executeUpdate(JdbcStatement.java:104)
	at org.hibernate.tool.hbm2ddl.SchemaExport.execute(SchemaExport.java:308)
	at org.hibernate.tool.hbm2ddl.SchemaExport.drop(SchemaExport.java:284)
	at org.hibernate.tool.hbm2ddl.SchemaExport.execute(SchemaExport.java:186)
	at org.hibernate.tool.hbm2ddl.SchemaExport.create(SchemaExport.java:133)
	at org.hibernate.impl.SessionFactoryImpl.<init>(SessionFactoryImpl.java:311)
	at org.hibernate.cfg.Configuration.buildSessionFactory(Configuration.java:1300)
	at store.util.HibernateUtil.<clinit>(HibernateUtil.java:8)
	at test.testStore.TestSet01_HibernateUtil.testFactory(TestSet01_HibernateUtil.java:35)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:585)
	at junit.framework.TestCase.runTest(TestCase.java:164)
	at junit.framework.TestCase.runBare(TestCase.java:130)
	at junit.framework.TestResult$1.protect(TestResult.java:106)
	at junit.framework.TestResult.runProtected(TestResult.java:124)
	at junit.framework.TestResult.run(TestResult.java:109)
	at junit.framework.TestCase.run(TestCase.java:120)
	at junit.framework.TestSuite.runTest(TestSuite.java:230)
	at junit.framework.TestSuite.run(TestSuite.java:225)
	at org.eclipse.jdt.internal.junit.runner.junit3.JUnit3TestReference.run(JUnit3TestReference.java:130)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:460)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:673)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:386)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:196)
01-16 11:21:52 jdbc[2]: SQLException
org.h2.jdbc.JdbcSQLException: Table PROPRIETA_PERSONE not found; SQL statement:
alter table PROPRIETA_PERSONE drop constraint FKDB7BF8A934ADCD5D [42102-69]
	at org.h2.message.Message.getSQLException(Message.java:91)
	at org.h2.message.Message.getSQLException(Message.java:95)
	at org.h2.message.Message.getSQLException(Message.java:73)
	at org.h2.command.Parser.readTableOrView(Parser.java:4025)
	at org.h2.command.Parser.readTableOrView(Parser.java:4005)
	at org.h2.command.Parser.parseAlterTable(Parser.java:4050)
	at org.h2.command.Parser.parseAlter(Parser.java:3622)
	at org.h2.command.Parser.parsePrepared(Parser.java:302)
	at org.h2.command.Parser.parse(Parser.java:285)
	at org.h2.command.Parser.parse(Parser.java:257)
	at org.h2.command.Parser.prepareCommand(Parser.java:229)
	at org.h2.engine.Session.prepareLocal(Session.java:236)
	at org.h2.engine.Session.prepareCommand(Session.java:218)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1020)
	at org.h2.jdbc.JdbcStatement.executeUpdate(JdbcStatement.java:104)
	at org.hibernate.tool.hbm2ddl.SchemaExport.execute(SchemaExport.java:308)
	at org.hibernate.tool.hbm2ddl.SchemaExport.drop(SchemaExport.java:284)
	at org.hibernate.tool.hbm2ddl.SchemaExport.execute(SchemaExport.java:186)
	at org.hibernate.tool.hbm2ddl.SchemaExport.create(SchemaExport.java:133)
	at org.hibernate.impl.SessionFactoryImpl.<init>(SessionFactoryImpl.java:311)
	at org.hibernate.cfg.Configuration.buildSessionFactory(Configuration.java:1300)
	at store.util.HibernateUtil.<clinit>(HibernateUtil.java:8)
	at test.testStore.TestSet01_HibernateUtil.testFactory(TestSet01_HibernateUtil.java:35)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:585)
	at junit.framework.TestCase.runTest(TestCase.java:164)
	at junit.framework.TestCase.runBare(TestCase.java:130)
	at junit.framework.TestResult$1.protect(TestResult.java:106)
	at junit.framework.TestResult.runProtected(TestResult.java:124)
	at junit.framework.TestResult.run(TestResult.java:109)
	at junit.framework.TestCase.run(TestCase.java:120)
	at junit.framework.TestSuite.runTest(TestSuite.java:230)
	at junit.framework.TestSuite.run(TestSuite.java:225)
	at org.eclipse.jdt.internal.junit.runner.junit3.JUnit3TestReference.run(JUnit3TestReference.java:130)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:460)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:673)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:386)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:196)
01-16 11:21:52 jdbc[2]: SQLException
org.h2.jdbc.JdbcSQLException: Table TABELLA_MILLESIMALE not found; SQL statement:
alter table TABELLA_MILLESIMALE drop constraint FK42F9245EC56C4797 [42102-69]
	at org.h2.message.Message.getSQLException(Message.java:91)
	at org.h2.message.Message.getSQLException(Message.java:95)
	at org.h2.message.Message.getSQLException(Message.java:73)
	at org.h2.command.Parser.readTableOrView(Parser.java:4025)
	at org.h2.command.Parser.readTableOrView(Parser.java:4005)
	at org.h2.command.Parser.parseAlterTable(Parser.java:4050)
	at org.h2.command.Parser.parseAlter(Parser.java:3622)
	at org.h2.command.Parser.parsePrepared(Parser.java:302)
	at org.h2.command.Parser.parse(Parser.java:285)
	at org.h2.command.Parser.parse(Parser.java:257)
	at org.h2.command.Parser.prepareCommand(Parser.java:229)
	at org.h2.engine.Session.prepareLocal(Session.java:236)
	at org.h2.engine.Session.prepareCommand(Session.java:218)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1020)
	at org.h2.jdbc.JdbcStatement.executeUpdate(JdbcStatement.java:104)
	at org.hibernate.tool.hbm2ddl.SchemaExport.execute(SchemaExport.java:308)
	at org.hibernate.tool.hbm2ddl.SchemaExport.drop(SchemaExport.java:284)
	at org.hibernate.tool.hbm2ddl.SchemaExport.execute(SchemaExport.java:186)
	at org.hibernate.tool.hbm2ddl.SchemaExport.create(SchemaExport.java:133)
	at org.hibernate.impl.SessionFactoryImpl.<init>(SessionFactoryImpl.java:311)
	at org.hibernate.cfg.Configuration.buildSessionFactory(Configuration.java:1300)
	at store.util.HibernateUtil.<clinit>(HibernateUtil.java:8)
	at test.testStore.TestSet01_HibernateUtil.testFactory(TestSet01_HibernateUtil.java:35)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:585)
	at junit.framework.TestCase.runTest(TestCase.java:164)
	at junit.framework.TestCase.runBare(TestCase.java:130)
	at junit.framework.TestResult$1.protect(TestResult.java:106)
	at junit.framework.TestResult.runProtected(TestResult.java:124)
	at junit.framework.TestResult.run(TestResult.java:109)
	at junit.framework.TestCase.run(TestCase.java:120)
	at junit.framework.TestSuite.runTest(TestSuite.java:230)
	at junit.framework.TestSuite.run(TestSuite.java:225)
	at org.eclipse.jdt.internal.junit.runner.junit3.JUnit3TestReference.run(JUnit3TestReference.java:130)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:460)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:673)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:386)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:196)
01-16 11:21:52 jdbc[2]: SQLException
org.h2.jdbc.JdbcSQLException: Table TABELLA_MILLESIMALE not found; SQL statement:
alter table TABELLA_MILLESIMALE drop constraint FK42F9245E13C29DF1 [42102-69]
	at org.h2.message.Message.getSQLException(Message.java:91)
	at org.h2.message.Message.getSQLException(Message.java:95)
	at org.h2.message.Message.getSQLException(Message.java:73)
	at org.h2.command.Parser.readTableOrView(Parser.java:4025)
	at org.h2.command.Parser.readTableOrView(Parser.java:4005)
	at org.h2.command.Parser.parseAlterTable(Parser.java:4050)
	at org.h2.command.Parser.parseAlter(Parser.java:3622)
	at org.h2.command.Parser.parsePrepared(Parser.java:302)
	at org.h2.command.Parser.parse(Parser.java:285)
	at org.h2.command.Parser.parse(Parser.java:257)
	at org.h2.command.Parser.prepareCommand(Parser.java:229)
	at org.h2.engine.Session.prepareLocal(Session.java:236)
	at org.h2.engine.Session.prepareCommand(Session.java:218)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1020)
	at org.h2.jdbc.JdbcStatement.executeUpdate(JdbcStatement.java:104)
	at org.hibernate.tool.hbm2ddl.SchemaExport.execute(SchemaExport.java:308)
	at org.hibernate.tool.hbm2ddl.SchemaExport.drop(SchemaExport.java:284)
	at org.hibernate.tool.hbm2ddl.SchemaExport.execute(SchemaExport.java:186)
	at org.hibernate.tool.hbm2ddl.SchemaExport.create(SchemaExport.java:133)
	at org.hibernate.impl.SessionFactoryImpl.<init>(SessionFactoryImpl.java:311)
	at org.hibernate.cfg.Configuration.buildSessionFactory(Configuration.java:1300)
	at store.util.HibernateUtil.<clinit>(HibernateUtil.java:8)
	at test.testStore.TestSet01_HibernateUtil.testFactory(TestSet01_HibernateUtil.java:35)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:585)
	at junit.framework.TestCase.runTest(TestCase.java:164)
	at junit.framework.TestCase.runBare(TestCase.java:130)
	at junit.framework.TestResult$1.protect(TestResult.java:106)
	at junit.framework.TestResult.runProtected(TestResult.java:124)
	at junit.framework.TestResult.run(TestResult.java:109)
	at junit.framework.TestCase.run(TestCase.java:120)
	at junit.framework.TestSuite.runTest(TestSuite.java:230)
	at junit.framework.TestSuite.run(TestSuite.java:225)
	at org.eclipse.jdt.internal.junit.runner.junit3.JUnit3TestReference.run(JUnit3TestReference.java:130)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:460)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:673)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:386)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:196)
01-16 11:21:52 jdbc[2]: SQLException
org.h2.jdbc.JdbcSQLException: Table UNITA_IMMOBILIARE not found; SQL statement:
alter table UNITA_IMMOBILIARE drop constraint FK63FF3928C56C4797 [42102-69]
	at org.h2.message.Message.getSQLException(Message.java:91)
	at org.h2.message.Message.getSQLException(Message.java:95)
	at org.h2.message.Message.getSQLException(Message.java:73)
	at org.h2.command.Parser.readTableOrView(Parser.java:4025)
	at org.h2.command.Parser.readTableOrView(Parser.java:4005)
	at org.h2.command.Parser.parseAlterTable(Parser.java:4050)
	at org.h2.command.Parser.parseAlter(Parser.java:3622)
	at org.h2.command.Parser.parsePrepared(Parser.java:302)
	at org.h2.command.Parser.parse(Parser.java:285)
	at org.h2.command.Parser.parse(Parser.java:257)
	at org.h2.command.Parser.prepareCommand(Parser.java:229)
	at org.h2.engine.Session.prepareLocal(Session.java:236)
	at org.h2.engine.Session.prepareCommand(Session.java:218)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1020)
	at org.h2.jdbc.JdbcStatement.executeUpdate(JdbcStatement.java:104)
	at org.hibernate.tool.hbm2ddl.SchemaExport.execute(SchemaExport.java:308)
	at org.hibernate.tool.hbm2ddl.SchemaExport.drop(SchemaExport.java:284)
	at org.hibernate.tool.hbm2ddl.SchemaExport.execute(SchemaExport.java:186)
	at org.hibernate.tool.hbm2ddl.SchemaExport.create(SchemaExport.java:133)
	at org.hibernate.impl.SessionFactoryImpl.<init>(SessionFactoryImpl.java:311)
	at org.hibernate.cfg.Configuration.buildSessionFactory(Configuration.java:1300)
	at store.util.HibernateUtil.<clinit>(HibernateUtil.java:8)
	at test.testStore.TestSet01_HibernateUtil.testFactory(TestSet01_HibernateUtil.java:35)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:585)
	at junit.framework.TestCase.runTest(TestCase.java:164)
	at junit.framework.TestCase.runBare(TestCase.java:130)
	at junit.framework.TestResult$1.protect(TestResult.java:106)
	at junit.framework.TestResult.runProtected(TestResult.java:124)
	at junit.framework.TestResult.run(TestResult.java:109)
	at junit.framework.TestCase.run(TestCase.java:120)
	at junit.framework.TestSuite.runTest(TestSuite.java:230)
	at junit.framework.TestSuite.run(TestSuite.java:225)
	at org.eclipse.jdt.internal.junit.runner.junit3.JUnit3TestReference.run(JUnit3TestReference.java:130)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:460)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:673)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:386)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:196)
01-16 11:21:52 jdbc[2]: SQLException
org.h2.jdbc.JdbcSQLException: Table UNITA_IMMOBILIARE not found; SQL statement:
alter table UNITA_IMMOBILIARE drop constraint FK63FF3928C1ADE885 [42102-69]
	at org.h2.message.Message.getSQLException(Message.java:91)
	at org.h2.message.Message.getSQLException(Message.java:95)
	at org.h2.message.Message.getSQLException(Message.java:73)
	at org.h2.command.Parser.readTableOrView(Parser.java:4025)
	at org.h2.command.Parser.readTableOrView(Parser.java:4005)
	at org.h2.command.Parser.parseAlterTable(Parser.java:4050)
	at org.h2.command.Parser.parseAlter(Parser.java:3622)
	at org.h2.command.Parser.parsePrepared(Parser.java:302)
	at org.h2.command.Parser.parse(Parser.java:285)
	at org.h2.command.Parser.parse(Parser.java:257)
	at org.h2.command.Parser.prepareCommand(Parser.java:229)
	at org.h2.engine.Session.prepareLocal(Session.java:236)
	at org.h2.engine.Session.prepareCommand(Session.java:218)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1020)
	at org.h2.jdbc.JdbcStatement.executeUpdate(JdbcStatement.java:104)
	at org.hibernate.tool.hbm2ddl.SchemaExport.execute(SchemaExport.java:308)
	at org.hibernate.tool.hbm2ddl.SchemaExport.drop(SchemaExport.java:284)
	at org.hibernate.tool.hbm2ddl.SchemaExport.execute(SchemaExport.java:186)
	at org.hibernate.tool.hbm2ddl.SchemaExport.create(SchemaExport.java:133)
	at org.hibernate.impl.SessionFactoryImpl.<init>(SessionFactoryImpl.java:311)
	at org.hibernate.cfg.Configuration.buildSessionFactory(Configuration.java:1300)
	at store.util.HibernateUtil.<clinit>(HibernateUtil.java:8)
	at test.testStore.TestSet01_HibernateUtil.testFactory(TestSet01_HibernateUtil.java:35)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:585)
	at junit.framework.TestCase.runTest(TestCase.java:164)
	at junit.framework.TestCase.runBare(TestCase.java:130)
	at junit.framework.TestResult$1.protect(TestResult.java:106)
	at junit.framework.TestResult.runProtected(TestResult.java:124)
	at junit.framework.TestResult.run(TestResult.java:109)
	at junit.framework.TestCase.run(TestCase.java:120)
	at junit.framework.TestSuite.runTest(TestSuite.java:230)
	at junit.framework.TestSuite.run(TestSuite.java:225)
	at org.eclipse.jdt.internal.junit.runner.junit3.JUnit3TestReference.run(JUnit3TestReference.java:130)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:460)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:673)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:386)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:196)
01-16 11:21:52 jdbc[2]: SQLException
org.h2.jdbc.JdbcSQLException: Table VOCE_BILANCIO not found; SQL statement:
alter table VOCE_BILANCIO drop constraint FKB7FEE67BC6AE3230 [42102-69]
	at org.h2.message.Message.getSQLException(Message.java:91)
	at org.h2.message.Message.getSQLException(Message.java:95)
	at org.h2.message.Message.getSQLException(Message.java:73)
	at org.h2.command.Parser.readTableOrView(Parser.java:4025)
	at org.h2.command.Parser.readTableOrView(Parser.java:4005)
	at org.h2.command.Parser.parseAlterTable(Parser.java:4050)
	at org.h2.command.Parser.parseAlter(Parser.java:3622)
	at org.h2.command.Parser.parsePrepared(Parser.java:302)
	at org.h2.command.Parser.parse(Parser.java:285)
	at org.h2.command.Parser.parse(Parser.java:257)
	at org.h2.command.Parser.prepareCommand(Parser.java:229)
	at org.h2.engine.Session.prepareLocal(Session.java:236)
	at org.h2.engine.Session.prepareCommand(Session.java:218)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1020)
	at org.h2.jdbc.JdbcStatement.executeUpdate(JdbcStatement.java:104)
	at org.hibernate.tool.hbm2ddl.SchemaExport.execute(SchemaExport.java:308)
	at org.hibernate.tool.hbm2ddl.SchemaExport.drop(SchemaExport.java:284)
	at org.hibernate.tool.hbm2ddl.SchemaExport.execute(SchemaExport.java:186)
	at org.hibernate.tool.hbm2ddl.SchemaExport.create(SchemaExport.java:133)
	at org.hibernate.impl.SessionFactoryImpl.<init>(SessionFactoryImpl.java:311)
	at org.hibernate.cfg.Configuration.buildSessionFactory(Configuration.java:1300)
	at store.util.HibernateUtil.<clinit>(HibernateUtil.java:8)
	at test.testStore.TestSet01_HibernateUtil.testFactory(TestSet01_HibernateUtil.java:35)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:585)
	at junit.framework.TestCase.runTest(TestCase.java:164)
	at junit.framework.TestCase.runBare(TestCase.java:130)
	at junit.framework.TestResult$1.protect(TestResult.java:106)
	at junit.framework.TestResult.runProtected(TestResult.java:124)
	at junit.framework.TestResult.run(TestResult.java:109)
	at junit.framework.TestCase.run(TestCase.java:120)
	at junit.framework.TestSuite.runTest(TestSuite.java:230)
	at junit.framework.TestSuite.run(TestSuite.java:225)
	at org.eclipse.jdt.internal.junit.runner.junit3.JUnit3TestReference.run(JUnit3TestReference.java:130)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:460)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:673)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:386)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:196)
01-16 11:21:52 jdbc[2]: SQLException
org.h2.jdbc.JdbcSQLException: Table VOCE_BILANCIO not found; SQL statement:
alter table VOCE_BILANCIO drop constraint FKB7FEE67BA2884757 [42102-69]
	at org.h2.message.Message.getSQLException(Message.java:91)
	at org.h2.message.Message.getSQLException(Message.java:95)
	at org.h2.message.Message.getSQLException(Message.java:73)
	at org.h2.command.Parser.readTableOrView(Parser.java:4025)
	at org.h2.command.Parser.readTableOrView(Parser.java:4005)
	at org.h2.command.Parser.parseAlterTable(Parser.java:4050)
	at org.h2.command.Parser.parseAlter(Parser.java:3622)
	at org.h2.command.Parser.parsePrepared(Parser.java:302)
	at org.h2.command.Parser.parse(Parser.java:285)
	at org.h2.command.Parser.parse(Parser.java:257)
	at org.h2.command.Parser.prepareCommand(Parser.java:229)
	at org.h2.engine.Session.prepareLocal(Session.java:236)
	at org.h2.engine.Session.prepareCommand(Session.java:218)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1020)
	at org.h2.jdbc.JdbcStatement.executeUpdate(JdbcStatement.java:104)
	at org.hibernate.tool.hbm2ddl.SchemaExport.execute(SchemaExport.java:308)
	at org.hibernate.tool.hbm2ddl.SchemaExport.drop(SchemaExport.java:284)
	at org.hibernate.tool.hbm2ddl.SchemaExport.execute(SchemaExport.java:186)
	at org.hibernate.tool.hbm2ddl.SchemaExport.create(SchemaExport.java:133)
	at org.hibernate.impl.SessionFactoryImpl.<init>(SessionFactoryImpl.java:311)
	at org.hibernate.cfg.Configuration.buildSessionFactory(Configuration.java:1300)
	at store.util.HibernateUtil.<clinit>(HibernateUtil.java:8)
	at test.testStore.TestSet01_HibernateUtil.testFactory(TestSet01_HibernateUtil.java:35)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:585)
	at junit.framework.TestCase.runTest(TestCase.java:164)
	at junit.framework.TestCase.runBare(TestCase.java:130)
	at junit.framework.TestResult$1.protect(TestResult.java:106)
	at junit.framework.TestResult.runProtected(TestResult.java:124)
	at junit.framework.TestResult.run(TestResult.java:109)
	at junit.framework.TestCase.run(TestCase.java:120)
	at junit.framework.TestSuite.runTest(TestSuite.java:230)
	at junit.framework.TestSuite.run(TestSuite.java:225)
	at org.eclipse.jdt.internal.junit.runner.junit3.JUnit3TestReference.run(JUnit3TestReference.java:130)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:460)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:673)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:386)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:196)
01-16 11:21:52 jdbc[2]: SQLException
org.h2.jdbc.JdbcSQLException: Table VOCE_BILANCIO not found; SQL statement:
alter table VOCE_BILANCIO drop constraint FKB7FEE67B16A9B8E6 [42102-69]
	at org.h2.message.Message.getSQLException(Message.java:91)
	at org.h2.message.Message.getSQLException(Message.java:95)
	at org.h2.message.Message.getSQLException(Message.java:73)
	at org.h2.command.Parser.readTableOrView(Parser.java:4025)
	at org.h2.command.Parser.readTableOrView(Parser.java:4005)
	at org.h2.command.Parser.parseAlterTable(Parser.java:4050)
	at org.h2.command.Parser.parseAlter(Parser.java:3622)
	at org.h2.command.Parser.parsePrepared(Parser.java:302)
	at org.h2.command.Parser.parse(Parser.java:285)
	at org.h2.command.Parser.parse(Parser.java:257)
	at org.h2.command.Parser.prepareCommand(Parser.java:229)
	at org.h2.engine.Session.prepareLocal(Session.java:236)
	at org.h2.engine.Session.prepareCommand(Session.java:218)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1020)
	at org.h2.jdbc.JdbcStatement.executeUpdate(JdbcStatement.java:104)
	at org.hibernate.tool.hbm2ddl.SchemaExport.execute(SchemaExport.java:308)
	at org.hibernate.tool.hbm2ddl.SchemaExport.drop(SchemaExport.java:284)
	at org.hibernate.tool.hbm2ddl.SchemaExport.execute(SchemaExport.java:186)
	at org.hibernate.tool.hbm2ddl.SchemaExport.create(SchemaExport.java:133)
	at org.hibernate.impl.SessionFactoryImpl.<init>(SessionFactoryImpl.java:311)
	at org.hibernate.cfg.Configuration.buildSessionFactory(Configuration.java:1300)
	at store.util.HibernateUtil.<clinit>(HibernateUtil.java:8)
	at test.testStore.TestSet01_HibernateUtil.testFactory(TestSet01_HibernateUtil.java:35)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:585)
	at junit.framework.TestCase.runTest(TestCase.java:164)
	at junit.framework.TestCase.runBare(TestCase.java:130)
	at junit.framework.TestResult$1.protect(TestResult.java:106)
	at junit.framework.TestResult.runProtected(TestResult.java:124)
	at junit.framework.TestResult.run(TestResult.java:109)
	at junit.framework.TestCase.run(TestCase.java:120)
	at junit.framework.TestSuite.runTest(TestSuite.java:230)
	at junit.framework.TestSuite.run(TestSuite.java:225)
	at org.eclipse.jdt.internal.junit.runner.junit3.JUnit3TestReference.run(JUnit3TestReference.java:130)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:460)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:673)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:386)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:196)
01-16 11:34:38 jdbc[2]: SQLException
org.h2.jdbc.JdbcSQLException: Constraint FKD4B22306EEFD55EC not found [90057-69]
	at org.h2.message.Message.getSQLException(Message.java:91)
	at org.h2.message.Message.getSQLException(Message.java:95)
	at org.h2.message.Message.getSQLException(Message.java:73)
	at org.h2.schema.Schema.getConstraint(Schema.java:260)
	at org.h2.command.ddl.AlterTableDropConstraint.update(AlterTableDropConstraint.java:33)
	at org.h2.command.CommandContainer.update(CommandContainer.java:69)
	at org.h2.command.Command.executeUpdate(Command.java:197)
	at org.h2.jdbc.JdbcStatement.executeUpdate(JdbcStatement.java:108)
	at org.hibernate.tool.hbm2ddl.SchemaExport.execute(SchemaExport.java:308)
	at org.hibernate.tool.hbm2ddl.SchemaExport.drop(SchemaExport.java:284)
	at org.hibernate.tool.hbm2ddl.SchemaExport.execute(SchemaExport.java:186)
	at org.hibernate.tool.hbm2ddl.SchemaExport.create(SchemaExport.java:133)
	at org.hibernate.impl.SessionFactoryImpl.<init>(SessionFactoryImpl.java:311)
	at org.hibernate.cfg.Configuration.buildSessionFactory(Configuration.java:1300)
	at store.util.HibernateUtil.<clinit>(HibernateUtil.java:8)
	at store.TuttiCondomini.recuperaCondomini(TuttiCondomini.java:39)
	at store.TuttiCondomini.inizializza(TuttiCondomini.java:34)
	at test.testStore.TestSet03_TuttiCondomini.testCONDOMINI_Inserimento(TestSet03_TuttiCondomini.java:39)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:585)
	at junit.framework.TestCase.runTest(TestCase.java:164)
	at junit.framework.TestCase.runBare(TestCase.java:130)
	at junit.framework.TestResult$1.protect(TestResult.java:106)
	at junit.framework.TestResult.runProtected(TestResult.java:124)
	at junit.framework.TestResult.run(TestResult.java:109)
	at junit.framework.TestCase.run(TestCase.java:120)
	at junit.framework.TestSuite.runTest(TestSuite.java:230)
	at junit.framework.TestSuite.run(TestSuite.java:225)
	at org.eclipse.jdt.internal.junit.runner.junit3.JUnit3TestReference.run(JUnit3TestReference.java:130)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:460)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:673)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:386)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:196)
01-16 12:51:15 database: opening /home/bruno/workspace/AmICo/DB/DataBase4Amico
org.h2.jdbc.JdbcSQLException: Database may be already in use: Locked by another process. Possible solutions: close all other connection(s); use the server mode [90020-69]
	at org.h2.message.Message.getSQLException(Message.java:91)
	at org.h2.message.Message.getSQLException(Message.java:95)
	at org.h2.message.Message.getSQLException(Message.java:73)
	at org.h2.store.FileLock.error(FileLock.java:316)
	at org.h2.store.FileLock.lockFile(FileLock.java:178)
	at org.h2.store.FileLock.lock(FileLock.java:74)
	at org.h2.engine.Database.open(Database.java:467)
	at org.h2.engine.Database.<init>(Database.java:203)
	at org.h2.engine.Engine.openSession(Engine.java:55)
	at org.h2.engine.Engine.getSession(Engine.java:104)
	at org.h2.engine.Session.createSession(Session.java:203)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:976)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:957)
	at org.h2.Driver.connect(Driver.java:57)
	at java.sql.DriverManager.getConnection(DriverManager.java:525)
	at java.sql.DriverManager.getConnection(DriverManager.java:140)
	at org.hibernate.connection.DriverManagerConnectionProvider.getConnection(DriverManagerConnectionProvider.java:110)
	at org.hibernate.cfg.SettingsFactory.buildSettings(SettingsFactory.java:84)
	at org.hibernate.cfg.Configuration.buildSettings(Configuration.java:2073)
	at org.hibernate.cfg.Configuration.buildSessionFactory(Configuration.java:1298)
	at store.util.HibernateUtil.<clinit>(HibernateUtil.java:8)
	at store.TuttiCondomini.recuperaCondomini(TuttiCondomini.java:39)
	at store.TuttiCondomini.inizializza(TuttiCondomini.java:34)
	at test.testStore.TestSet03_TuttiCondomini.testCONDOMINI_Inserimento(TestSet03_TuttiCondomini.java:39)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:585)
	at junit.framework.TestCase.runTest(TestCase.java:164)
	at junit.framework.TestCase.runBare(TestCase.java:130)
	at junit.framework.TestResult$1.protect(TestResult.java:106)
	at junit.framework.TestResult.runProtected(TestResult.java:124)
	at junit.framework.TestResult.run(TestResult.java:109)
	at junit.framework.TestCase.run(TestCase.java:120)
	at junit.framework.TestSuite.runTest(TestSuite.java:230)
	at junit.framework.TestSuite.run(TestSuite.java:225)
	at org.eclipse.jdt.internal.junit.runner.junit3.JUnit3TestReference.run(JUnit3TestReference.java:130)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:460)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:673)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:386)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:196)
01-16 12:51:18 database: opening /home/bruno/workspace/AmICo/DB/DataBase4Amico
org.h2.jdbc.JdbcSQLException: Database may be already in use: Locked by another process. Possible solutions: close all other connection(s); use the server mode [90020-69]
	at org.h2.message.Message.getSQLException(Message.java:91)
	at org.h2.message.Message.getSQLException(Message.java:95)
	at org.h2.message.Message.getSQLException(Message.java:73)
	at org.h2.store.FileLock.error(FileLock.java:316)
	at org.h2.store.FileLock.lockFile(FileLock.java:178)
	at org.h2.store.FileLock.lock(FileLock.java:74)
	at org.h2.engine.Database.open(Database.java:467)
	at org.h2.engine.Database.<init>(Database.java:203)
	at org.h2.engine.Engine.openSession(Engine.java:55)
	at org.h2.engine.Engine.getSession(Engine.java:104)
	at org.h2.engine.Session.createSession(Session.java:203)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:976)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:957)
	at org.h2.Driver.connect(Driver.java:57)
	at java.sql.DriverManager.getConnection(DriverManager.java:525)
	at java.sql.DriverManager.getConnection(DriverManager.java:140)
	at org.hibernate.connection.DriverManagerConnectionProvider.getConnection(DriverManagerConnectionProvider.java:110)
	at org.hibernate.tool.hbm2ddl.SuppliedConnectionProviderConnectionHelper.prepare(SuppliedConnectionProviderConnectionHelper.java:27)
	at org.hibernate.tool.hbm2ddl.SchemaExport.execute(SchemaExport.java:180)
	at org.hibernate.tool.hbm2ddl.SchemaExport.create(SchemaExport.java:133)
	at org.hibernate.impl.SessionFactoryImpl.<init>(SessionFactoryImpl.java:311)
	at org.hibernate.cfg.Configuration.buildSessionFactory(Configuration.java:1300)
	at store.util.HibernateUtil.<clinit>(HibernateUtil.java:8)
	at store.TuttiCondomini.recuperaCondomini(TuttiCondomini.java:39)
	at store.TuttiCondomini.inizializza(TuttiCondomini.java:34)
	at test.testStore.TestSet03_TuttiCondomini.testCONDOMINI_Inserimento(TestSet03_TuttiCondomini.java:39)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:585)
	at junit.framework.TestCase.runTest(TestCase.java:164)
	at junit.framework.TestCase.runBare(TestCase.java:130)
	at junit.framework.TestResult$1.protect(TestResult.java:106)
	at junit.framework.TestResult.runProtected(TestResult.java:124)
	at junit.framework.TestResult.run(TestResult.java:109)
	at junit.framework.TestCase.run(TestCase.java:120)
	at junit.framework.TestSuite.runTest(TestSuite.java:230)
	at junit.framework.TestSuite.run(TestSuite.java:225)
	at org.eclipse.jdt.internal.junit.runner.junit3.JUnit3TestReference.run(JUnit3TestReference.java:130)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:460)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:673)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:386)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:196)
01-16 12:51:20 database: opening /home/bruno/workspace/AmICo/DB/DataBase4Amico
org.h2.jdbc.JdbcSQLException: Database may be already in use: Locked by another process. Possible solutions: close all other connection(s); use the server mode [90020-69]
	at org.h2.message.Message.getSQLException(Message.java:91)
	at org.h2.message.Message.getSQLException(Message.java:95)
	at org.h2.message.Message.getSQLException(Message.java:73)
	at org.h2.store.FileLock.error(FileLock.java:316)
	at org.h2.store.FileLock.lockFile(FileLock.java:178)
	at org.h2.store.FileLock.lock(FileLock.java:74)
	at org.h2.engine.Database.open(Database.java:467)
	at org.h2.engine.Database.<init>(Database.java:203)
	at org.h2.engine.Engine.openSession(Engine.java:55)
	at org.h2.engine.Engine.getSession(Engine.java:104)
	at org.h2.engine.Session.createSession(Session.java:203)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:976)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:957)
	at org.h2.Driver.connect(Driver.java:57)
	at java.sql.DriverManager.getConnection(DriverManager.java:525)
	at java.sql.DriverManager.getConnection(DriverManager.java:140)
	at org.hibernate.connection.DriverManagerConnectionProvider.getConnection(DriverManagerConnectionProvider.java:110)
	at org.hibernate.jdbc.ConnectionManager.openConnection(ConnectionManager.java:423)
	at org.hibernate.jdbc.ConnectionManager.getConnection(ConnectionManager.java:144)
	at org.hibernate.jdbc.JDBCContext.connection(JDBCContext.java:119)
	at org.hibernate.transaction.JDBCTransaction.begin(JDBCTransaction.java:57)
	at org.hibernate.impl.SessionImpl.beginTransaction(SessionImpl.java:1326)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:585)
	at org.hibernate.context.ThreadLocalSessionContext$TransactionProtectionWrapper.invoke(ThreadLocalSessionContext.java:301)
	at $Proxy0.beginTransaction(Unknown Source)
	at store.TuttiCondomini.recuperaCondomini(TuttiCondomini.java:40)
	at store.TuttiCondomini.inizializza(TuttiCondomini.java:34)
	at test.testStore.TestSet03_TuttiCondomini.testCONDOMINI_Inserimento(TestSet03_TuttiCondomini.java:39)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:585)
	at junit.framework.TestCase.runTest(TestCase.java:164)
	at junit.framework.TestCase.runBare(TestCase.java:130)
	at junit.framework.TestResult$1.protect(TestResult.java:106)
	at junit.framework.TestResult.runProtected(TestResult.java:124)
	at junit.framework.TestResult.run(TestResult.java:109)
	at junit.framework.TestCase.run(TestCase.java:120)
	at junit.framework.TestSuite.runTest(TestSuite.java:230)
	at junit.framework.TestSuite.run(TestSuite.java:225)
	at org.eclipse.jdt.internal.junit.runner.junit3.JUnit3TestReference.run(JUnit3TestReference.java:130)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:460)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:673)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:386)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:196)
01-16 12:51:22 database: opening /home/bruno/workspace/AmICo/DB/DataBase4Amico
org.h2.jdbc.JdbcSQLException: Database may be already in use: Locked by another process. Possible solutions: close all other connection(s); use the server mode [90020-69]
	at org.h2.message.Message.getSQLException(Message.java:91)
	at org.h2.message.Message.getSQLException(Message.java:95)
	at org.h2.message.Message.getSQLException(Message.java:73)
	at org.h2.store.FileLock.error(FileLock.java:316)
	at org.h2.store.FileLock.lockFile(FileLock.java:178)
	at org.h2.store.FileLock.lock(FileLock.java:74)
	at org.h2.engine.Database.open(Database.java:467)
	at org.h2.engine.Database.<init>(Database.java:203)
	at org.h2.engine.Engine.openSession(Engine.java:55)
	at org.h2.engine.Engine.getSession(Engine.java:104)
	at org.h2.engine.Session.createSession(Session.java:203)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:976)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:957)
	at org.h2.Driver.connect(Driver.java:57)
	at java.sql.DriverManager.getConnection(DriverManager.java:525)
	at java.sql.DriverManager.getConnection(DriverManager.java:140)
	at org.hibernate.connection.DriverManagerConnectionProvider.getConnection(DriverManagerConnectionProvider.java:110)
	at org.hibernate.jdbc.ConnectionManager.openConnection(ConnectionManager.java:423)
	at org.hibernate.jdbc.ConnectionManager.getConnection(ConnectionManager.java:144)
	at org.hibernate.jdbc.JDBCContext.connection(JDBCContext.java:119)
	at org.hibernate.transaction.JDBCTransaction.begin(JDBCTransaction.java:57)
	at org.hibernate.impl.SessionImpl.beginTransaction(SessionImpl.java:1326)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:585)
	at org.hibernate.context.ThreadLocalSessionContext$TransactionProtectionWrapper.invoke(ThreadLocalSessionContext.java:301)
	at $Proxy0.beginTransaction(Unknown Source)
	at store.TuttiCondomini.recuperaCondomini(TuttiCondomini.java:40)
	at store.TuttiCondomini.inizializza(TuttiCondomini.java:34)
	at test.testStore.TestSet03_TuttiCondomini.testCONDOMINI_recupero(TestSet03_TuttiCondomini.java:57)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:585)
	at junit.framework.TestCase.runTest(TestCase.java:164)
	at junit.framework.TestCase.runBare(TestCase.java:130)
	at junit.framework.TestResult$1.protect(TestResult.java:106)
	at junit.framework.TestResult.runProtected(TestResult.java:124)
	at junit.framework.TestResult.run(TestResult.java:109)
	at junit.framework.TestCase.run(TestCase.java:120)
	at junit.framework.TestSuite.runTest(TestSuite.java:230)
	at junit.framework.TestSuite.run(TestSuite.java:225)
	at org.eclipse.jdt.internal.junit.runner.junit3.JUnit3TestReference.run(JUnit3TestReference.java:130)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:460)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:673)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:386)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:196)
01-16 12:51:24 database: opening /home/bruno/workspace/AmICo/DB/DataBase4Amico
org.h2.jdbc.JdbcSQLException: Database may be already in use: Locked by another process. Possible solutions: close all other connection(s); use the server mode [90020-69]
	at org.h2.message.Message.getSQLException(Message.java:91)
	at org.h2.message.Message.getSQLException(Message.java:95)
	at org.h2.message.Message.getSQLException(Message.java:73)
	at org.h2.store.FileLock.error(FileLock.java:316)
	at org.h2.store.FileLock.lockFile(FileLock.java:178)
	at org.h2.store.FileLock.lock(FileLock.java:74)
	at org.h2.engine.Database.open(Database.java:467)
	at org.h2.engine.Database.<init>(Database.java:203)
	at org.h2.engine.Engine.openSession(Engine.java:55)
	at org.h2.engine.Engine.getSession(Engine.java:104)
	at org.h2.engine.Session.createSession(Session.java:203)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:976)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:957)
	at org.h2.Driver.connect(Driver.java:57)
	at java.sql.DriverManager.getConnection(DriverManager.java:525)
	at java.sql.DriverManager.getConnection(DriverManager.java:140)
	at org.hibernate.connection.DriverManagerConnectionProvider.getConnection(DriverManagerConnectionProvider.java:110)
	at org.hibernate.jdbc.ConnectionManager.openConnection(ConnectionManager.java:423)
	at org.hibernate.jdbc.ConnectionManager.getConnection(ConnectionManager.java:144)
	at org.hibernate.jdbc.JDBCContext.connection(JDBCContext.java:119)
	at org.hibernate.transaction.JDBCTransaction.begin(JDBCTransaction.java:57)
	at org.hibernate.impl.SessionImpl.beginTransaction(SessionImpl.java:1326)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:585)
	at org.hibernate.context.ThreadLocalSessionContext$TransactionProtectionWrapper.invoke(ThreadLocalSessionContext.java:301)
	at $Proxy0.beginTransaction(Unknown Source)
	at store.TuttiCondomini.recuperaCondomini(TuttiCondomini.java:40)
	at store.TuttiCondomini.inizializza(TuttiCondomini.java:34)
	at test.testStore.TestSet03_TuttiCondomini.testCONDOMINI_modifica(TestSet03_TuttiCondomini.java:76)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:585)
	at junit.framework.TestCase.runTest(TestCase.java:164)
	at junit.framework.TestCase.runBare(TestCase.java:130)
	at junit.framework.TestResult$1.protect(TestResult.java:106)
	at junit.framework.TestResult.runProtected(TestResult.java:124)
	at junit.framework.TestResult.run(TestResult.java:109)
	at junit.framework.TestCase.run(TestCase.java:120)
	at junit.framework.TestSuite.runTest(TestSuite.java:230)
	at junit.framework.TestSuite.run(TestSuite.java:225)
	at org.eclipse.jdt.internal.junit.runner.junit3.JUnit3TestReference.run(JUnit3TestReference.java:130)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:460)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:673)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:386)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:196)
01-16 12:51:26 database: opening /home/bruno/workspace/AmICo/DB/DataBase4Amico
org.h2.jdbc.JdbcSQLException: Database may be already in use: Locked by another process. Possible solutions: close all other connection(s); use the server mode [90020-69]
	at org.h2.message.Message.getSQLException(Message.java:91)
	at org.h2.message.Message.getSQLException(Message.java:95)
	at org.h2.message.Message.getSQLException(Message.java:73)
	at org.h2.store.FileLock.error(FileLock.java:316)
	at org.h2.store.FileLock.lockFile(FileLock.java:178)
	at org.h2.store.FileLock.lock(FileLock.java:74)
	at org.h2.engine.Database.open(Database.java:467)
	at org.h2.engine.Database.<init>(Database.java:203)
	at org.h2.engine.Engine.openSession(Engine.java:55)
	at org.h2.engine.Engine.getSession(Engine.java:104)
	at org.h2.engine.Session.createSession(Session.java:203)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:976)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:957)
	at org.h2.Driver.connect(Driver.java:57)
	at java.sql.DriverManager.getConnection(DriverManager.java:525)
	at java.sql.DriverManager.getConnection(DriverManager.java:140)
	at org.hibernate.connection.DriverManagerConnectionProvider.getConnection(DriverManagerConnectionProvider.java:110)
	at org.hibernate.jdbc.ConnectionManager.openConnection(ConnectionManager.java:423)
	at org.hibernate.jdbc.ConnectionManager.getConnection(ConnectionManager.java:144)
	at org.hibernate.jdbc.JDBCContext.connection(JDBCContext.java:119)
	at org.hibernate.transaction.JDBCTransaction.begin(JDBCTransaction.java:57)
	at org.hibernate.impl.SessionImpl.beginTransaction(SessionImpl.java:1326)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:585)
	at org.hibernate.context.ThreadLocalSessionContext$TransactionProtectionWrapper.invoke(ThreadLocalSessionContext.java:301)
	at $Proxy0.beginTransaction(Unknown Source)
	at store.TuttiCondomini.recuperaCondomini(TuttiCondomini.java:40)
	at store.TuttiCondomini.inizializza(TuttiCondomini.java:34)
	at test.testStore.TestSet03_TuttiCondomini.testCONDOMINI_inserireUnitaImmobiliare(TestSet03_TuttiCondomini.java:94)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:585)
	at junit.framework.TestCase.runTest(TestCase.java:164)
	at junit.framework.TestCase.runBare(TestCase.java:130)
	at junit.framework.TestResult$1.protect(TestResult.java:106)
	at junit.framework.TestResult.runProtected(TestResult.java:124)
	at junit.framework.TestResult.run(TestResult.java:109)
	at junit.framework.TestCase.run(TestCase.java:120)
	at junit.framework.TestSuite.runTest(TestSuite.java:230)
	at junit.framework.TestSuite.run(TestSuite.java:225)
	at org.eclipse.jdt.internal.junit.runner.junit3.JUnit3TestReference.run(JUnit3TestReference.java:130)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:460)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:673)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:386)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:196)
01-16 12:51:37 database: opening /home/bruno/workspace/AmICo/DB/DataBase4Amico
org.h2.jdbc.JdbcSQLException: Database may be already in use: Locked by another process. Possible solutions: close all other connection(s); use the server mode [90020-69]
	at org.h2.message.Message.getSQLException(Message.java:91)
	at org.h2.message.Message.getSQLException(Message.java:95)
	at org.h2.message.Message.getSQLException(Message.java:73)
	at org.h2.store.FileLock.error(FileLock.java:316)
	at org.h2.store.FileLock.lockFile(FileLock.java:178)
	at org.h2.store.FileLock.lock(FileLock.java:74)
	at org.h2.engine.Database.open(Database.java:467)
	at org.h2.engine.Database.<init>(Database.java:203)
	at org.h2.engine.Engine.openSession(Engine.java:55)
	at org.h2.engine.Engine.getSession(Engine.java:104)
	at org.h2.engine.Session.createSession(Session.java:203)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:976)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:957)
	at org.h2.Driver.connect(Driver.java:57)
	at java.sql.DriverManager.getConnection(DriverManager.java:525)
	at java.sql.DriverManager.getConnection(DriverManager.java:140)
	at org.hibernate.connection.DriverManagerConnectionProvider.getConnection(DriverManagerConnectionProvider.java:110)
	at org.hibernate.cfg.SettingsFactory.buildSettings(SettingsFactory.java:84)
	at org.hibernate.cfg.Configuration.buildSettings(Configuration.java:2073)
	at org.hibernate.cfg.Configuration.buildSessionFactory(Configuration.java:1298)
	at store.util.HibernateUtil.<clinit>(HibernateUtil.java:8)
	at store.TuttiCondomini.recuperaCondomini(TuttiCondomini.java:39)
	at store.TuttiCondomini.inizializza(TuttiCondomini.java:34)
	at test.testStore.TestSet03_TuttiCondomini.testCONDOMINI_Inserimento(TestSet03_TuttiCondomini.java:39)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:585)
	at junit.framework.TestCase.runTest(TestCase.java:164)
	at junit.framework.TestCase.runBare(TestCase.java:130)
	at junit.framework.TestResult$1.protect(TestResult.java:106)
	at junit.framework.TestResult.runProtected(TestResult.java:124)
	at junit.framework.TestResult.run(TestResult.java:109)
	at junit.framework.TestCase.run(TestCase.java:120)
	at junit.framework.TestSuite.runTest(TestSuite.java:230)
	at junit.framework.TestSuite.run(TestSuite.java:225)
	at org.eclipse.jdt.internal.junit.runner.junit3.JUnit3TestReference.run(JUnit3TestReference.java:130)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:460)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:673)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:386)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:196)
01-16 12:51:40 database: opening /home/bruno/workspace/AmICo/DB/DataBase4Amico
org.h2.jdbc.JdbcSQLException: Database may be already in use: Locked by another process. Possible solutions: close all other connection(s); use the server mode [90020-69]
	at org.h2.message.Message.getSQLException(Message.java:91)
	at org.h2.message.Message.getSQLException(Message.java:95)
	at org.h2.message.Message.getSQLException(Message.java:73)
	at org.h2.store.FileLock.error(FileLock.java:316)
	at org.h2.store.FileLock.lockFile(FileLock.java:178)
	at org.h2.store.FileLock.lock(FileLock.java:74)
	at org.h2.engine.Database.open(Database.java:467)
	at org.h2.engine.Database.<init>(Database.java:203)
	at org.h2.engine.Engine.openSession(Engine.java:55)
	at org.h2.engine.Engine.getSession(Engine.java:104)
	at org.h2.engine.Session.createSession(Session.java:203)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:976)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:957)
	at org.h2.Driver.connect(Driver.java:57)
	at java.sql.DriverManager.getConnection(DriverManager.java:525)
	at java.sql.DriverManager.getConnection(DriverManager.java:140)
	at org.hibernate.connection.DriverManagerConnectionProvider.getConnection(DriverManagerConnectionProvider.java:110)
	at org.hibernate.tool.hbm2ddl.SuppliedConnectionProviderConnectionHelper.prepare(SuppliedConnectionProviderConnectionHelper.java:27)
	at org.hibernate.tool.hbm2ddl.SchemaExport.execute(SchemaExport.java:180)
	at org.hibernate.tool.hbm2ddl.SchemaExport.create(SchemaExport.java:133)
	at org.hibernate.impl.SessionFactoryImpl.<init>(SessionFactoryImpl.java:311)
	at org.hibernate.cfg.Configuration.buildSessionFactory(Configuration.java:1300)
	at store.util.HibernateUtil.<clinit>(HibernateUtil.java:8)
	at store.TuttiCondomini.recuperaCondomini(TuttiCondomini.java:39)
	at store.TuttiCondomini.inizializza(TuttiCondomini.java:34)
	at test.testStore.TestSet03_TuttiCondomini.testCONDOMINI_Inserimento(TestSet03_TuttiCondomini.java:39)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:585)
	at junit.framework.TestCase.runTest(TestCase.java:164)
	at junit.framework.TestCase.runBare(TestCase.java:130)
	at junit.framework.TestResult$1.protect(TestResult.java:106)
	at junit.framework.TestResult.runProtected(TestResult.java:124)
	at junit.framework.TestResult.run(TestResult.java:109)
	at junit.framework.TestCase.run(TestCase.java:120)
	at junit.framework.TestSuite.runTest(TestSuite.java:230)
	at junit.framework.TestSuite.run(TestSuite.java:225)
	at org.eclipse.jdt.internal.junit.runner.junit3.JUnit3TestReference.run(JUnit3TestReference.java:130)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:460)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:673)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:386)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:196)
01-16 12:51:43 database: opening /home/bruno/workspace/AmICo/DB/DataBase4Amico
org.h2.jdbc.JdbcSQLException: Database may be already in use: Locked by another process. Possible solutions: close all other connection(s); use the server mode [90020-69]
	at org.h2.message.Message.getSQLException(Message.java:91)
	at org.h2.message.Message.getSQLException(Message.java:95)
	at org.h2.message.Message.getSQLException(Message.java:73)
	at org.h2.store.FileLock.error(FileLock.java:316)
	at org.h2.store.FileLock.lockFile(FileLock.java:178)
	at org.h2.store.FileLock.lock(FileLock.java:74)
	at org.h2.engine.Database.open(Database.java:467)
	at org.h2.engine.Database.<init>(Database.java:203)
	at org.h2.engine.Engine.openSession(Engine.java:55)
	at org.h2.engine.Engine.getSession(Engine.java:104)
	at org.h2.engine.Session.createSession(Session.java:203)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:976)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:957)
	at org.h2.Driver.connect(Driver.java:57)
	at java.sql.DriverManager.getConnection(DriverManager.java:525)
	at java.sql.DriverManager.getConnection(DriverManager.java:140)
	at org.hibernate.connection.DriverManagerConnectionProvider.getConnection(DriverManagerConnectionProvider.java:110)
	at org.hibernate.jdbc.ConnectionManager.openConnection(ConnectionManager.java:423)
	at org.hibernate.jdbc.ConnectionManager.getConnection(ConnectionManager.java:144)
	at org.hibernate.jdbc.JDBCContext.connection(JDBCContext.java:119)
	at org.hibernate.transaction.JDBCTransaction.begin(JDBCTransaction.java:57)
	at org.hibernate.impl.SessionImpl.beginTransaction(SessionImpl.java:1326)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:585)
	at org.hibernate.context.ThreadLocalSessionContext$TransactionProtectionWrapper.invoke(ThreadLocalSessionContext.java:301)
	at $Proxy0.beginTransaction(Unknown Source)
	at store.TuttiCondomini.recuperaCondomini(TuttiCondomini.java:40)
	at store.TuttiCondomini.inizializza(TuttiCondomini.java:34)
	at test.testStore.TestSet03_TuttiCondomini.testCONDOMINI_Inserimento(TestSet03_TuttiCondomini.java:39)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:585)
	at junit.framework.TestCase.runTest(TestCase.java:164)
	at junit.framework.TestCase.runBare(TestCase.java:130)
	at junit.framework.TestResult$1.protect(TestResult.java:106)
	at junit.framework.TestResult.runProtected(TestResult.java:124)
	at junit.framework.TestResult.run(TestResult.java:109)
	at junit.framework.TestCase.run(TestCase.java:120)
	at junit.framework.TestSuite.runTest(TestSuite.java:230)
	at junit.framework.TestSuite.run(TestSuite.java:225)
	at org.eclipse.jdt.internal.junit.runner.junit3.JUnit3TestReference.run(JUnit3TestReference.java:130)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:460)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:673)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:386)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:196)
01-16 12:51:45 database: opening /home/bruno/workspace/AmICo/DB/DataBase4Amico
org.h2.jdbc.JdbcSQLException: Database may be already in use: Locked by another process. Possible solutions: close all other connection(s); use the server mode [90020-69]
	at org.h2.message.Message.getSQLException(Message.java:91)
	at org.h2.message.Message.getSQLException(Message.java:95)
	at org.h2.message.Message.getSQLException(Message.java:73)
	at org.h2.store.FileLock.error(FileLock.java:316)
	at org.h2.store.FileLock.lockFile(FileLock.java:178)
	at org.h2.store.FileLock.lock(FileLock.java:74)
	at org.h2.engine.Database.open(Database.java:467)
	at org.h2.engine.Database.<init>(Database.java:203)
	at org.h2.engine.Engine.openSession(Engine.java:55)
	at org.h2.engine.Engine.getSession(Engine.java:104)
	at org.h2.engine.Session.createSession(Session.java:203)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:976)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:957)
	at org.h2.Driver.connect(Driver.java:57)
	at java.sql.DriverManager.getConnection(DriverManager.java:525)
	at java.sql.DriverManager.getConnection(DriverManager.java:140)
	at org.hibernate.connection.DriverManagerConnectionProvider.getConnection(DriverManagerConnectionProvider.java:110)
	at org.hibernate.jdbc.ConnectionManager.openConnection(ConnectionManager.java:423)
	at org.hibernate.jdbc.ConnectionManager.getConnection(ConnectionManager.java:144)
	at org.hibernate.jdbc.JDBCContext.connection(JDBCContext.java:119)
	at org.hibernate.transaction.JDBCTransaction.begin(JDBCTransaction.java:57)
	at org.hibernate.impl.SessionImpl.beginTransaction(SessionImpl.java:1326)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:585)
	at org.hibernate.context.ThreadLocalSessionContext$TransactionProtectionWrapper.invoke(ThreadLocalSessionContext.java:301)
	at $Proxy0.beginTransaction(Unknown Source)
	at store.TuttiCondomini.recuperaCondomini(TuttiCondomini.java:40)
	at store.TuttiCondomini.inizializza(TuttiCondomini.java:34)
	at test.testStore.TestSet03_TuttiCondomini.testCONDOMINI_recupero(TestSet03_TuttiCondomini.java:57)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:585)
	at junit.framework.TestCase.runTest(TestCase.java:164)
	at junit.framework.TestCase.runBare(TestCase.java:130)
	at junit.framework.TestResult$1.protect(TestResult.java:106)
	at junit.framework.TestResult.runProtected(TestResult.java:124)
	at junit.framework.TestResult.run(TestResult.java:109)
	at junit.framework.TestCase.run(TestCase.java:120)
	at junit.framework.TestSuite.runTest(TestSuite.java:230)
	at junit.framework.TestSuite.run(TestSuite.java:225)
	at org.eclipse.jdt.internal.junit.runner.junit3.JUnit3TestReference.run(JUnit3TestReference.java:130)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:460)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:673)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:386)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:196)
01-16 14:04:43 database: opening /home/bruno/workspace/AmICo/DB/DataBase4Amico
org.h2.jdbc.JdbcSQLException: Database may be already in use: Locked by another process. Possible solutions: close all other connection(s); use the server mode [90020-69]
	at org.h2.message.Message.getSQLException(Message.java:91)
	at org.h2.message.Message.getSQLException(Message.java:95)
	at org.h2.message.Message.getSQLException(Message.java:73)
	at org.h2.store.FileLock.error(FileLock.java:316)
	at org.h2.store.FileLock.lockFile(FileLock.java:178)
	at org.h2.store.FileLock.lock(FileLock.java:74)
	at org.h2.engine.Database.open(Database.java:467)
	at org.h2.engine.Database.<init>(Database.java:203)
	at org.h2.engine.Engine.openSession(Engine.java:55)
	at org.h2.engine.Engine.getSession(Engine.java:104)
	at org.h2.engine.Session.createSession(Session.java:203)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:976)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:957)
	at org.h2.Driver.connect(Driver.java:57)
	at java.sql.DriverManager.getConnection(DriverManager.java:525)
	at java.sql.DriverManager.getConnection(DriverManager.java:140)
	at org.hibernate.connection.DriverManagerConnectionProvider.getConnection(DriverManagerConnectionProvider.java:110)
	at org.hibernate.cfg.SettingsFactory.buildSettings(SettingsFactory.java:84)
	at org.hibernate.cfg.Configuration.buildSettings(Configuration.java:2073)
	at org.hibernate.cfg.Configuration.buildSessionFactory(Configuration.java:1298)
	at store.util.HibernateUtil.<clinit>(HibernateUtil.java:8)
	at store.TuttiCondomini.recuperaCondomini(TuttiCondomini.java:39)
	at store.TuttiCondomini.inizializza(TuttiCondomini.java:34)
	at test.testStore.TestSet03_TuttiCondomini.testCONDOMINI_Inserimento(TestSet03_TuttiCondomini.java:39)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:585)
	at junit.framework.TestCase.runTest(TestCase.java:164)
	at junit.framework.TestCase.runBare(TestCase.java:130)
	at junit.framework.TestResult$1.protect(TestResult.java:106)
	at junit.framework.TestResult.runProtected(TestResult.java:124)
	at junit.framework.TestResult.run(TestResult.java:109)
	at junit.framework.TestCase.run(TestCase.java:120)
	at junit.framework.TestSuite.runTest(TestSuite.java:230)
	at junit.framework.TestSuite.run(TestSuite.java:225)
	at org.eclipse.jdt.internal.junit.runner.junit3.JUnit3TestReference.run(JUnit3TestReference.java:130)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:460)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:673)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:386)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:196)
01-16 14:04:46 database: opening /home/bruno/workspace/AmICo/DB/DataBase4Amico
org.h2.jdbc.JdbcSQLException: Database may be already in use: Locked by another process. Possible solutions: close all other connection(s); use the server mode [90020-69]
	at org.h2.message.Message.getSQLException(Message.java:91)
	at org.h2.message.Message.getSQLException(Message.java:95)
	at org.h2.message.Message.getSQLException(Message.java:73)
	at org.h2.store.FileLock.error(FileLock.java:316)
	at org.h2.store.FileLock.lockFile(FileLock.java:178)
	at org.h2.store.FileLock.lock(FileLock.java:74)
	at org.h2.engine.Database.open(Database.java:467)
	at org.h2.engine.Database.<init>(Database.java:203)
	at org.h2.engine.Engine.openSession(Engine.java:55)
	at org.h2.engine.Engine.getSession(Engine.java:104)
	at org.h2.engine.Session.createSession(Session.java:203)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:976)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:957)
	at org.h2.Driver.connect(Driver.java:57)
	at java.sql.DriverManager.getConnection(DriverManager.java:525)
	at java.sql.DriverManager.getConnection(DriverManager.java:140)
	at org.hibernate.connection.DriverManagerConnectionProvider.getConnection(DriverManagerConnectionProvider.java:110)
	at org.hibernate.tool.hbm2ddl.SuppliedConnectionProviderConnectionHelper.prepare(SuppliedConnectionProviderConnectionHelper.java:27)
	at org.hibernate.tool.hbm2ddl.SchemaExport.execute(SchemaExport.java:180)
	at org.hibernate.tool.hbm2ddl.SchemaExport.create(SchemaExport.java:133)
	at org.hibernate.impl.SessionFactoryImpl.<init>(SessionFactoryImpl.java:311)
	at org.hibernate.cfg.Configuration.buildSessionFactory(Configuration.java:1300)
	at store.util.HibernateUtil.<clinit>(HibernateUtil.java:8)
	at store.TuttiCondomini.recuperaCondomini(TuttiCondomini.java:39)
	at store.TuttiCondomini.inizializza(TuttiCondomini.java:34)
	at test.testStore.TestSet03_TuttiCondomini.testCONDOMINI_Inserimento(TestSet03_TuttiCondomini.java:39)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:585)
	at junit.framework.TestCase.runTest(TestCase.java:164)
	at junit.framework.TestCase.runBare(TestCase.java:130)
	at junit.framework.TestResult$1.protect(TestResult.java:106)
	at junit.framework.TestResult.runProtected(TestResult.java:124)
	at junit.framework.TestResult.run(TestResult.java:109)
	at junit.framework.TestCase.run(TestCase.java:120)
	at junit.framework.TestSuite.runTest(TestSuite.java:230)
	at junit.framework.TestSuite.run(TestSuite.java:225)
	at org.eclipse.jdt.internal.junit.runner.junit3.JUnit3TestReference.run(JUnit3TestReference.java:130)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:460)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:673)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:386)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:196)
01-16 14:04:49 database: opening /home/bruno/workspace/AmICo/DB/DataBase4Amico
org.h2.jdbc.JdbcSQLException: Database may be already in use: Locked by another process. Possible solutions: close all other connection(s); use the server mode [90020-69]
	at org.h2.message.Message.getSQLException(Message.java:91)
	at org.h2.message.Message.getSQLException(Message.java:95)
	at org.h2.message.Message.getSQLException(Message.java:73)
	at org.h2.store.FileLock.error(FileLock.java:316)
	at org.h2.store.FileLock.lockFile(FileLock.java:178)
	at org.h2.store.FileLock.lock(FileLock.java:74)
	at org.h2.engine.Database.open(Database.java:467)
	at org.h2.engine.Database.<init>(Database.java:203)
	at org.h2.engine.Engine.openSession(Engine.java:55)
	at org.h2.engine.Engine.getSession(Engine.java:104)
	at org.h2.engine.Session.createSession(Session.java:203)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:976)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:957)
	at org.h2.Driver.connect(Driver.java:57)
	at java.sql.DriverManager.getConnection(DriverManager.java:525)
	at java.sql.DriverManager.getConnection(DriverManager.java:140)
	at org.hibernate.connection.DriverManagerConnectionProvider.getConnection(DriverManagerConnectionProvider.java:110)
	at org.hibernate.jdbc.ConnectionManager.openConnection(ConnectionManager.java:423)
	at org.hibernate.jdbc.ConnectionManager.getConnection(ConnectionManager.java:144)
	at org.hibernate.jdbc.JDBCContext.connection(JDBCContext.java:119)
	at org.hibernate.transaction.JDBCTransaction.begin(JDBCTransaction.java:57)
	at org.hibernate.impl.SessionImpl.beginTransaction(SessionImpl.java:1326)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:585)
	at org.hibernate.context.ThreadLocalSessionContext$TransactionProtectionWrapper.invoke(ThreadLocalSessionContext.java:301)
	at $Proxy0.beginTransaction(Unknown Source)
	at store.TuttiCondomini.recuperaCondomini(TuttiCondomini.java:40)
	at store.TuttiCondomini.inizializza(TuttiCondomini.java:34)
	at test.testStore.TestSet03_TuttiCondomini.testCONDOMINI_Inserimento(TestSet03_TuttiCondomini.java:39)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:585)
	at junit.framework.TestCase.runTest(TestCase.java:164)
	at junit.framework.TestCase.runBare(TestCase.java:130)
	at junit.framework.TestResult$1.protect(TestResult.java:106)
	at junit.framework.TestResult.runProtected(TestResult.java:124)
	at junit.framework.TestResult.run(TestResult.java:109)
	at junit.framework.TestCase.run(TestCase.java:120)
	at junit.framework.TestSuite.runTest(TestSuite.java:230)
	at junit.framework.TestSuite.run(TestSuite.java:225)
	at org.eclipse.jdt.internal.junit.runner.junit3.JUnit3TestReference.run(JUnit3TestReference.java:130)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:460)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:673)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:386)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:196)
01-16 14:04:51 database: opening /home/bruno/workspace/AmICo/DB/DataBase4Amico
org.h2.jdbc.JdbcSQLException: Database may be already in use: Locked by another process. Possible solutions: close all other connection(s); use the server mode [90020-69]
	at org.h2.message.Message.getSQLException(Message.java:91)
	at org.h2.message.Message.getSQLException(Message.java:95)
	at org.h2.message.Message.getSQLException(Message.java:73)
	at org.h2.store.FileLock.error(FileLock.java:316)
	at org.h2.store.FileLock.lockFile(FileLock.java:178)
	at org.h2.store.FileLock.lock(FileLock.java:74)
	at org.h2.engine.Database.open(Database.java:467)
	at org.h2.engine.Database.<init>(Database.java:203)
	at org.h2.engine.Engine.openSession(Engine.java:55)
	at org.h2.engine.Engine.getSession(Engine.java:104)
	at org.h2.engine.Session.createSession(Session.java:203)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:976)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:957)
	at org.h2.Driver.connect(Driver.java:57)
	at java.sql.DriverManager.getConnection(DriverManager.java:525)
	at java.sql.DriverManager.getConnection(DriverManager.java:140)
	at org.hibernate.connection.DriverManagerConnectionProvider.getConnection(DriverManagerConnectionProvider.java:110)
	at org.hibernate.jdbc.ConnectionManager.openConnection(ConnectionManager.java:423)
	at org.hibernate.jdbc.ConnectionManager.getConnection(ConnectionManager.java:144)
	at org.hibernate.jdbc.JDBCContext.connection(JDBCContext.java:119)
	at org.hibernate.transaction.JDBCTransaction.begin(JDBCTransaction.java:57)
	at org.hibernate.impl.SessionImpl.beginTransaction(SessionImpl.java:1326)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:585)
	at org.hibernate.context.ThreadLocalSessionContext$TransactionProtectionWrapper.invoke(ThreadLocalSessionContext.java:301)
	at $Proxy0.beginTransaction(Unknown Source)
	at store.TuttiCondomini.recuperaCondomini(TuttiCondomini.java:40)
	at store.TuttiCondomini.inizializza(TuttiCondomini.java:34)
	at test.testStore.TestSet03_TuttiCondomini.testCONDOMINI_recupero(TestSet03_TuttiCondomini.java:57)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:585)
	at junit.framework.TestCase.runTest(TestCase.java:164)
	at junit.framework.TestCase.runBare(TestCase.java:130)
	at junit.framework.TestResult$1.protect(TestResult.java:106)
	at junit.framework.TestResult.runProtected(TestResult.java:124)
	at junit.framework.TestResult.run(TestResult.java:109)
	at junit.framework.TestCase.run(TestCase.java:120)
	at junit.framework.TestSuite.runTest(TestSuite.java:230)
	at junit.framework.TestSuite.run(TestSuite.java:225)
	at org.eclipse.jdt.internal.junit.runner.junit3.JUnit3TestReference.run(JUnit3TestReference.java:130)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:460)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:673)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:386)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:196)
