02-08 14:56:16 jdbc[2]: SQLException
org.h2.jdbc.JdbcSQLException: Table BILANCIO not found; SQL statement:
alter table BILANCIO drop constraint FK631D3797C56C4797 [42102-69]
	at org.h2.message.Message.getSQLException(Message.java:91)
	at org.h2.message.Message.getSQLException(Message.java:95)
	at org.h2.message.Message.getSQLException(Message.java:73)
	at org.h2.command.Parser.readTableOrView(Parser.java:4025)
	at org.h2.command.Parser.readTableOrView(Parser.java:4005)
	at org.h2.command.Parser.parseAlterTable(Parser.java:4050)
	at org.h2.command.Parser.parseAlter(Parser.java:3622)
	at org.h2.command.Parser.parsePrepared(Parser.java:302)
	at org.h2.command.Parser.parse(Parser.java:285)
	at org.h2.command.Parser.parse(Parser.java:257)
	at org.h2.command.Parser.prepareCommand(Parser.java:229)
	at org.h2.engine.Session.prepareLocal(Session.java:236)
	at org.h2.engine.Session.prepareCommand(Session.java:218)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1020)
	at org.h2.jdbc.JdbcStatement.executeUpdate(JdbcStatement.java:104)
	at org.hibernate.tool.hbm2ddl.SchemaExport.execute(SchemaExport.java:308)
	at org.hibernate.tool.hbm2ddl.SchemaExport.drop(SchemaExport.java:284)
	at org.hibernate.tool.hbm2ddl.SchemaExport.execute(SchemaExport.java:186)
	at org.hibernate.tool.hbm2ddl.SchemaExport.create(SchemaExport.java:133)
	at org.hibernate.impl.SessionFactoryImpl.<init>(SessionFactoryImpl.java:311)
	at org.hibernate.cfg.Configuration.buildSessionFactory(Configuration.java:1300)
	at store.util.HibernateUtil.<clinit>(HibernateUtil.java:8)
	at store.TuttiCondomini.recuperaCondomini(TuttiCondomini.java:34)
	at executor.GestoreCondomini.<init>(GestoreCondomini.java:60)
	at executor.GestoreCondomini.getInstance(GestoreCondomini.java:38)
	at executor.Avvio.inizializzaAmICo(Avvio.java:39)
	at executor.Avvio.main(Avvio.java:28)
02-08 14:56:16 jdbc[2]: SQLException
org.h2.jdbc.JdbcSQLException: Table CASSA not found; SQL statement:
alter table CASSA drop constraint FK3CEF4C3C56C4797 [42102-69]
	at org.h2.message.Message.getSQLException(Message.java:91)
	at org.h2.message.Message.getSQLException(Message.java:95)
	at org.h2.message.Message.getSQLException(Message.java:73)
	at org.h2.command.Parser.readTableOrView(Parser.java:4025)
	at org.h2.command.Parser.readTableOrView(Parser.java:4005)
	at org.h2.command.Parser.parseAlterTable(Parser.java:4050)
	at org.h2.command.Parser.parseAlter(Parser.java:3622)
	at org.h2.command.Parser.parsePrepared(Parser.java:302)
	at org.h2.command.Parser.parse(Parser.java:285)
	at org.h2.command.Parser.parse(Parser.java:257)
	at org.h2.command.Parser.prepareCommand(Parser.java:229)
	at org.h2.engine.Session.prepareLocal(Session.java:236)
	at org.h2.engine.Session.prepareCommand(Session.java:218)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1020)
	at org.h2.jdbc.JdbcStatement.executeUpdate(JdbcStatement.java:104)
	at org.hibernate.tool.hbm2ddl.SchemaExport.execute(SchemaExport.java:308)
	at org.hibernate.tool.hbm2ddl.SchemaExport.drop(SchemaExport.java:284)
	at org.hibernate.tool.hbm2ddl.SchemaExport.execute(SchemaExport.java:186)
	at org.hibernate.tool.hbm2ddl.SchemaExport.create(SchemaExport.java:133)
	at org.hibernate.impl.SessionFactoryImpl.<init>(SessionFactoryImpl.java:311)
	at org.hibernate.cfg.Configuration.buildSessionFactory(Configuration.java:1300)
	at store.util.HibernateUtil.<clinit>(HibernateUtil.java:8)
	at store.TuttiCondomini.recuperaCondomini(TuttiCondomini.java:34)
	at executor.GestoreCondomini.<init>(GestoreCondomini.java:60)
	at executor.GestoreCondomini.getInstance(GestoreCondomini.java:38)
	at executor.Avvio.inizializzaAmICo(Avvio.java:39)
	at executor.Avvio.main(Avvio.java:28)
02-08 14:56:16 jdbc[2]: SQLException
org.h2.jdbc.JdbcSQLException: Table MILLESIMI not found; SQL statement:
alter table MILLESIMI drop constraint FK71C8419B464E24E7 [42102-69]
	at org.h2.message.Message.getSQLException(Message.java:91)
	at org.h2.message.Message.getSQLException(Message.java:95)
	at org.h2.message.Message.getSQLException(Message.java:73)
	at org.h2.command.Parser.readTableOrView(Parser.java:4025)
	at org.h2.command.Parser.readTableOrView(Parser.java:4005)
	at org.h2.command.Parser.parseAlterTable(Parser.java:4050)
	at org.h2.command.Parser.parseAlter(Parser.java:3622)
	at org.h2.command.Parser.parsePrepared(Parser.java:302)
	at org.h2.command.Parser.parse(Parser.java:285)
	at org.h2.command.Parser.parse(Parser.java:257)
	at org.h2.command.Parser.prepareCommand(Parser.java:229)
	at org.h2.engine.Session.prepareLocal(Session.java:236)
	at org.h2.engine.Session.prepareCommand(Session.java:218)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1020)
	at org.h2.jdbc.JdbcStatement.executeUpdate(JdbcStatement.java:104)
	at org.hibernate.tool.hbm2ddl.SchemaExport.execute(SchemaExport.java:308)
	at org.hibernate.tool.hbm2ddl.SchemaExport.drop(SchemaExport.java:284)
	at org.hibernate.tool.hbm2ddl.SchemaExport.execute(SchemaExport.java:186)
	at org.hibernate.tool.hbm2ddl.SchemaExport.create(SchemaExport.java:133)
	at org.hibernate.impl.SessionFactoryImpl.<init>(SessionFactoryImpl.java:311)
	at org.hibernate.cfg.Configuration.buildSessionFactory(Configuration.java:1300)
	at store.util.HibernateUtil.<clinit>(HibernateUtil.java:8)
	at store.TuttiCondomini.recuperaCondomini(TuttiCondomini.java:34)
	at executor.GestoreCondomini.<init>(GestoreCondomini.java:60)
	at executor.GestoreCondomini.getInstance(GestoreCondomini.java:38)
	at executor.Avvio.inizializzaAmICo(Avvio.java:39)
	at executor.Avvio.main(Avvio.java:28)
02-08 14:56:16 jdbc[2]: SQLException
org.h2.jdbc.JdbcSQLException: Table MILLESIMI not found; SQL statement:
alter table MILLESIMI drop constraint FK71C8419B85B01BA1 [42102-69]
	at org.h2.message.Message.getSQLException(Message.java:91)
	at org.h2.message.Message.getSQLException(Message.java:95)
	at org.h2.message.Message.getSQLException(Message.java:73)
	at org.h2.command.Parser.readTableOrView(Parser.java:4025)
	at org.h2.command.Parser.readTableOrView(Parser.java:4005)
	at org.h2.command.Parser.parseAlterTable(Parser.java:4050)
	at org.h2.command.Parser.parseAlter(Parser.java:3622)
	at org.h2.command.Parser.parsePrepared(Parser.java:302)
	at org.h2.command.Parser.parse(Parser.java:285)
	at org.h2.command.Parser.parse(Parser.java:257)
	at org.h2.command.Parser.prepareCommand(Parser.java:229)
	at org.h2.engine.Session.prepareLocal(Session.java:236)
	at org.h2.engine.Session.prepareCommand(Session.java:218)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1020)
	at org.h2.jdbc.JdbcStatement.executeUpdate(JdbcStatement.java:104)
	at org.hibernate.tool.hbm2ddl.SchemaExport.execute(SchemaExport.java:308)
	at org.hibernate.tool.hbm2ddl.SchemaExport.drop(SchemaExport.java:284)
	at org.hibernate.tool.hbm2ddl.SchemaExport.execute(SchemaExport.java:186)
	at org.hibernate.tool.hbm2ddl.SchemaExport.create(SchemaExport.java:133)
	at org.hibernate.impl.SessionFactoryImpl.<init>(SessionFactoryImpl.java:311)
	at org.hibernate.cfg.Configuration.buildSessionFactory(Configuration.java:1300)
	at store.util.HibernateUtil.<clinit>(HibernateUtil.java:8)
	at store.TuttiCondomini.recuperaCondomini(TuttiCondomini.java:34)
	at executor.GestoreCondomini.<init>(GestoreCondomini.java:60)
	at executor.GestoreCondomini.getInstance(GestoreCondomini.java:38)
	at executor.Avvio.inizializzaAmICo(Avvio.java:39)
	at executor.Avvio.main(Avvio.java:28)
02-08 14:56:16 jdbc[2]: SQLException
org.h2.jdbc.JdbcSQLException: Table MOVIMENTO_CASSA not found; SQL statement:
alter table MOVIMENTO_CASSA drop constraint FKE865F2C0C2467AFD [42102-69]
	at org.h2.message.Message.getSQLException(Message.java:91)
	at org.h2.message.Message.getSQLException(Message.java:95)
	at org.h2.message.Message.getSQLException(Message.java:73)
	at org.h2.command.Parser.readTableOrView(Parser.java:4025)
	at org.h2.command.Parser.readTableOrView(Parser.java:4005)
	at org.h2.command.Parser.parseAlterTable(Parser.java:4050)
	at org.h2.command.Parser.parseAlter(Parser.java:3622)
	at org.h2.command.Parser.parsePrepared(Parser.java:302)
	at org.h2.command.Parser.parse(Parser.java:285)
	at org.h2.command.Parser.parse(Parser.java:257)
	at org.h2.command.Parser.prepareCommand(Parser.java:229)
	at org.h2.engine.Session.prepareLocal(Session.java:236)
	at org.h2.engine.Session.prepareCommand(Session.java:218)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1020)
	at org.h2.jdbc.JdbcStatement.executeUpdate(JdbcStatement.java:104)
	at org.hibernate.tool.hbm2ddl.SchemaExport.execute(SchemaExport.java:308)
	at org.hibernate.tool.hbm2ddl.SchemaExport.drop(SchemaExport.java:284)
	at org.hibernate.tool.hbm2ddl.SchemaExport.execute(SchemaExport.java:186)
	at org.hibernate.tool.hbm2ddl.SchemaExport.create(SchemaExport.java:133)
	at org.hibernate.impl.SessionFactoryImpl.<init>(SessionFactoryImpl.java:311)
	at org.hibernate.cfg.Configuration.buildSessionFactory(Configuration.java:1300)
	at store.util.HibernateUtil.<clinit>(HibernateUtil.java:8)
	at store.TuttiCondomini.recuperaCondomini(TuttiCondomini.java:34)
	at executor.GestoreCondomini.<init>(GestoreCondomini.java:60)
	at executor.GestoreCondomini.getInstance(GestoreCondomini.java:38)
	at executor.Avvio.inizializzaAmICo(Avvio.java:39)
	at executor.Avvio.main(Avvio.java:28)
02-08 14:56:16 jdbc[2]: SQLException
org.h2.jdbc.JdbcSQLException: Table MOVIMENTO_CASSA not found; SQL statement:
alter table MOVIMENTO_CASSA drop constraint FKE865F2C0EC7432A8 [42102-69]
	at org.h2.message.Message.getSQLException(Message.java:91)
	at org.h2.message.Message.getSQLException(Message.java:95)
	at org.h2.message.Message.getSQLException(Message.java:73)
	at org.h2.command.Parser.readTableOrView(Parser.java:4025)
	at org.h2.command.Parser.readTableOrView(Parser.java:4005)
	at org.h2.command.Parser.parseAlterTable(Parser.java:4050)
	at org.h2.command.Parser.parseAlter(Parser.java:3622)
	at org.h2.command.Parser.parsePrepared(Parser.java:302)
	at org.h2.command.Parser.parse(Parser.java:285)
	at org.h2.command.Parser.parse(Parser.java:257)
	at org.h2.command.Parser.prepareCommand(Parser.java:229)
	at org.h2.engine.Session.prepareLocal(Session.java:236)
	at org.h2.engine.Session.prepareCommand(Session.java:218)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1020)
	at org.h2.jdbc.JdbcStatement.executeUpdate(JdbcStatement.java:104)
	at org.hibernate.tool.hbm2ddl.SchemaExport.execute(SchemaExport.java:308)
	at org.hibernate.tool.hbm2ddl.SchemaExport.drop(SchemaExport.java:284)
	at org.hibernate.tool.hbm2ddl.SchemaExport.execute(SchemaExport.java:186)
	at org.hibernate.tool.hbm2ddl.SchemaExport.create(SchemaExport.java:133)
	at org.hibernate.impl.SessionFactoryImpl.<init>(SessionFactoryImpl.java:311)
	at org.hibernate.cfg.Configuration.buildSessionFactory(Configuration.java:1300)
	at store.util.HibernateUtil.<clinit>(HibernateUtil.java:8)
	at store.TuttiCondomini.recuperaCondomini(TuttiCondomini.java:34)
	at executor.GestoreCondomini.<init>(GestoreCondomini.java:60)
	at executor.GestoreCondomini.getInstance(GestoreCondomini.java:38)
	at executor.Avvio.inizializzaAmICo(Avvio.java:39)
	at executor.Avvio.main(Avvio.java:28)
02-08 14:56:16 jdbc[2]: SQLException
org.h2.jdbc.JdbcSQLException: Table MOVIMENTO_CASSA not found; SQL statement:
alter table MOVIMENTO_CASSA drop constraint FKE865F2C0BE71F91 [42102-69]
	at org.h2.message.Message.getSQLException(Message.java:91)
	at org.h2.message.Message.getSQLException(Message.java:95)
	at org.h2.message.Message.getSQLException(Message.java:73)
	at org.h2.command.Parser.readTableOrView(Parser.java:4025)
	at org.h2.command.Parser.readTableOrView(Parser.java:4005)
	at org.h2.command.Parser.parseAlterTable(Parser.java:4050)
	at org.h2.command.Parser.parseAlter(Parser.java:3622)
	at org.h2.command.Parser.parsePrepared(Parser.java:302)
	at org.h2.command.Parser.parse(Parser.java:285)
	at org.h2.command.Parser.parse(Parser.java:257)
	at org.h2.command.Parser.prepareCommand(Parser.java:229)
	at org.h2.engine.Session.prepareLocal(Session.java:236)
	at org.h2.engine.Session.prepareCommand(Session.java:218)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1020)
	at org.h2.jdbc.JdbcStatement.executeUpdate(JdbcStatement.java:104)
	at org.hibernate.tool.hbm2ddl.SchemaExport.execute(SchemaExport.java:308)
	at org.hibernate.tool.hbm2ddl.SchemaExport.drop(SchemaExport.java:284)
	at org.hibernate.tool.hbm2ddl.SchemaExport.execute(SchemaExport.java:186)
	at org.hibernate.tool.hbm2ddl.SchemaExport.create(SchemaExport.java:133)
	at org.hibernate.impl.SessionFactoryImpl.<init>(SessionFactoryImpl.java:311)
	at org.hibernate.cfg.Configuration.buildSessionFactory(Configuration.java:1300)
	at store.util.HibernateUtil.<clinit>(HibernateUtil.java:8)
	at store.TuttiCondomini.recuperaCondomini(TuttiCondomini.java:34)
	at executor.GestoreCondomini.<init>(GestoreCondomini.java:60)
	at executor.GestoreCondomini.getInstance(GestoreCondomini.java:38)
	at executor.Avvio.inizializzaAmICo(Avvio.java:39)
	at executor.Avvio.main(Avvio.java:28)
02-08 14:56:16 jdbc[2]: SQLException
org.h2.jdbc.JdbcSQLException: Table PAGAMENTO not found; SQL statement:
alter table PAGAMENTO drop constraint FKD4B22306A1EC25D7 [42102-69]
	at org.h2.message.Message.getSQLException(Message.java:91)
	at org.h2.message.Message.getSQLException(Message.java:95)
	at org.h2.message.Message.getSQLException(Message.java:73)
	at org.h2.command.Parser.readTableOrView(Parser.java:4025)
	at org.h2.command.Parser.readTableOrView(Parser.java:4005)
	at org.h2.command.Parser.parseAlterTable(Parser.java:4050)
	at org.h2.command.Parser.parseAlter(Parser.java:3622)
	at org.h2.command.Parser.parsePrepared(Parser.java:302)
	at org.h2.command.Parser.parse(Parser.java:285)
	at org.h2.command.Parser.parse(Parser.java:257)
	at org.h2.command.Parser.prepareCommand(Parser.java:229)
	at org.h2.engine.Session.prepareLocal(Session.java:236)
	at org.h2.engine.Session.prepareCommand(Session.java:218)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1020)
	at org.h2.jdbc.JdbcStatement.executeUpdate(JdbcStatement.java:104)
	at org.hibernate.tool.hbm2ddl.SchemaExport.execute(SchemaExport.java:308)
	at org.hibernate.tool.hbm2ddl.SchemaExport.drop(SchemaExport.java:284)
	at org.hibernate.tool.hbm2ddl.SchemaExport.execute(SchemaExport.java:186)
	at org.hibernate.tool.hbm2ddl.SchemaExport.create(SchemaExport.java:133)
	at org.hibernate.impl.SessionFactoryImpl.<init>(SessionFactoryImpl.java:311)
	at org.hibernate.cfg.Configuration.buildSessionFactory(Configuration.java:1300)
	at store.util.HibernateUtil.<clinit>(HibernateUtil.java:8)
	at store.TuttiCondomini.recuperaCondomini(TuttiCondomini.java:34)
	at executor.GestoreCondomini.<init>(GestoreCondomini.java:60)
	at executor.GestoreCondomini.getInstance(GestoreCondomini.java:38)
	at executor.Avvio.inizializzaAmICo(Avvio.java:39)
	at executor.Avvio.main(Avvio.java:28)
02-08 14:56:16 jdbc[2]: SQLException
org.h2.jdbc.JdbcSQLException: Table PAGAMENTO not found; SQL statement:
alter table PAGAMENTO drop constraint FKD4B223066AA91D9D [42102-69]
	at org.h2.message.Message.getSQLException(Message.java:91)
	at org.h2.message.Message.getSQLException(Message.java:95)
	at org.h2.message.Message.getSQLException(Message.java:73)
	at org.h2.command.Parser.readTableOrView(Parser.java:4025)
	at org.h2.command.Parser.readTableOrView(Parser.java:4005)
	at org.h2.command.Parser.parseAlterTable(Parser.java:4050)
	at org.h2.command.Parser.parseAlter(Parser.java:3622)
	at org.h2.command.Parser.parsePrepared(Parser.java:302)
	at org.h2.command.Parser.parse(Parser.java:285)
	at org.h2.command.Parser.parse(Parser.java:257)
	at org.h2.command.Parser.prepareCommand(Parser.java:229)
	at org.h2.engine.Session.prepareLocal(Session.java:236)
	at org.h2.engine.Session.prepareCommand(Session.java:218)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1020)
	at org.h2.jdbc.JdbcStatement.executeUpdate(JdbcStatement.java:104)
	at org.hibernate.tool.hbm2ddl.SchemaExport.execute(SchemaExport.java:308)
	at org.hibernate.tool.hbm2ddl.SchemaExport.drop(SchemaExport.java:284)
	at org.hibernate.tool.hbm2ddl.SchemaExport.execute(SchemaExport.java:186)
	at org.hibernate.tool.hbm2ddl.SchemaExport.create(SchemaExport.java:133)
	at org.hibernate.impl.SessionFactoryImpl.<init>(SessionFactoryImpl.java:311)
	at org.hibernate.cfg.Configuration.buildSessionFactory(Configuration.java:1300)
	at store.util.HibernateUtil.<clinit>(HibernateUtil.java:8)
	at store.TuttiCondomini.recuperaCondomini(TuttiCondomini.java:34)
	at executor.GestoreCondomini.<init>(GestoreCondomini.java:60)
	at executor.GestoreCondomini.getInstance(GestoreCondomini.java:38)
	at executor.Avvio.inizializzaAmICo(Avvio.java:39)
	at executor.Avvio.main(Avvio.java:28)
02-08 14:56:16 jdbc[2]: SQLException
org.h2.jdbc.JdbcSQLException: Table PAGAMENTO not found; SQL statement:
alter table PAGAMENTO drop constraint FKD4B22306A2884757 [42102-69]
	at org.h2.message.Message.getSQLException(Message.java:91)
	at org.h2.message.Message.getSQLException(Message.java:95)
	at org.h2.message.Message.getSQLException(Message.java:73)
	at org.h2.command.Parser.readTableOrView(Parser.java:4025)
	at org.h2.command.Parser.readTableOrView(Parser.java:4005)
	at org.h2.command.Parser.parseAlterTable(Parser.java:4050)
	at org.h2.command.Parser.parseAlter(Parser.java:3622)
	at org.h2.command.Parser.parsePrepared(Parser.java:302)
	at org.h2.command.Parser.parse(Parser.java:285)
	at org.h2.command.Parser.parse(Parser.java:257)
	at org.h2.command.Parser.prepareCommand(Parser.java:229)
	at org.h2.engine.Session.prepareLocal(Session.java:236)
	at org.h2.engine.Session.prepareCommand(Session.java:218)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1020)
	at org.h2.jdbc.JdbcStatement.executeUpdate(JdbcStatement.java:104)
	at org.hibernate.tool.hbm2ddl.SchemaExport.execute(SchemaExport.java:308)
	at org.hibernate.tool.hbm2ddl.SchemaExport.drop(SchemaExport.java:284)
	at org.hibernate.tool.hbm2ddl.SchemaExport.execute(SchemaExport.java:186)
	at org.hibernate.tool.hbm2ddl.SchemaExport.create(SchemaExport.java:133)
	at org.hibernate.impl.SessionFactoryImpl.<init>(SessionFactoryImpl.java:311)
	at org.hibernate.cfg.Configuration.buildSessionFactory(Configuration.java:1300)
	at store.util.HibernateUtil.<clinit>(HibernateUtil.java:8)
	at store.TuttiCondomini.recuperaCondomini(TuttiCondomini.java:34)
	at executor.GestoreCondomini.<init>(GestoreCondomini.java:60)
	at executor.GestoreCondomini.getInstance(GestoreCondomini.java:38)
	at executor.Avvio.inizializzaAmICo(Avvio.java:39)
	at executor.Avvio.main(Avvio.java:28)
02-08 14:56:16 jdbc[2]: SQLException
org.h2.jdbc.JdbcSQLException: Table PAGAMENTO not found; SQL statement:
alter table PAGAMENTO drop constraint FKD4B22306D92D4FAA [42102-69]
	at org.h2.message.Message.getSQLException(Message.java:91)
	at org.h2.message.Message.getSQLException(Message.java:95)
	at org.h2.message.Message.getSQLException(Message.java:73)
	at org.h2.command.Parser.readTableOrView(Parser.java:4025)
	at org.h2.command.Parser.readTableOrView(Parser.java:4005)
	at org.h2.command.Parser.parseAlterTable(Parser.java:4050)
	at org.h2.command.Parser.parseAlter(Parser.java:3622)
	at org.h2.command.Parser.parsePrepared(Parser.java:302)
	at org.h2.command.Parser.parse(Parser.java:285)
	at org.h2.command.Parser.parse(Parser.java:257)
	at org.h2.command.Parser.prepareCommand(Parser.java:229)
	at org.h2.engine.Session.prepareLocal(Session.java:236)
	at org.h2.engine.Session.prepareCommand(Session.java:218)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1020)
	at org.h2.jdbc.JdbcStatement.executeUpdate(JdbcStatement.java:104)
	at org.hibernate.tool.hbm2ddl.SchemaExport.execute(SchemaExport.java:308)
	at org.hibernate.tool.hbm2ddl.SchemaExport.drop(SchemaExport.java:284)
	at org.hibernate.tool.hbm2ddl.SchemaExport.execute(SchemaExport.java:186)
	at org.hibernate.tool.hbm2ddl.SchemaExport.create(SchemaExport.java:133)
	at org.hibernate.impl.SessionFactoryImpl.<init>(SessionFactoryImpl.java:311)
	at org.hibernate.cfg.Configuration.buildSessionFactory(Configuration.java:1300)
	at store.util.HibernateUtil.<clinit>(HibernateUtil.java:8)
	at store.TuttiCondomini.recuperaCondomini(TuttiCondomini.java:34)
	at executor.GestoreCondomini.<init>(GestoreCondomini.java:60)
	at executor.GestoreCondomini.getInstance(GestoreCondomini.java:38)
	at executor.Avvio.inizializzaAmICo(Avvio.java:39)
	at executor.Avvio.main(Avvio.java:28)
02-08 14:56:16 jdbc[2]: SQLException
org.h2.jdbc.JdbcSQLException: Table PAGAMENTO not found; SQL statement:
alter table PAGAMENTO drop constraint FKD4B22306D4E54CE4 [42102-69]
	at org.h2.message.Message.getSQLException(Message.java:91)
	at org.h2.message.Message.getSQLException(Message.java:95)
	at org.h2.message.Message.getSQLException(Message.java:73)
	at org.h2.command.Parser.readTableOrView(Parser.java:4025)
	at org.h2.command.Parser.readTableOrView(Parser.java:4005)
	at org.h2.command.Parser.parseAlterTable(Parser.java:4050)
	at org.h2.command.Parser.parseAlter(Parser.java:3622)
	at org.h2.command.Parser.parsePrepared(Parser.java:302)
	at org.h2.command.Parser.parse(Parser.java:285)
	at org.h2.command.Parser.parse(Parser.java:257)
	at org.h2.command.Parser.prepareCommand(Parser.java:229)
	at org.h2.engine.Session.prepareLocal(Session.java:236)
	at org.h2.engine.Session.prepareCommand(Session.java:218)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1020)
	at org.h2.jdbc.JdbcStatement.executeUpdate(JdbcStatement.java:104)
	at org.hibernate.tool.hbm2ddl.SchemaExport.execute(SchemaExport.java:308)
	at org.hibernate.tool.hbm2ddl.SchemaExport.drop(SchemaExport.java:284)
	at org.hibernate.tool.hbm2ddl.SchemaExport.execute(SchemaExport.java:186)
	at org.hibernate.tool.hbm2ddl.SchemaExport.create(SchemaExport.java:133)
	at org.hibernate.impl.SessionFactoryImpl.<init>(SessionFactoryImpl.java:311)
	at org.hibernate.cfg.Configuration.buildSessionFactory(Configuration.java:1300)
	at store.util.HibernateUtil.<clinit>(HibernateUtil.java:8)
	at store.TuttiCondomini.recuperaCondomini(TuttiCondomini.java:34)
	at executor.GestoreCondomini.<init>(GestoreCondomini.java:60)
	at executor.GestoreCondomini.getInstance(GestoreCondomini.java:38)
	at executor.Avvio.inizializzaAmICo(Avvio.java:39)
	at executor.Avvio.main(Avvio.java:28)
02-08 14:56:16 jdbc[2]: SQLException
org.h2.jdbc.JdbcSQLException: Table PERSONA not found; SQL statement:
alter table PERSONA drop constraint FK25B5B8CE0AC6D57 [42102-69]
	at org.h2.message.Message.getSQLException(Message.java:91)
	at org.h2.message.Message.getSQLException(Message.java:95)
	at org.h2.message.Message.getSQLException(Message.java:73)
	at org.h2.command.Parser.readTableOrView(Parser.java:4025)
	at org.h2.command.Parser.readTableOrView(Parser.java:4005)
	at org.h2.command.Parser.parseAlterTable(Parser.java:4050)
	at org.h2.command.Parser.parseAlter(Parser.java:3622)
	at org.h2.command.Parser.parsePrepared(Parser.java:302)
	at org.h2.command.Parser.parse(Parser.java:285)
	at org.h2.command.Parser.parse(Parser.java:257)
	at org.h2.command.Parser.prepareCommand(Parser.java:229)
	at org.h2.engine.Session.prepareLocal(Session.java:236)
	at org.h2.engine.Session.prepareCommand(Session.java:218)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1020)
	at org.h2.jdbc.JdbcStatement.executeUpdate(JdbcStatement.java:104)
	at org.hibernate.tool.hbm2ddl.SchemaExport.execute(SchemaExport.java:308)
	at org.hibernate.tool.hbm2ddl.SchemaExport.drop(SchemaExport.java:284)
	at org.hibernate.tool.hbm2ddl.SchemaExport.execute(SchemaExport.java:186)
	at org.hibernate.tool.hbm2ddl.SchemaExport.create(SchemaExport.java:133)
	at org.hibernate.impl.SessionFactoryImpl.<init>(SessionFactoryImpl.java:311)
	at org.hibernate.cfg.Configuration.buildSessionFactory(Configuration.java:1300)
	at store.util.HibernateUtil.<clinit>(HibernateUtil.java:8)
	at store.TuttiCondomini.recuperaCondomini(TuttiCondomini.java:34)
	at executor.GestoreCondomini.<init>(GestoreCondomini.java:60)
	at executor.GestoreCondomini.getInstance(GestoreCondomini.java:38)
	at executor.Avvio.inizializzaAmICo(Avvio.java:39)
	at executor.Avvio.main(Avvio.java:28)
02-08 14:56:16 jdbc[2]: SQLException
org.h2.jdbc.JdbcSQLException: Table PIANO_PAGAMENTI not found; SQL statement:
alter table PIANO_PAGAMENTI drop constraint FKD2BB036AC6AE3230 [42102-69]
	at org.h2.message.Message.getSQLException(Message.java:91)
	at org.h2.message.Message.getSQLException(Message.java:95)
	at org.h2.message.Message.getSQLException(Message.java:73)
	at org.h2.command.Parser.readTableOrView(Parser.java:4025)
	at org.h2.command.Parser.readTableOrView(Parser.java:4005)
	at org.h2.command.Parser.parseAlterTable(Parser.java:4050)
	at org.h2.command.Parser.parseAlter(Parser.java:3622)
	at org.h2.command.Parser.parsePrepared(Parser.java:302)
	at org.h2.command.Parser.parse(Parser.java:285)
	at org.h2.command.Parser.parse(Parser.java:257)
	at org.h2.command.Parser.prepareCommand(Parser.java:229)
	at org.h2.engine.Session.prepareLocal(Session.java:236)
	at org.h2.engine.Session.prepareCommand(Session.java:218)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1020)
	at org.h2.jdbc.JdbcStatement.executeUpdate(JdbcStatement.java:104)
	at org.hibernate.tool.hbm2ddl.SchemaExport.execute(SchemaExport.java:308)
	at org.hibernate.tool.hbm2ddl.SchemaExport.drop(SchemaExport.java:284)
	at org.hibernate.tool.hbm2ddl.SchemaExport.execute(SchemaExport.java:186)
	at org.hibernate.tool.hbm2ddl.SchemaExport.create(SchemaExport.java:133)
	at org.hibernate.impl.SessionFactoryImpl.<init>(SessionFactoryImpl.java:311)
	at org.hibernate.cfg.Configuration.buildSessionFactory(Configuration.java:1300)
	at store.util.HibernateUtil.<clinit>(HibernateUtil.java:8)
	at store.TuttiCondomini.recuperaCondomini(TuttiCondomini.java:34)
	at executor.GestoreCondomini.<init>(GestoreCondomini.java:60)
	at executor.GestoreCondomini.getInstance(GestoreCondomini.java:38)
	at executor.Avvio.inizializzaAmICo(Avvio.java:39)
	at executor.Avvio.main(Avvio.java:28)
02-08 14:56:16 jdbc[2]: SQLException
org.h2.jdbc.JdbcSQLException: Table PIANO_PAGAMENTI not found; SQL statement:
alter table PIANO_PAGAMENTI drop constraint FKD2BB036AA2884757 [42102-69]
	at org.h2.message.Message.getSQLException(Message.java:91)
	at org.h2.message.Message.getSQLException(Message.java:95)
	at org.h2.message.Message.getSQLException(Message.java:73)
	at org.h2.command.Parser.readTableOrView(Parser.java:4025)
	at org.h2.command.Parser.readTableOrView(Parser.java:4005)
	at org.h2.command.Parser.parseAlterTable(Parser.java:4050)
	at org.h2.command.Parser.parseAlter(Parser.java:3622)
	at org.h2.command.Parser.parsePrepared(Parser.java:302)
	at org.h2.command.Parser.parse(Parser.java:285)
	at org.h2.command.Parser.parse(Parser.java:257)
	at org.h2.command.Parser.prepareCommand(Parser.java:229)
	at org.h2.engine.Session.prepareLocal(Session.java:236)
	at org.h2.engine.Session.prepareCommand(Session.java:218)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1020)
	at org.h2.jdbc.JdbcStatement.executeUpdate(JdbcStatement.java:104)
	at org.hibernate.tool.hbm2ddl.SchemaExport.execute(SchemaExport.java:308)
	at org.hibernate.tool.hbm2ddl.SchemaExport.drop(SchemaExport.java:284)
	at org.hibernate.tool.hbm2ddl.SchemaExport.execute(SchemaExport.java:186)
	at org.hibernate.tool.hbm2ddl.SchemaExport.create(SchemaExport.java:133)
	at org.hibernate.impl.SessionFactoryImpl.<init>(SessionFactoryImpl.java:311)
	at org.hibernate.cfg.Configuration.buildSessionFactory(Configuration.java:1300)
	at store.util.HibernateUtil.<clinit>(HibernateUtil.java:8)
	at store.TuttiCondomini.recuperaCondomini(TuttiCondomini.java:34)
	at executor.GestoreCondomini.<init>(GestoreCondomini.java:60)
	at executor.GestoreCondomini.getInstance(GestoreCondomini.java:38)
	at executor.Avvio.inizializzaAmICo(Avvio.java:39)
	at executor.Avvio.main(Avvio.java:28)
02-08 14:56:16 jdbc[2]: SQLException
org.h2.jdbc.JdbcSQLException: Table PROPRIETA not found; SQL statement:
alter table PROPRIETA drop constraint FK7BB8CE58464E24E7 [42102-69]
	at org.h2.message.Message.getSQLException(Message.java:91)
	at org.h2.message.Message.getSQLException(Message.java:95)
	at org.h2.message.Message.getSQLException(Message.java:73)
	at org.h2.command.Parser.readTableOrView(Parser.java:4025)
	at org.h2.command.Parser.readTableOrView(Parser.java:4005)
	at org.h2.command.Parser.parseAlterTable(Parser.java:4050)
	at org.h2.command.Parser.parseAlter(Parser.java:3622)
	at org.h2.command.Parser.parsePrepared(Parser.java:302)
	at org.h2.command.Parser.parse(Parser.java:285)
	at org.h2.command.Parser.parse(Parser.java:257)
	at org.h2.command.Parser.prepareCommand(Parser.java:229)
	at org.h2.engine.Session.prepareLocal(Session.java:236)
	at org.h2.engine.Session.prepareCommand(Session.java:218)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1020)
	at org.h2.jdbc.JdbcStatement.executeUpdate(JdbcStatement.java:104)
	at org.hibernate.tool.hbm2ddl.SchemaExport.execute(SchemaExport.java:308)
	at org.hibernate.tool.hbm2ddl.SchemaExport.drop(SchemaExport.java:284)
	at org.hibernate.tool.hbm2ddl.SchemaExport.execute(SchemaExport.java:186)
	at org.hibernate.tool.hbm2ddl.SchemaExport.create(SchemaExport.java:133)
	at org.hibernate.impl.SessionFactoryImpl.<init>(SessionFactoryImpl.java:311)
	at org.hibernate.cfg.Configuration.buildSessionFactory(Configuration.java:1300)
	at store.util.HibernateUtil.<clinit>(HibernateUtil.java:8)
	at store.TuttiCondomini.recuperaCondomini(TuttiCondomini.java:34)
	at executor.GestoreCondomini.<init>(GestoreCondomini.java:60)
	at executor.GestoreCondomini.getInstance(GestoreCondomini.java:38)
	at executor.Avvio.inizializzaAmICo(Avvio.java:39)
	at executor.Avvio.main(Avvio.java:28)
02-08 14:56:16 jdbc[2]: SQLException
org.h2.jdbc.JdbcSQLException: Table PROPRIETA not found; SQL statement:
alter table PROPRIETA drop constraint FK7BB8CE586AA91D9D [42102-69]
	at org.h2.message.Message.getSQLException(Message.java:91)
	at org.h2.message.Message.getSQLException(Message.java:95)
	at org.h2.message.Message.getSQLException(Message.java:73)
	at org.h2.command.Parser.readTableOrView(Parser.java:4025)
	at org.h2.command.Parser.readTableOrView(Parser.java:4005)
	at org.h2.command.Parser.parseAlterTable(Parser.java:4050)
	at org.h2.command.Parser.parseAlter(Parser.java:3622)
	at org.h2.command.Parser.parsePrepared(Parser.java:302)
	at org.h2.command.Parser.parse(Parser.java:285)
	at org.h2.command.Parser.parse(Parser.java:257)
	at org.h2.command.Parser.prepareCommand(Parser.java:229)
	at org.h2.engine.Session.prepareLocal(Session.java:236)
	at org.h2.engine.Session.prepareCommand(Session.java:218)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1020)
	at org.h2.jdbc.JdbcStatement.executeUpdate(JdbcStatement.java:104)
	at org.hibernate.tool.hbm2ddl.SchemaExport.execute(SchemaExport.java:308)
	at org.hibernate.tool.hbm2ddl.SchemaExport.drop(SchemaExport.java:284)
	at org.hibernate.tool.hbm2ddl.SchemaExport.execute(SchemaExport.java:186)
	at org.hibernate.tool.hbm2ddl.SchemaExport.create(SchemaExport.java:133)
	at org.hibernate.impl.SessionFactoryImpl.<init>(SessionFactoryImpl.java:311)
	at org.hibernate.cfg.Configuration.buildSessionFactory(Configuration.java:1300)
	at store.util.HibernateUtil.<clinit>(HibernateUtil.java:8)
	at store.TuttiCondomini.recuperaCondomini(TuttiCondomini.java:34)
	at executor.GestoreCondomini.<init>(GestoreCondomini.java:60)
	at executor.GestoreCondomini.getInstance(GestoreCondomini.java:38)
	at executor.Avvio.inizializzaAmICo(Avvio.java:39)
	at executor.Avvio.main(Avvio.java:28)
02-08 14:56:16 jdbc[2]: SQLException
org.h2.jdbc.JdbcSQLException: Table TABELLA_MILLESIMALE not found; SQL statement:
alter table TABELLA_MILLESIMALE drop constraint FK42F9245EC56C4797 [42102-69]
	at org.h2.message.Message.getSQLException(Message.java:91)
	at org.h2.message.Message.getSQLException(Message.java:95)
	at org.h2.message.Message.getSQLException(Message.java:73)
	at org.h2.command.Parser.readTableOrView(Parser.java:4025)
	at org.h2.command.Parser.readTableOrView(Parser.java:4005)
	at org.h2.command.Parser.parseAlterTable(Parser.java:4050)
	at org.h2.command.Parser.parseAlter(Parser.java:3622)
	at org.h2.command.Parser.parsePrepared(Parser.java:302)
	at org.h2.command.Parser.parse(Parser.java:285)
	at org.h2.command.Parser.parse(Parser.java:257)
	at org.h2.command.Parser.prepareCommand(Parser.java:229)
	at org.h2.engine.Session.prepareLocal(Session.java:236)
	at org.h2.engine.Session.prepareCommand(Session.java:218)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1020)
	at org.h2.jdbc.JdbcStatement.executeUpdate(JdbcStatement.java:104)
	at org.hibernate.tool.hbm2ddl.SchemaExport.execute(SchemaExport.java:308)
	at org.hibernate.tool.hbm2ddl.SchemaExport.drop(SchemaExport.java:284)
	at org.hibernate.tool.hbm2ddl.SchemaExport.execute(SchemaExport.java:186)
	at org.hibernate.tool.hbm2ddl.SchemaExport.create(SchemaExport.java:133)
	at org.hibernate.impl.SessionFactoryImpl.<init>(SessionFactoryImpl.java:311)
	at org.hibernate.cfg.Configuration.buildSessionFactory(Configuration.java:1300)
	at store.util.HibernateUtil.<clinit>(HibernateUtil.java:8)
	at store.TuttiCondomini.recuperaCondomini(TuttiCondomini.java:34)
	at executor.GestoreCondomini.<init>(GestoreCondomini.java:60)
	at executor.GestoreCondomini.getInstance(GestoreCondomini.java:38)
	at executor.Avvio.inizializzaAmICo(Avvio.java:39)
	at executor.Avvio.main(Avvio.java:28)
02-08 14:56:16 jdbc[2]: SQLException
org.h2.jdbc.JdbcSQLException: Table UNITA_IMMOBILIARE not found; SQL statement:
alter table UNITA_IMMOBILIARE drop constraint FK63FF3928C56C4797 [42102-69]
	at org.h2.message.Message.getSQLException(Message.java:91)
	at org.h2.message.Message.getSQLException(Message.java:95)
	at org.h2.message.Message.getSQLException(Message.java:73)
	at org.h2.command.Parser.readTableOrView(Parser.java:4025)
	at org.h2.command.Parser.readTableOrView(Parser.java:4005)
	at org.h2.command.Parser.parseAlterTable(Parser.java:4050)
	at org.h2.command.Parser.parseAlter(Parser.java:3622)
	at org.h2.command.Parser.parsePrepared(Parser.java:302)
	at org.h2.command.Parser.parse(Parser.java:285)
	at org.h2.command.Parser.parse(Parser.java:257)
	at org.h2.command.Parser.prepareCommand(Parser.java:229)
	at org.h2.engine.Session.prepareLocal(Session.java:236)
	at org.h2.engine.Session.prepareCommand(Session.java:218)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1020)
	at org.h2.jdbc.JdbcStatement.executeUpdate(JdbcStatement.java:104)
	at org.hibernate.tool.hbm2ddl.SchemaExport.execute(SchemaExport.java:308)
	at org.hibernate.tool.hbm2ddl.SchemaExport.drop(SchemaExport.java:284)
	at org.hibernate.tool.hbm2ddl.SchemaExport.execute(SchemaExport.java:186)
	at org.hibernate.tool.hbm2ddl.SchemaExport.create(SchemaExport.java:133)
	at org.hibernate.impl.SessionFactoryImpl.<init>(SessionFactoryImpl.java:311)
	at org.hibernate.cfg.Configuration.buildSessionFactory(Configuration.java:1300)
	at store.util.HibernateUtil.<clinit>(HibernateUtil.java:8)
	at store.TuttiCondomini.recuperaCondomini(TuttiCondomini.java:34)
	at executor.GestoreCondomini.<init>(GestoreCondomini.java:60)
	at executor.GestoreCondomini.getInstance(GestoreCondomini.java:38)
	at executor.Avvio.inizializzaAmICo(Avvio.java:39)
	at executor.Avvio.main(Avvio.java:28)
02-08 14:56:16 jdbc[2]: SQLException
org.h2.jdbc.JdbcSQLException: Table VOCE_BILANCIO not found; SQL statement:
alter table VOCE_BILANCIO drop constraint FKB7FEE67BC6AE3230 [42102-69]
	at org.h2.message.Message.getSQLException(Message.java:91)
	at org.h2.message.Message.getSQLException(Message.java:95)
	at org.h2.message.Message.getSQLException(Message.java:73)
	at org.h2.command.Parser.readTableOrView(Parser.java:4025)
	at org.h2.command.Parser.readTableOrView(Parser.java:4005)
	at org.h2.command.Parser.parseAlterTable(Parser.java:4050)
	at org.h2.command.Parser.parseAlter(Parser.java:3622)
	at org.h2.command.Parser.parsePrepared(Parser.java:302)
	at org.h2.command.Parser.parse(Parser.java:285)
	at org.h2.command.Parser.parse(Parser.java:257)
	at org.h2.command.Parser.prepareCommand(Parser.java:229)
	at org.h2.engine.Session.prepareLocal(Session.java:236)
	at org.h2.engine.Session.prepareCommand(Session.java:218)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1020)
	at org.h2.jdbc.JdbcStatement.executeUpdate(JdbcStatement.java:104)
	at org.hibernate.tool.hbm2ddl.SchemaExport.execute(SchemaExport.java:308)
	at org.hibernate.tool.hbm2ddl.SchemaExport.drop(SchemaExport.java:284)
	at org.hibernate.tool.hbm2ddl.SchemaExport.execute(SchemaExport.java:186)
	at org.hibernate.tool.hbm2ddl.SchemaExport.create(SchemaExport.java:133)
	at org.hibernate.impl.SessionFactoryImpl.<init>(SessionFactoryImpl.java:311)
	at org.hibernate.cfg.Configuration.buildSessionFactory(Configuration.java:1300)
	at store.util.HibernateUtil.<clinit>(HibernateUtil.java:8)
	at store.TuttiCondomini.recuperaCondomini(TuttiCondomini.java:34)
	at executor.GestoreCondomini.<init>(GestoreCondomini.java:60)
	at executor.GestoreCondomini.getInstance(GestoreCondomini.java:38)
	at executor.Avvio.inizializzaAmICo(Avvio.java:39)
	at executor.Avvio.main(Avvio.java:28)
02-08 14:56:16 jdbc[2]: SQLException
org.h2.jdbc.JdbcSQLException: Table VOCE_BILANCIO not found; SQL statement:
alter table VOCE_BILANCIO drop constraint FKB7FEE67BA2884757 [42102-69]
	at org.h2.message.Message.getSQLException(Message.java:91)
	at org.h2.message.Message.getSQLException(Message.java:95)
	at org.h2.message.Message.getSQLException(Message.java:73)
	at org.h2.command.Parser.readTableOrView(Parser.java:4025)
	at org.h2.command.Parser.readTableOrView(Parser.java:4005)
	at org.h2.command.Parser.parseAlterTable(Parser.java:4050)
	at org.h2.command.Parser.parseAlter(Parser.java:3622)
	at org.h2.command.Parser.parsePrepared(Parser.java:302)
	at org.h2.command.Parser.parse(Parser.java:285)
	at org.h2.command.Parser.parse(Parser.java:257)
	at org.h2.command.Parser.prepareCommand(Parser.java:229)
	at org.h2.engine.Session.prepareLocal(Session.java:236)
	at org.h2.engine.Session.prepareCommand(Session.java:218)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1020)
	at org.h2.jdbc.JdbcStatement.executeUpdate(JdbcStatement.java:104)
	at org.hibernate.tool.hbm2ddl.SchemaExport.execute(SchemaExport.java:308)
	at org.hibernate.tool.hbm2ddl.SchemaExport.drop(SchemaExport.java:284)
	at org.hibernate.tool.hbm2ddl.SchemaExport.execute(SchemaExport.java:186)
	at org.hibernate.tool.hbm2ddl.SchemaExport.create(SchemaExport.java:133)
	at org.hibernate.impl.SessionFactoryImpl.<init>(SessionFactoryImpl.java:311)
	at org.hibernate.cfg.Configuration.buildSessionFactory(Configuration.java:1300)
	at store.util.HibernateUtil.<clinit>(HibernateUtil.java:8)
	at store.TuttiCondomini.recuperaCondomini(TuttiCondomini.java:34)
	at executor.GestoreCondomini.<init>(GestoreCondomini.java:60)
	at executor.GestoreCondomini.getInstance(GestoreCondomini.java:38)
	at executor.Avvio.inizializzaAmICo(Avvio.java:39)
	at executor.Avvio.main(Avvio.java:28)
02-08 14:56:16 jdbc[2]: SQLException
org.h2.jdbc.JdbcSQLException: Table VOCE_BILANCIO not found; SQL statement:
alter table VOCE_BILANCIO drop constraint FKB7FEE67B16A9B8E6 [42102-69]
	at org.h2.message.Message.getSQLException(Message.java:91)
	at org.h2.message.Message.getSQLException(Message.java:95)
	at org.h2.message.Message.getSQLException(Message.java:73)
	at org.h2.command.Parser.readTableOrView(Parser.java:4025)
	at org.h2.command.Parser.readTableOrView(Parser.java:4005)
	at org.h2.command.Parser.parseAlterTable(Parser.java:4050)
	at org.h2.command.Parser.parseAlter(Parser.java:3622)
	at org.h2.command.Parser.parsePrepared(Parser.java:302)
	at org.h2.command.Parser.parse(Parser.java:285)
	at org.h2.command.Parser.parse(Parser.java:257)
	at org.h2.command.Parser.prepareCommand(Parser.java:229)
	at org.h2.engine.Session.prepareLocal(Session.java:236)
	at org.h2.engine.Session.prepareCommand(Session.java:218)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1020)
	at org.h2.jdbc.JdbcStatement.executeUpdate(JdbcStatement.java:104)
	at org.hibernate.tool.hbm2ddl.SchemaExport.execute(SchemaExport.java:308)
	at org.hibernate.tool.hbm2ddl.SchemaExport.drop(SchemaExport.java:284)
	at org.hibernate.tool.hbm2ddl.SchemaExport.execute(SchemaExport.java:186)
	at org.hibernate.tool.hbm2ddl.SchemaExport.create(SchemaExport.java:133)
	at org.hibernate.impl.SessionFactoryImpl.<init>(SessionFactoryImpl.java:311)
	at org.hibernate.cfg.Configuration.buildSessionFactory(Configuration.java:1300)
	at store.util.HibernateUtil.<clinit>(HibernateUtil.java:8)
	at store.TuttiCondomini.recuperaCondomini(TuttiCondomini.java:34)
	at executor.GestoreCondomini.<init>(GestoreCondomini.java:60)
	at executor.GestoreCondomini.getInstance(GestoreCondomini.java:38)
	at executor.Avvio.inizializzaAmICo(Avvio.java:39)
	at executor.Avvio.main(Avvio.java:28)
02-08 14:56:16 jdbc[2]: SQLException
org.h2.jdbc.JdbcSQLException: Table PERSONE_CONDOMINI not found; SQL statement:
alter table persone_condomini drop constraint FKAECFB9956AA91D9D [42102-69]
	at org.h2.message.Message.getSQLException(Message.java:91)
	at org.h2.message.Message.getSQLException(Message.java:95)
	at org.h2.message.Message.getSQLException(Message.java:73)
	at org.h2.command.Parser.readTableOrView(Parser.java:4025)
	at org.h2.command.Parser.readTableOrView(Parser.java:4005)
	at org.h2.command.Parser.parseAlterTable(Parser.java:4050)
	at org.h2.command.Parser.parseAlter(Parser.java:3622)
	at org.h2.command.Parser.parsePrepared(Parser.java:302)
	at org.h2.command.Parser.parse(Parser.java:285)
	at org.h2.command.Parser.parse(Parser.java:257)
	at org.h2.command.Parser.prepareCommand(Parser.java:229)
	at org.h2.engine.Session.prepareLocal(Session.java:236)
	at org.h2.engine.Session.prepareCommand(Session.java:218)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1020)
	at org.h2.jdbc.JdbcStatement.executeUpdate(JdbcStatement.java:104)
	at org.hibernate.tool.hbm2ddl.SchemaExport.execute(SchemaExport.java:308)
	at org.hibernate.tool.hbm2ddl.SchemaExport.drop(SchemaExport.java:284)
	at org.hibernate.tool.hbm2ddl.SchemaExport.execute(SchemaExport.java:186)
	at org.hibernate.tool.hbm2ddl.SchemaExport.create(SchemaExport.java:133)
	at org.hibernate.impl.SessionFactoryImpl.<init>(SessionFactoryImpl.java:311)
	at org.hibernate.cfg.Configuration.buildSessionFactory(Configuration.java:1300)
	at store.util.HibernateUtil.<clinit>(HibernateUtil.java:8)
	at store.TuttiCondomini.recuperaCondomini(TuttiCondomini.java:34)
	at executor.GestoreCondomini.<init>(GestoreCondomini.java:60)
	at executor.GestoreCondomini.getInstance(GestoreCondomini.java:38)
	at executor.Avvio.inizializzaAmICo(Avvio.java:39)
	at executor.Avvio.main(Avvio.java:28)
02-08 14:56:16 jdbc[2]: SQLException
org.h2.jdbc.JdbcSQLException: Table PERSONE_CONDOMINI not found; SQL statement:
alter table persone_condomini drop constraint FKAECFB995C56C4797 [42102-69]
	at org.h2.message.Message.getSQLException(Message.java:91)
	at org.h2.message.Message.getSQLException(Message.java:95)
	at org.h2.message.Message.getSQLException(Message.java:73)
	at org.h2.command.Parser.readTableOrView(Parser.java:4025)
	at org.h2.command.Parser.readTableOrView(Parser.java:4005)
	at org.h2.command.Parser.parseAlterTable(Parser.java:4050)
	at org.h2.command.Parser.parseAlter(Parser.java:3622)
	at org.h2.command.Parser.parsePrepared(Parser.java:302)
	at org.h2.command.Parser.parse(Parser.java:285)
	at org.h2.command.Parser.parse(Parser.java:257)
	at org.h2.command.Parser.prepareCommand(Parser.java:229)
	at org.h2.engine.Session.prepareLocal(Session.java:236)
	at org.h2.engine.Session.prepareCommand(Session.java:218)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1020)
	at org.h2.jdbc.JdbcStatement.executeUpdate(JdbcStatement.java:104)
	at org.hibernate.tool.hbm2ddl.SchemaExport.execute(SchemaExport.java:308)
	at org.hibernate.tool.hbm2ddl.SchemaExport.drop(SchemaExport.java:284)
	at org.hibernate.tool.hbm2ddl.SchemaExport.execute(SchemaExport.java:186)
	at org.hibernate.tool.hbm2ddl.SchemaExport.create(SchemaExport.java:133)
	at org.hibernate.impl.SessionFactoryImpl.<init>(SessionFactoryImpl.java:311)
	at org.hibernate.cfg.Configuration.buildSessionFactory(Configuration.java:1300)
	at store.util.HibernateUtil.<clinit>(HibernateUtil.java:8)
	at store.TuttiCondomini.recuperaCondomini(TuttiCondomini.java:34)
	at executor.GestoreCondomini.<init>(GestoreCondomini.java:60)
	at executor.GestoreCondomini.getInstance(GestoreCondomini.java:38)
	at executor.Avvio.inizializzaAmICo(Avvio.java:39)
	at executor.Avvio.main(Avvio.java:28)
02-08 14:57:45 database: opening C:\Documents and Settings\Federico\workspace\AmICo\DB\DataBase4Amico
org.h2.jdbc.JdbcSQLException: Database may be already in use: Locked by another process. Possible solutions: close all other connection(s); use the server mode [90020-69]
	at org.h2.message.Message.getSQLException(Message.java:91)
	at org.h2.message.Message.getSQLException(Message.java:95)
	at org.h2.message.Message.getSQLException(Message.java:73)
	at org.h2.store.FileLock.error(FileLock.java:316)
	at org.h2.store.FileLock.lockFile(FileLock.java:178)
	at org.h2.store.FileLock.lock(FileLock.java:74)
	at org.h2.engine.Database.open(Database.java:467)
	at org.h2.engine.Database.<init>(Database.java:203)
	at org.h2.engine.Engine.openSession(Engine.java:55)
	at org.h2.engine.Engine.getSession(Engine.java:104)
	at org.h2.engine.Session.createSession(Session.java:203)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:976)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:957)
	at org.h2.Driver.connect(Driver.java:57)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at org.hibernate.connection.DriverManagerConnectionProvider.getConnection(DriverManagerConnectionProvider.java:110)
	at org.hibernate.cfg.SettingsFactory.buildSettings(SettingsFactory.java:84)
	at org.hibernate.cfg.Configuration.buildSettings(Configuration.java:2073)
	at org.hibernate.cfg.Configuration.buildSessionFactory(Configuration.java:1298)
	at store.util.HibernateUtil.<clinit>(HibernateUtil.java:8)
	at store.TuttiCondomini.recuperaCondomini(TuttiCondomini.java:34)
	at executor.GestoreCondomini.<init>(GestoreCondomini.java:60)
	at executor.GestoreCondomini.getInstance(GestoreCondomini.java:38)
	at executor.Avvio.inizializzaAmICo(Avvio.java:39)
	at executor.Avvio.main(Avvio.java:28)
02-08 15:00:06 jdbc[3]: Connection not closed
java.lang.Exception: Stack Trace
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:988)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:957)
	at org.h2.Driver.connect(Driver.java:57)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at org.hibernate.connection.DriverManagerConnectionProvider.getConnection(DriverManagerConnectionProvider.java:110)
	at org.hibernate.jdbc.ConnectionManager.openConnection(ConnectionManager.java:423)
	at org.hibernate.jdbc.ConnectionManager.getConnection(ConnectionManager.java:144)
	at org.hibernate.jdbc.JDBCContext.connection(JDBCContext.java:119)
	at org.hibernate.transaction.JDBCTransaction.begin(JDBCTransaction.java:57)
	at org.hibernate.impl.SessionImpl.beginTransaction(SessionImpl.java:1326)
	at sun.reflect.GeneratedMethodAccessor55.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.hibernate.context.ThreadLocalSessionContext$TransactionProtectionWrapper.invoke(ThreadLocalSessionContext.java:301)
	at $Proxy0.beginTransaction(Unknown Source)
	at store.POJO.UnitaImmobiliare.modificaProprieta(UnitaImmobiliare.java:99)
	at executor.GestoreCondomini.passaProprieta(GestoreCondomini.java:200)
	at boundary.ConfermaUnitaImmobiliari.proprietaOK(ConfermaUnitaImmobiliari.java:163)
	at boundary.AccedereProprietari.bOKMouseMouseClicked(AccedereProprietari.java:191)
	at boundary.AccedereProprietari.access$2(AccedereProprietari.java:189)
	at boundary.AccedereProprietari$4.mouseClicked(AccedereProprietari.java:317)
	at java.awt.AWTEventMulticaster.mouseClicked(Unknown Source)
	at java.awt.Component.processMouseEvent(Unknown Source)
	at javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
02-09 12:38:52 database: opening C:\Documents and Settings\Federico\workspace\AmICo\DB\DataBase4Amico
org.h2.jdbc.JdbcSQLException: Database may be already in use: Locked by another process. Possible solutions: close all other connection(s); use the server mode [90020-69]
	at org.h2.message.Message.getSQLException(Message.java:91)
	at org.h2.message.Message.getSQLException(Message.java:95)
	at org.h2.message.Message.getSQLException(Message.java:73)
	at org.h2.store.FileLock.error(FileLock.java:316)
	at org.h2.store.FileLock.lockFile(FileLock.java:178)
	at org.h2.store.FileLock.lock(FileLock.java:74)
	at org.h2.engine.Database.open(Database.java:467)
	at org.h2.engine.Database.<init>(Database.java:203)
	at org.h2.engine.Engine.openSession(Engine.java:55)
	at org.h2.engine.Engine.getSession(Engine.java:104)
	at org.h2.engine.Session.createSession(Session.java:203)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:976)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:957)
	at org.h2.Driver.connect(Driver.java:57)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at org.hibernate.connection.DriverManagerConnectionProvider.getConnection(DriverManagerConnectionProvider.java:110)
	at org.hibernate.cfg.SettingsFactory.buildSettings(SettingsFactory.java:84)
	at org.hibernate.cfg.Configuration.buildSettings(Configuration.java:2073)
	at org.hibernate.cfg.Configuration.buildSessionFactory(Configuration.java:1298)
	at store.util.HibernateUtil.<clinit>(HibernateUtil.java:8)
	at store.TuttiCondomini.recuperaCondomini(TuttiCondomini.java:34)
	at executor.GestoreCondomini.<init>(GestoreCondomini.java:60)
	at executor.GestoreCondomini.getInstance(GestoreCondomini.java:38)
	at executor.Avvio.inizializzaAmICo(Avvio.java:39)
	at executor.Avvio.main(Avvio.java:28)
02-09 12:38:55 database: opening C:\Documents and Settings\Federico\workspace\AmICo\DB\DataBase4Amico
org.h2.jdbc.JdbcSQLException: Database may be already in use: Locked by another process. Possible solutions: close all other connection(s); use the server mode [90020-69]
	at org.h2.message.Message.getSQLException(Message.java:91)
	at org.h2.message.Message.getSQLException(Message.java:95)
	at org.h2.message.Message.getSQLException(Message.java:73)
	at org.h2.store.FileLock.error(FileLock.java:316)
	at org.h2.store.FileLock.lockFile(FileLock.java:178)
	at org.h2.store.FileLock.lock(FileLock.java:74)
	at org.h2.engine.Database.open(Database.java:467)
	at org.h2.engine.Database.<init>(Database.java:203)
	at org.h2.engine.Engine.openSession(Engine.java:55)
	at org.h2.engine.Engine.getSession(Engine.java:104)
	at org.h2.engine.Session.createSession(Session.java:203)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:976)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:957)
	at org.h2.Driver.connect(Driver.java:57)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at org.hibernate.connection.DriverManagerConnectionProvider.getConnection(DriverManagerConnectionProvider.java:110)
	at org.hibernate.jdbc.ConnectionManager.openConnection(ConnectionManager.java:423)
	at org.hibernate.jdbc.ConnectionManager.getConnection(ConnectionManager.java:144)
	at org.hibernate.jdbc.JDBCContext.connection(JDBCContext.java:119)
	at org.hibernate.transaction.JDBCTransaction.begin(JDBCTransaction.java:57)
	at org.hibernate.impl.SessionImpl.beginTransaction(SessionImpl.java:1326)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.hibernate.context.ThreadLocalSessionContext$TransactionProtectionWrapper.invoke(ThreadLocalSessionContext.java:301)
	at $Proxy0.beginTransaction(Unknown Source)
	at store.TuttiCondomini.recuperaCondomini(TuttiCondomini.java:35)
	at executor.GestoreCondomini.<init>(GestoreCondomini.java:60)
	at executor.GestoreCondomini.getInstance(GestoreCondomini.java:38)
	at executor.Avvio.inizializzaAmICo(Avvio.java:39)
	at executor.Avvio.main(Avvio.java:28)
02-09 18:47:12 database: opening C:\Documents and Settings\Federico\workspace\AmICo\DB\DataBase4Amico
org.h2.jdbc.JdbcSQLException: Database may be already in use: Locked by another process. Possible solutions: close all other connection(s); use the server mode [90020-69]
	at org.h2.message.Message.getSQLException(Message.java:91)
	at org.h2.message.Message.getSQLException(Message.java:95)
	at org.h2.message.Message.getSQLException(Message.java:73)
	at org.h2.store.FileLock.error(FileLock.java:316)
	at org.h2.store.FileLock.lockFile(FileLock.java:178)
	at org.h2.store.FileLock.lock(FileLock.java:74)
	at org.h2.engine.Database.open(Database.java:467)
	at org.h2.engine.Database.<init>(Database.java:203)
	at org.h2.engine.Engine.openSession(Engine.java:55)
	at org.h2.engine.Engine.getSession(Engine.java:104)
	at org.h2.engine.Session.createSession(Session.java:203)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:976)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:957)
	at org.h2.Driver.connect(Driver.java:57)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at org.hibernate.connection.DriverManagerConnectionProvider.getConnection(DriverManagerConnectionProvider.java:110)
	at org.hibernate.cfg.SettingsFactory.buildSettings(SettingsFactory.java:84)
	at org.hibernate.cfg.Configuration.buildSettings(Configuration.java:2073)
	at org.hibernate.cfg.Configuration.buildSessionFactory(Configuration.java:1298)
	at store.util.HibernateUtil.<clinit>(HibernateUtil.java:8)
	at store.TuttiCondomini.recuperaCondomini(TuttiCondomini.java:34)
	at executor.GestoreCondomini.<init>(GestoreCondomini.java:60)
	at executor.GestoreCondomini.getInstance(GestoreCondomini.java:38)
	at executor.Avvio.inizializzaAmICo(Avvio.java:39)
	at executor.Avvio.main(Avvio.java:28)
02-09 18:47:14 database: opening C:\Documents and Settings\Federico\workspace\AmICo\DB\DataBase4Amico
org.h2.jdbc.JdbcSQLException: Database may be already in use: Locked by another process. Possible solutions: close all other connection(s); use the server mode [90020-69]
	at org.h2.message.Message.getSQLException(Message.java:91)
	at org.h2.message.Message.getSQLException(Message.java:95)
	at org.h2.message.Message.getSQLException(Message.java:73)
	at org.h2.store.FileLock.error(FileLock.java:316)
	at org.h2.store.FileLock.lockFile(FileLock.java:178)
	at org.h2.store.FileLock.lock(FileLock.java:74)
	at org.h2.engine.Database.open(Database.java:467)
	at org.h2.engine.Database.<init>(Database.java:203)
	at org.h2.engine.Engine.openSession(Engine.java:55)
	at org.h2.engine.Engine.getSession(Engine.java:104)
	at org.h2.engine.Session.createSession(Session.java:203)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:976)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:957)
	at org.h2.Driver.connect(Driver.java:57)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at org.hibernate.connection.DriverManagerConnectionProvider.getConnection(DriverManagerConnectionProvider.java:110)
	at org.hibernate.jdbc.ConnectionManager.openConnection(ConnectionManager.java:423)
	at org.hibernate.jdbc.ConnectionManager.getConnection(ConnectionManager.java:144)
	at org.hibernate.jdbc.JDBCContext.connection(JDBCContext.java:119)
	at org.hibernate.transaction.JDBCTransaction.begin(JDBCTransaction.java:57)
	at org.hibernate.impl.SessionImpl.beginTransaction(SessionImpl.java:1326)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.hibernate.context.ThreadLocalSessionContext$TransactionProtectionWrapper.invoke(ThreadLocalSessionContext.java:301)
	at $Proxy0.beginTransaction(Unknown Source)
	at store.TuttiCondomini.recuperaCondomini(TuttiCondomini.java:35)
	at executor.GestoreCondomini.<init>(GestoreCondomini.java:60)
	at executor.GestoreCondomini.getInstance(GestoreCondomini.java:38)
	at executor.Avvio.inizializzaAmICo(Avvio.java:39)
	at executor.Avvio.main(Avvio.java:28)
02-10 20:56:51 database: opening C:\Documents and Settings\Federico\workspace\AmICo\DB\DataBase4Amico
org.h2.jdbc.JdbcSQLException: Database may be already in use: Locked by another process. Possible solutions: close all other connection(s); use the server mode [90020-69]
	at org.h2.message.Message.getSQLException(Message.java:91)
	at org.h2.message.Message.getSQLException(Message.java:95)
	at org.h2.message.Message.getSQLException(Message.java:73)
	at org.h2.store.FileLock.error(FileLock.java:316)
	at org.h2.store.FileLock.lockFile(FileLock.java:178)
	at org.h2.store.FileLock.lock(FileLock.java:74)
	at org.h2.engine.Database.open(Database.java:467)
	at org.h2.engine.Database.<init>(Database.java:203)
	at org.h2.engine.Engine.openSession(Engine.java:55)
	at org.h2.engine.Engine.getSession(Engine.java:104)
	at org.h2.engine.Session.createSession(Session.java:203)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:976)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:957)
	at org.h2.Driver.connect(Driver.java:57)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at org.hibernate.connection.DriverManagerConnectionProvider.getConnection(DriverManagerConnectionProvider.java:110)
	at org.hibernate.cfg.SettingsFactory.buildSettings(SettingsFactory.java:84)
	at org.hibernate.cfg.Configuration.buildSettings(Configuration.java:2073)
	at org.hibernate.cfg.Configuration.buildSessionFactory(Configuration.java:1298)
	at store.util.HibernateUtil.<clinit>(HibernateUtil.java:8)
	at store.TuttiCondomini.recuperaCondomini(TuttiCondomini.java:34)
	at executor.GestoreCondomini.<init>(GestoreCondomini.java:60)
	at executor.GestoreCondomini.getInstance(GestoreCondomini.java:38)
	at executor.Avvio.inizializzaAmICo(Avvio.java:39)
	at executor.Avvio.main(Avvio.java:28)
02-10 20:56:54 database: opening C:\Documents and Settings\Federico\workspace\AmICo\DB\DataBase4Amico
org.h2.jdbc.JdbcSQLException: Database may be already in use: Locked by another process. Possible solutions: close all other connection(s); use the server mode [90020-69]
	at org.h2.message.Message.getSQLException(Message.java:91)
	at org.h2.message.Message.getSQLException(Message.java:95)
	at org.h2.message.Message.getSQLException(Message.java:73)
	at org.h2.store.FileLock.error(FileLock.java:316)
	at org.h2.store.FileLock.lockFile(FileLock.java:178)
	at org.h2.store.FileLock.lock(FileLock.java:74)
	at org.h2.engine.Database.open(Database.java:467)
	at org.h2.engine.Database.<init>(Database.java:203)
	at org.h2.engine.Engine.openSession(Engine.java:55)
	at org.h2.engine.Engine.getSession(Engine.java:104)
	at org.h2.engine.Session.createSession(Session.java:203)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:976)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:957)
	at org.h2.Driver.connect(Driver.java:57)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at org.hibernate.connection.DriverManagerConnectionProvider.getConnection(DriverManagerConnectionProvider.java:110)
	at org.hibernate.jdbc.ConnectionManager.openConnection(ConnectionManager.java:423)
	at org.hibernate.jdbc.ConnectionManager.getConnection(ConnectionManager.java:144)
	at org.hibernate.jdbc.JDBCContext.connection(JDBCContext.java:119)
	at org.hibernate.transaction.JDBCTransaction.begin(JDBCTransaction.java:57)
	at org.hibernate.impl.SessionImpl.beginTransaction(SessionImpl.java:1326)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.hibernate.context.ThreadLocalSessionContext$TransactionProtectionWrapper.invoke(ThreadLocalSessionContext.java:301)
	at $Proxy0.beginTransaction(Unknown Source)
	at store.TuttiCondomini.recuperaCondomini(TuttiCondomini.java:35)
	at executor.GestoreCondomini.<init>(GestoreCondomini.java:60)
	at executor.GestoreCondomini.getInstance(GestoreCondomini.java:38)
	at executor.Avvio.inizializzaAmICo(Avvio.java:39)
	at executor.Avvio.main(Avvio.java:28)
02-11 15:13:36 database: opening C:\Documents and Settings\Federico\workspace\AmICo\DB\DataBase4Amico
org.h2.jdbc.JdbcSQLException: Database may be already in use: Locked by another process. Possible solutions: close all other connection(s); use the server mode [90020-69]
	at org.h2.message.Message.getSQLException(Message.java:91)
	at org.h2.message.Message.getSQLException(Message.java:95)
	at org.h2.message.Message.getSQLException(Message.java:73)
	at org.h2.store.FileLock.error(FileLock.java:316)
	at org.h2.store.FileLock.lockFile(FileLock.java:178)
	at org.h2.store.FileLock.lock(FileLock.java:74)
	at org.h2.engine.Database.open(Database.java:467)
	at org.h2.engine.Database.<init>(Database.java:203)
	at org.h2.engine.Engine.openSession(Engine.java:55)
	at org.h2.engine.Engine.getSession(Engine.java:104)
	at org.h2.engine.Session.createSession(Session.java:203)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:976)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:957)
	at org.h2.Driver.connect(Driver.java:57)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at org.hibernate.connection.DriverManagerConnectionProvider.getConnection(DriverManagerConnectionProvider.java:110)
	at org.hibernate.cfg.SettingsFactory.buildSettings(SettingsFactory.java:84)
	at org.hibernate.cfg.Configuration.buildSettings(Configuration.java:2073)
	at org.hibernate.cfg.Configuration.buildSessionFactory(Configuration.java:1298)
	at store.util.HibernateUtil.<clinit>(HibernateUtil.java:8)
	at store.TuttiCondomini.recuperaCondomini(TuttiCondomini.java:34)
	at executor.GestoreCondomini.<init>(GestoreCondomini.java:60)
	at executor.GestoreCondomini.getInstance(GestoreCondomini.java:38)
	at executor.Avvio.inizializzaAmICo(Avvio.java:39)
	at executor.Avvio.main(Avvio.java:28)
02-11 15:13:39 database: opening C:\Documents and Settings\Federico\workspace\AmICo\DB\DataBase4Amico
org.h2.jdbc.JdbcSQLException: Database may be already in use: Locked by another process. Possible solutions: close all other connection(s); use the server mode [90020-69]
	at org.h2.message.Message.getSQLException(Message.java:91)
	at org.h2.message.Message.getSQLException(Message.java:95)
	at org.h2.message.Message.getSQLException(Message.java:73)
	at org.h2.store.FileLock.error(FileLock.java:316)
	at org.h2.store.FileLock.lockFile(FileLock.java:178)
	at org.h2.store.FileLock.lock(FileLock.java:74)
	at org.h2.engine.Database.open(Database.java:467)
	at org.h2.engine.Database.<init>(Database.java:203)
	at org.h2.engine.Engine.openSession(Engine.java:55)
	at org.h2.engine.Engine.getSession(Engine.java:104)
	at org.h2.engine.Session.createSession(Session.java:203)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:976)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:957)
	at org.h2.Driver.connect(Driver.java:57)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at org.hibernate.connection.DriverManagerConnectionProvider.getConnection(DriverManagerConnectionProvider.java:110)
	at org.hibernate.jdbc.ConnectionManager.openConnection(ConnectionManager.java:423)
	at org.hibernate.jdbc.ConnectionManager.getConnection(ConnectionManager.java:144)
	at org.hibernate.jdbc.JDBCContext.connection(JDBCContext.java:119)
	at org.hibernate.transaction.JDBCTransaction.begin(JDBCTransaction.java:57)
	at org.hibernate.impl.SessionImpl.beginTransaction(SessionImpl.java:1326)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.hibernate.context.ThreadLocalSessionContext$TransactionProtectionWrapper.invoke(ThreadLocalSessionContext.java:301)
	at $Proxy0.beginTransaction(Unknown Source)
	at store.TuttiCondomini.recuperaCondomini(TuttiCondomini.java:35)
	at executor.GestoreCondomini.<init>(GestoreCondomini.java:60)
	at executor.GestoreCondomini.getInstance(GestoreCondomini.java:38)
	at executor.Avvio.inizializzaAmICo(Avvio.java:39)
	at executor.Avvio.main(Avvio.java:28)
02-11 15:28:41 database: opening C:\Documents and Settings\Federico\workspace\AmICo\DB\DataBase4Amico
org.h2.jdbc.JdbcSQLException: Database may be already in use: Locked by another process. Possible solutions: close all other connection(s); use the server mode [90020-69]
	at org.h2.message.Message.getSQLException(Message.java:91)
	at org.h2.message.Message.getSQLException(Message.java:95)
	at org.h2.message.Message.getSQLException(Message.java:73)
	at org.h2.store.FileLock.error(FileLock.java:316)
	at org.h2.store.FileLock.lockFile(FileLock.java:178)
	at org.h2.store.FileLock.lock(FileLock.java:74)
	at org.h2.engine.Database.open(Database.java:467)
	at org.h2.engine.Database.<init>(Database.java:203)
	at org.h2.engine.Engine.openSession(Engine.java:55)
	at org.h2.engine.Engine.getSession(Engine.java:104)
	at org.h2.engine.Session.createSession(Session.java:203)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:976)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:957)
	at org.h2.Driver.connect(Driver.java:57)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at org.hibernate.connection.DriverManagerConnectionProvider.getConnection(DriverManagerConnectionProvider.java:110)
	at org.hibernate.cfg.SettingsFactory.buildSettings(SettingsFactory.java:84)
	at org.hibernate.cfg.Configuration.buildSettings(Configuration.java:2073)
	at org.hibernate.cfg.Configuration.buildSessionFactory(Configuration.java:1298)
	at store.util.HibernateUtil.<clinit>(HibernateUtil.java:8)
	at store.TuttiCondomini.recuperaCondomini(TuttiCondomini.java:34)
	at executor.GestoreCondomini.<init>(GestoreCondomini.java:60)
	at executor.GestoreCondomini.getInstance(GestoreCondomini.java:38)
	at executor.Avvio.inizializzaAmICo(Avvio.java:39)
	at executor.Avvio.main(Avvio.java:28)
02-11 15:28:43 database: opening C:\Documents and Settings\Federico\workspace\AmICo\DB\DataBase4Amico
org.h2.jdbc.JdbcSQLException: Database may be already in use: Locked by another process. Possible solutions: close all other connection(s); use the server mode [90020-69]
	at org.h2.message.Message.getSQLException(Message.java:91)
	at org.h2.message.Message.getSQLException(Message.java:95)
	at org.h2.message.Message.getSQLException(Message.java:73)
	at org.h2.store.FileLock.error(FileLock.java:316)
	at org.h2.store.FileLock.lockFile(FileLock.java:178)
	at org.h2.store.FileLock.lock(FileLock.java:74)
	at org.h2.engine.Database.open(Database.java:467)
	at org.h2.engine.Database.<init>(Database.java:203)
	at org.h2.engine.Engine.openSession(Engine.java:55)
	at org.h2.engine.Engine.getSession(Engine.java:104)
	at org.h2.engine.Session.createSession(Session.java:203)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:976)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:957)
	at org.h2.Driver.connect(Driver.java:57)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at org.hibernate.connection.DriverManagerConnectionProvider.getConnection(DriverManagerConnectionProvider.java:110)
	at org.hibernate.jdbc.ConnectionManager.openConnection(ConnectionManager.java:423)
	at org.hibernate.jdbc.ConnectionManager.getConnection(ConnectionManager.java:144)
	at org.hibernate.jdbc.JDBCContext.connection(JDBCContext.java:119)
	at org.hibernate.transaction.JDBCTransaction.begin(JDBCTransaction.java:57)
	at org.hibernate.impl.SessionImpl.beginTransaction(SessionImpl.java:1326)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.hibernate.context.ThreadLocalSessionContext$TransactionProtectionWrapper.invoke(ThreadLocalSessionContext.java:301)
	at $Proxy0.beginTransaction(Unknown Source)
	at store.TuttiCondomini.recuperaCondomini(TuttiCondomini.java:35)
	at executor.GestoreCondomini.<init>(GestoreCondomini.java:60)
	at executor.GestoreCondomini.getInstance(GestoreCondomini.java:38)
	at executor.Avvio.inizializzaAmICo(Avvio.java:39)
	at executor.Avvio.main(Avvio.java:28)
02-11 16:57:26 database: opening C:\Documents and Settings\Federico\workspace\AmICo\DB\DataBase4Amico
org.h2.jdbc.JdbcSQLException: Database may be already in use: Locked by another process. Possible solutions: close all other connection(s); use the server mode [90020-69]
	at org.h2.message.Message.getSQLException(Message.java:91)
	at org.h2.message.Message.getSQLException(Message.java:95)
	at org.h2.message.Message.getSQLException(Message.java:73)
	at org.h2.store.FileLock.error(FileLock.java:316)
	at org.h2.store.FileLock.lockFile(FileLock.java:178)
	at org.h2.store.FileLock.lock(FileLock.java:74)
	at org.h2.engine.Database.open(Database.java:467)
	at org.h2.engine.Database.<init>(Database.java:203)
	at org.h2.engine.Engine.openSession(Engine.java:55)
	at org.h2.engine.Engine.getSession(Engine.java:104)
	at org.h2.engine.Session.createSession(Session.java:203)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:976)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:957)
	at org.h2.Driver.connect(Driver.java:57)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at org.hibernate.connection.DriverManagerConnectionProvider.getConnection(DriverManagerConnectionProvider.java:110)
	at org.hibernate.cfg.SettingsFactory.buildSettings(SettingsFactory.java:84)
	at org.hibernate.cfg.Configuration.buildSettings(Configuration.java:2073)
	at org.hibernate.cfg.Configuration.buildSessionFactory(Configuration.java:1298)
	at store.util.HibernateUtil.<clinit>(HibernateUtil.java:8)
	at store.TuttiCondomini.recuperaCondomini(TuttiCondomini.java:34)
	at executor.GestoreCondomini.<init>(GestoreCondomini.java:60)
	at executor.GestoreCondomini.getInstance(GestoreCondomini.java:38)
	at executor.Avvio.inizializzaAmICo(Avvio.java:39)
	at executor.Avvio.main(Avvio.java:28)
02-11 16:57:28 database: opening C:\Documents and Settings\Federico\workspace\AmICo\DB\DataBase4Amico
org.h2.jdbc.JdbcSQLException: Database may be already in use: Locked by another process. Possible solutions: close all other connection(s); use the server mode [90020-69]
	at org.h2.message.Message.getSQLException(Message.java:91)
	at org.h2.message.Message.getSQLException(Message.java:95)
	at org.h2.message.Message.getSQLException(Message.java:73)
	at org.h2.store.FileLock.error(FileLock.java:316)
	at org.h2.store.FileLock.lockFile(FileLock.java:178)
	at org.h2.store.FileLock.lock(FileLock.java:74)
	at org.h2.engine.Database.open(Database.java:467)
	at org.h2.engine.Database.<init>(Database.java:203)
	at org.h2.engine.Engine.openSession(Engine.java:55)
	at org.h2.engine.Engine.getSession(Engine.java:104)
	at org.h2.engine.Session.createSession(Session.java:203)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:976)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:957)
	at org.h2.Driver.connect(Driver.java:57)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at org.hibernate.connection.DriverManagerConnectionProvider.getConnection(DriverManagerConnectionProvider.java:110)
	at org.hibernate.jdbc.ConnectionManager.openConnection(ConnectionManager.java:423)
	at org.hibernate.jdbc.ConnectionManager.getConnection(ConnectionManager.java:144)
	at org.hibernate.jdbc.JDBCContext.connection(JDBCContext.java:119)
	at org.hibernate.transaction.JDBCTransaction.begin(JDBCTransaction.java:57)
	at org.hibernate.impl.SessionImpl.beginTransaction(SessionImpl.java:1326)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.hibernate.context.ThreadLocalSessionContext$TransactionProtectionWrapper.invoke(ThreadLocalSessionContext.java:301)
	at $Proxy0.beginTransaction(Unknown Source)
	at store.TuttiCondomini.recuperaCondomini(TuttiCondomini.java:35)
	at executor.GestoreCondomini.<init>(GestoreCondomini.java:60)
	at executor.GestoreCondomini.getInstance(GestoreCondomini.java:38)
	at executor.Avvio.inizializzaAmICo(Avvio.java:39)
	at executor.Avvio.main(Avvio.java:28)
02-14 15:25:35 jdbc[2]: SQLException
org.h2.jdbc.JdbcSQLException: Unique index or primary key violation: CONSTRAINT_INDEX_E86  ON PUBLIC.MOVIMENTO_CASSA(RELATIVO_A_VOCE) [23001-69]
	at org.h2.message.Message.getSQLException(Message.java:91)
	at org.h2.message.Message.getSQLException(Message.java:95)
	at org.h2.message.Message.getSQLException(Message.java:73)
	at org.h2.index.BaseIndex.getDuplicateKeyException(BaseIndex.java:146)
	at org.h2.index.BtreeLeaf.add(BtreeLeaf.java:66)
	at org.h2.index.BtreeIndex.add(BtreeIndex.java:176)
	at org.h2.table.TableData.addRow(TableData.java:97)
	at org.h2.command.dml.Insert.update(Insert.java:94)
	at org.h2.command.CommandContainer.update(CommandContainer.java:69)
	at org.h2.command.Command.executeUpdate(Command.java:197)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:132)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:121)
	at org.hibernate.id.IdentityGenerator$GetGeneratedKeysDelegate.executeAndExtract(IdentityGenerator.java:73)
	at org.hibernate.id.insert.AbstractReturningDelegate.performInsert(AbstractReturningDelegate.java:33)
	at org.hibernate.persister.entity.AbstractEntityPersister.insert(AbstractEntityPersister.java:2163)
	at org.hibernate.persister.entity.AbstractEntityPersister.insert(AbstractEntityPersister.java:2643)
	at org.hibernate.action.EntityIdentityInsertAction.execute(EntityIdentityInsertAction.java:51)
	at org.hibernate.engine.ActionQueue.execute(ActionQueue.java:279)
	at org.hibernate.event.def.AbstractSaveEventListener.performSaveOrReplicate(AbstractSaveEventListener.java:298)
	at org.hibernate.event.def.AbstractSaveEventListener.performSave(AbstractSaveEventListener.java:181)
	at org.hibernate.event.def.AbstractSaveEventListener.saveWithGeneratedId(AbstractSaveEventListener.java:107)
	at org.hibernate.event.def.DefaultSaveOrUpdateEventListener.saveWithGeneratedOrRequestedId(DefaultSaveOrUpdateEventListener.java:187)
	at org.hibernate.event.def.DefaultSaveOrUpdateEventListener.entityIsTransient(DefaultSaveOrUpdateEventListener.java:172)
	at org.hibernate.event.def.DefaultSaveOrUpdateEventListener.performSaveOrUpdate(DefaultSaveOrUpdateEventListener.java:94)
	at org.hibernate.event.def.DefaultSaveOrUpdateEventListener.onSaveOrUpdate(DefaultSaveOrUpdateEventListener.java:70)
	at org.hibernate.impl.SessionImpl.fireSaveOrUpdate(SessionImpl.java:507)
	at org.hibernate.impl.SessionImpl.saveOrUpdate(SessionImpl.java:499)
	at org.hibernate.engine.CascadingAction$5.cascade(CascadingAction.java:218)
	at org.hibernate.engine.Cascade.cascadeToOne(Cascade.java:268)
	at org.hibernate.engine.Cascade.cascadeAssociation(Cascade.java:216)
	at org.hibernate.engine.Cascade.cascadeProperty(Cascade.java:169)
	at org.hibernate.engine.Cascade.cascadeCollectionElements(Cascade.java:296)
	at org.hibernate.engine.Cascade.cascadeCollection(Cascade.java:242)
	at org.hibernate.engine.Cascade.cascadeAssociation(Cascade.java:219)
	at org.hibernate.engine.Cascade.cascadeProperty(Cascade.java:169)
	at org.hibernate.engine.Cascade.cascade(Cascade.java:130)
	at org.hibernate.engine.Cascade.cascade(Cascade.java:97)
	at org.hibernate.event.def.DefaultSaveOrUpdateEventListener.cascadeOnUpdate(DefaultSaveOrUpdateEventListener.java:357)
	at org.hibernate.event.def.DefaultSaveOrUpdateEventListener.performUpdate(DefaultSaveOrUpdateEventListener.java:329)
	at org.hibernate.event.def.DefaultSaveOrUpdateEventListener.entityIsDetached(DefaultSaveOrUpdateEventListener.java:223)
	at org.hibernate.event.def.DefaultUpdateEventListener.performSaveOrUpdate(DefaultUpdateEventListener.java:33)
	at org.hibernate.event.def.DefaultSaveOrUpdateEventListener.onSaveOrUpdate(DefaultSaveOrUpdateEventListener.java:70)
	at org.hibernate.impl.SessionImpl.fireUpdate(SessionImpl.java:564)
	at org.hibernate.impl.SessionImpl.update(SessionImpl.java:552)
	at org.hibernate.impl.SessionImpl.update(SessionImpl.java:544)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.hibernate.context.ThreadLocalSessionContext$TransactionProtectionWrapper.invoke(ThreadLocalSessionContext.java:301)
	at $Proxy0.update(Unknown Source)
	at store.POJO.Cassa.registraMovimentoCassa(Cassa.java:40)
	at executor.GestoreCassa.procedi(GestoreCassa.java:144)
	at boundary.AccedereCassa.ok(AccedereCassa.java:164)
	at boundary.AccedereCassa.aggiornaProspetto(AccedereCassa.java:73)
	at executor.GestoreCassa.passaVoceBilancio(GestoreCassa.java:72)
	at boundary.AccedereCassa.passaVoceBilancio(AccedereCassa.java:170)
	at boundary.RegistraMovimento.bConfermaMouseMouseClicked(RegistraMovimento.java:118)
	at boundary.RegistraMovimento.access$1(RegistraMovimento.java:96)
	at boundary.RegistraMovimento$2.mouseClicked(RegistraMovimento.java:206)
	at java.awt.AWTEventMulticaster.mouseClicked(Unknown Source)
	at java.awt.Component.processMouseEvent(Unknown Source)
	at javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
02-14 15:26:03 jdbc[2]: SQLException
org.h2.jdbc.JdbcSQLException: Unique index or primary key violation: CONSTRAINT_INDEX_E86  ON PUBLIC.MOVIMENTO_CASSA(RELATIVO_A_VOCE) [23001-69]
	at org.h2.message.Message.getSQLException(Message.java:91)
	at org.h2.message.Message.getSQLException(Message.java:95)
	at org.h2.message.Message.getSQLException(Message.java:73)
	at org.h2.index.BaseIndex.getDuplicateKeyException(BaseIndex.java:146)
	at org.h2.index.BtreeLeaf.add(BtreeLeaf.java:66)
	at org.h2.index.BtreeIndex.add(BtreeIndex.java:176)
	at org.h2.table.TableData.addRow(TableData.java:97)
	at org.h2.command.dml.Insert.update(Insert.java:94)
	at org.h2.command.CommandContainer.update(CommandContainer.java:69)
	at org.h2.command.Command.executeUpdate(Command.java:197)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:132)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:121)
	at org.hibernate.id.IdentityGenerator$GetGeneratedKeysDelegate.executeAndExtract(IdentityGenerator.java:73)
	at org.hibernate.id.insert.AbstractReturningDelegate.performInsert(AbstractReturningDelegate.java:33)
	at org.hibernate.persister.entity.AbstractEntityPersister.insert(AbstractEntityPersister.java:2163)
	at org.hibernate.persister.entity.AbstractEntityPersister.insert(AbstractEntityPersister.java:2643)
	at org.hibernate.action.EntityIdentityInsertAction.execute(EntityIdentityInsertAction.java:51)
	at org.hibernate.engine.ActionQueue.execute(ActionQueue.java:279)
	at org.hibernate.event.def.AbstractSaveEventListener.performSaveOrReplicate(AbstractSaveEventListener.java:298)
	at org.hibernate.event.def.AbstractSaveEventListener.performSave(AbstractSaveEventListener.java:181)
	at org.hibernate.event.def.AbstractSaveEventListener.saveWithGeneratedId(AbstractSaveEventListener.java:107)
	at org.hibernate.event.def.DefaultSaveOrUpdateEventListener.saveWithGeneratedOrRequestedId(DefaultSaveOrUpdateEventListener.java:187)
	at org.hibernate.event.def.DefaultSaveOrUpdateEventListener.entityIsTransient(DefaultSaveOrUpdateEventListener.java:172)
	at org.hibernate.event.def.DefaultSaveOrUpdateEventListener.performSaveOrUpdate(DefaultSaveOrUpdateEventListener.java:94)
	at org.hibernate.event.def.DefaultSaveOrUpdateEventListener.onSaveOrUpdate(DefaultSaveOrUpdateEventListener.java:70)
	at org.hibernate.impl.SessionImpl.fireSaveOrUpdate(SessionImpl.java:507)
	at org.hibernate.impl.SessionImpl.saveOrUpdate(SessionImpl.java:499)
	at org.hibernate.engine.CascadingAction$5.cascade(CascadingAction.java:218)
	at org.hibernate.engine.Cascade.cascadeToOne(Cascade.java:268)
	at org.hibernate.engine.Cascade.cascadeAssociation(Cascade.java:216)
	at org.hibernate.engine.Cascade.cascadeProperty(Cascade.java:169)
	at org.hibernate.engine.Cascade.cascadeCollectionElements(Cascade.java:296)
	at org.hibernate.engine.Cascade.cascadeCollection(Cascade.java:242)
	at org.hibernate.engine.Cascade.cascadeAssociation(Cascade.java:219)
	at org.hibernate.engine.Cascade.cascadeProperty(Cascade.java:169)
	at org.hibernate.engine.Cascade.cascade(Cascade.java:130)
	at org.hibernate.engine.Cascade.cascade(Cascade.java:97)
	at org.hibernate.event.def.DefaultSaveOrUpdateEventListener.cascadeOnUpdate(DefaultSaveOrUpdateEventListener.java:357)
	at org.hibernate.event.def.DefaultSaveOrUpdateEventListener.performUpdate(DefaultSaveOrUpdateEventListener.java:329)
	at org.hibernate.event.def.DefaultSaveOrUpdateEventListener.entityIsDetached(DefaultSaveOrUpdateEventListener.java:223)
	at org.hibernate.event.def.DefaultUpdateEventListener.performSaveOrUpdate(DefaultUpdateEventListener.java:33)
	at org.hibernate.event.def.DefaultSaveOrUpdateEventListener.onSaveOrUpdate(DefaultSaveOrUpdateEventListener.java:70)
	at org.hibernate.impl.SessionImpl.fireUpdate(SessionImpl.java:564)
	at org.hibernate.impl.SessionImpl.update(SessionImpl.java:552)
	at org.hibernate.impl.SessionImpl.update(SessionImpl.java:544)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.hibernate.context.ThreadLocalSessionContext$TransactionProtectionWrapper.invoke(ThreadLocalSessionContext.java:301)
	at $Proxy0.update(Unknown Source)
	at store.POJO.Cassa.registraMovimentoCassa(Cassa.java:40)
	at executor.GestoreCassa.procedi(GestoreCassa.java:144)
	at boundary.AccedereCassa.ok(AccedereCassa.java:164)
	at boundary.AccedereCassa.aggiornaProspetto(AccedereCassa.java:73)
	at executor.GestoreCassa.passaVoceBilancio(GestoreCassa.java:72)
	at boundary.AccedereCassa.passaVoceBilancio(AccedereCassa.java:170)
	at boundary.RegistraMovimento.bConfermaMouseMouseClicked(RegistraMovimento.java:118)
	at boundary.RegistraMovimento.access$1(RegistraMovimento.java:96)
	at boundary.RegistraMovimento$2.mouseClicked(RegistraMovimento.java:206)
	at java.awt.AWTEventMulticaster.mouseClicked(Unknown Source)
	at java.awt.Component.processMouseEvent(Unknown Source)
	at javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
02-14 15:47:28 database: opening C:\Documents and Settings\Federico\workspace\AmICo\DB\DataBase4Amico
org.h2.jdbc.JdbcSQLException: Database may be already in use: Locked by another process. Possible solutions: close all other connection(s); use the server mode [90020-69]
	at org.h2.message.Message.getSQLException(Message.java:91)
	at org.h2.message.Message.getSQLException(Message.java:95)
	at org.h2.message.Message.getSQLException(Message.java:73)
	at org.h2.store.FileLock.error(FileLock.java:316)
	at org.h2.store.FileLock.lockFile(FileLock.java:178)
	at org.h2.store.FileLock.lock(FileLock.java:74)
	at org.h2.engine.Database.open(Database.java:467)
	at org.h2.engine.Database.<init>(Database.java:203)
	at org.h2.engine.Engine.openSession(Engine.java:55)
	at org.h2.engine.Engine.getSession(Engine.java:104)
	at org.h2.engine.Session.createSession(Session.java:203)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:976)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:957)
	at org.h2.Driver.connect(Driver.java:57)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at org.hibernate.connection.DriverManagerConnectionProvider.getConnection(DriverManagerConnectionProvider.java:110)
	at org.hibernate.cfg.SettingsFactory.buildSettings(SettingsFactory.java:84)
	at org.hibernate.cfg.Configuration.buildSettings(Configuration.java:2073)
	at org.hibernate.cfg.Configuration.buildSessionFactory(Configuration.java:1298)
	at store.util.HibernateUtil.<clinit>(HibernateUtil.java:8)
	at store.TuttiCondomini.recuperaCondomini(TuttiCondomini.java:34)
	at executor.GestoreCondomini.<init>(GestoreCondomini.java:60)
	at executor.GestoreCondomini.getInstance(GestoreCondomini.java:38)
	at executor.Avvio.inizializzaAmICo(Avvio.java:39)
	at executor.Avvio.main(Avvio.java:28)
02-14 15:47:30 database: opening C:\Documents and Settings\Federico\workspace\AmICo\DB\DataBase4Amico
org.h2.jdbc.JdbcSQLException: Database may be already in use: Locked by another process. Possible solutions: close all other connection(s); use the server mode [90020-69]
	at org.h2.message.Message.getSQLException(Message.java:91)
	at org.h2.message.Message.getSQLException(Message.java:95)
	at org.h2.message.Message.getSQLException(Message.java:73)
	at org.h2.store.FileLock.error(FileLock.java:316)
	at org.h2.store.FileLock.lockFile(FileLock.java:178)
	at org.h2.store.FileLock.lock(FileLock.java:74)
	at org.h2.engine.Database.open(Database.java:467)
	at org.h2.engine.Database.<init>(Database.java:203)
	at org.h2.engine.Engine.openSession(Engine.java:55)
	at org.h2.engine.Engine.getSession(Engine.java:104)
	at org.h2.engine.Session.createSession(Session.java:203)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:976)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:957)
	at org.h2.Driver.connect(Driver.java:57)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at org.hibernate.connection.DriverManagerConnectionProvider.getConnection(DriverManagerConnectionProvider.java:110)
	at org.hibernate.jdbc.ConnectionManager.openConnection(ConnectionManager.java:423)
	at org.hibernate.jdbc.ConnectionManager.getConnection(ConnectionManager.java:144)
	at org.hibernate.jdbc.JDBCContext.connection(JDBCContext.java:119)
	at org.hibernate.transaction.JDBCTransaction.begin(JDBCTransaction.java:57)
	at org.hibernate.impl.SessionImpl.beginTransaction(SessionImpl.java:1326)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.hibernate.context.ThreadLocalSessionContext$TransactionProtectionWrapper.invoke(ThreadLocalSessionContext.java:301)
	at $Proxy0.beginTransaction(Unknown Source)
	at store.TuttiCondomini.recuperaCondomini(TuttiCondomini.java:35)
	at executor.GestoreCondomini.<init>(GestoreCondomini.java:60)
	at executor.GestoreCondomini.getInstance(GestoreCondomini.java:38)
	at executor.Avvio.inizializzaAmICo(Avvio.java:39)
	at executor.Avvio.main(Avvio.java:28)
02-14 16:52:54 jdbc[2]: SQLException
org.h2.jdbc.JdbcSQLException: Column VOCI0_.CONTABILIZZATA not found; SQL statement:
select voci0_.BILANCIO_ID as BILANCIO8_1_, voci0_.VOCE_BIL_ID as VOCE1_1_, voci0_.VOCE_BIL_ID as VOCE1_11_0_, voci0_.titolo as titolo11_0_, voci0_.tipo as tipo11_0_, voci0_.descrizione as descrizi4_11_0_, voci0_.euro as euro11_0_, voci0_.dataPrevista as dataPrev6_11_0_, voci0_.dataContabilitazione as dataCont7_11_0_, voci0_.BILANCIO_ID as BILANCIO8_11_0_, voci0_.CONTABILIZZATA as CONTABIL9_11_0_, voci0_.RIPARTIZIONE as RIPARTI10_11_0_ from VOCE_BILANCIO voci0_ where voci0_.BILANCIO_ID=? [42122-69]
	at org.h2.message.Message.getSQLException(Message.java:91)
	at org.h2.message.Message.getSQLException(Message.java:95)
	at org.h2.message.Message.getSQLException(Message.java:73)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:124)
	at org.h2.expression.Alias.optimize(Alias.java:47)
	at org.h2.command.dml.Select.prepare(Select.java:680)
	at org.h2.command.Parser.prepareCommand(Parser.java:230)
	at org.h2.engine.Session.prepareLocal(Session.java:236)
	at org.h2.engine.Session.prepareCommand(Session.java:218)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1020)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:1217)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:163)
	at org.hibernate.jdbc.AbstractBatcher.getPreparedStatement(AbstractBatcher.java:505)
	at org.hibernate.jdbc.AbstractBatcher.getPreparedStatement(AbstractBatcher.java:423)
	at org.hibernate.jdbc.AbstractBatcher.prepareQueryStatement(AbstractBatcher.java:139)
	at org.hibernate.loader.Loader.prepareQueryStatement(Loader.java:1547)
	at org.hibernate.loader.Loader.doQuery(Loader.java:673)
	at org.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Loader.java:236)
	at org.hibernate.loader.Loader.loadCollection(Loader.java:1994)
	at org.hibernate.loader.collection.CollectionLoader.initialize(CollectionLoader.java:36)
	at org.hibernate.persister.collection.AbstractCollectionPersister.initialize(AbstractCollectionPersister.java:565)
	at org.hibernate.event.def.DefaultInitializeCollectionEventListener.onInitializeCollection(DefaultInitializeCollectionEventListener.java:63)
	at org.hibernate.impl.SessionImpl.initializeCollection(SessionImpl.java:1716)
	at org.hibernate.collection.AbstractPersistentCollection.initialize(AbstractPersistentCollection.java:344)
	at org.hibernate.collection.AbstractPersistentCollection.read(AbstractPersistentCollection.java:86)
	at org.hibernate.collection.PersistentSet.hashCode(PersistentSet.java:411)
	at store.POJO.Bilancio.hashCode(Bilancio.java:206)
	at java.util.HashMap.put(Unknown Source)
	at java.util.HashSet.add(Unknown Source)
	at java.util.AbstractCollection.addAll(Unknown Source)
	at org.hibernate.collection.PersistentSet.endRead(PersistentSet.java:329)
	at org.hibernate.engine.loading.CollectionLoadContext.endLoadingCollection(CollectionLoadContext.java:240)
	at org.hibernate.engine.loading.CollectionLoadContext.endLoadingCollections(CollectionLoadContext.java:222)
	at org.hibernate.engine.loading.CollectionLoadContext.endLoadingCollections(CollectionLoadContext.java:195)
	at org.hibernate.loader.Loader.endCollectionLoad(Loader.java:877)
	at org.hibernate.loader.Loader.initializeEntitiesAndCollections(Loader.java:865)
	at org.hibernate.loader.Loader.doQuery(Loader.java:729)
	at org.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Loader.java:236)
	at org.hibernate.loader.Loader.loadCollection(Loader.java:1994)
	at org.hibernate.loader.collection.CollectionLoader.initialize(CollectionLoader.java:36)
	at org.hibernate.persister.collection.AbstractCollectionPersister.initialize(AbstractCollectionPersister.java:565)
	at org.hibernate.event.def.DefaultInitializeCollectionEventListener.onInitializeCollection(DefaultInitializeCollectionEventListener.java:63)
	at org.hibernate.impl.SessionImpl.initializeCollection(SessionImpl.java:1716)
	at org.hibernate.collection.AbstractPersistentCollection.forceInitialization(AbstractPersistentCollection.java:454)
	at org.hibernate.engine.StatefulPersistenceContext.initializeNonLazyCollections(StatefulPersistenceContext.java:844)
	at org.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Loader.java:241)
	at org.hibernate.loader.Loader.doList(Loader.java:2213)
	at org.hibernate.loader.Loader.listIgnoreQueryCache(Loader.java:2104)
	at org.hibernate.loader.Loader.list(Loader.java:2099)
	at org.hibernate.loader.hql.QueryLoader.list(QueryLoader.java:378)
	at org.hibernate.hql.ast.QueryTranslatorImpl.list(QueryTranslatorImpl.java:338)
	at org.hibernate.engine.query.HQLQueryPlan.performList(HQLQueryPlan.java:172)
	at org.hibernate.impl.SessionImpl.list(SessionImpl.java:1121)
	at org.hibernate.impl.QueryImpl.list(QueryImpl.java:79)
	at store.TuttiCondomini.recuperaCondomini(TuttiCondomini.java:37)
	at executor.GestoreCondomini.<init>(GestoreCondomini.java:60)
	at executor.GestoreCondomini.getInstance(GestoreCondomini.java:38)
	at executor.Avvio.inizializzaAmICo(Avvio.java:39)
	at executor.Avvio.main(Avvio.java:28)
02-14 16:53:04 jdbc[2]: SQLException
org.h2.jdbc.JdbcSQLException: Column VOCI0_.CONTABILIZZATA not found; SQL statement:
select voci0_.BILANCIO_ID as BILANCIO8_1_, voci0_.VOCE_BIL_ID as VOCE1_1_, voci0_.VOCE_BIL_ID as VOCE1_11_0_, voci0_.titolo as titolo11_0_, voci0_.tipo as tipo11_0_, voci0_.descrizione as descrizi4_11_0_, voci0_.euro as euro11_0_, voci0_.dataPrevista as dataPrev6_11_0_, voci0_.dataContabilitazione as dataCont7_11_0_, voci0_.BILANCIO_ID as BILANCIO8_11_0_, voci0_.CONTABILIZZATA as CONTABIL9_11_0_, voci0_.RIPARTIZIONE as RIPARTI10_11_0_ from VOCE_BILANCIO voci0_ where voci0_.BILANCIO_ID=? [42122-69]
	at org.h2.message.Message.getSQLException(Message.java:91)
	at org.h2.message.Message.getSQLException(Message.java:95)
	at org.h2.message.Message.getSQLException(Message.java:73)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:124)
	at org.h2.expression.Alias.optimize(Alias.java:47)
	at org.h2.command.dml.Select.prepare(Select.java:680)
	at org.h2.command.Parser.prepareCommand(Parser.java:230)
	at org.h2.engine.Session.prepareLocal(Session.java:236)
	at org.h2.engine.Session.prepareCommand(Session.java:218)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1020)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:1217)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:163)
	at org.hibernate.jdbc.AbstractBatcher.getPreparedStatement(AbstractBatcher.java:505)
	at org.hibernate.jdbc.AbstractBatcher.getPreparedStatement(AbstractBatcher.java:423)
	at org.hibernate.jdbc.AbstractBatcher.prepareQueryStatement(AbstractBatcher.java:139)
	at org.hibernate.loader.Loader.prepareQueryStatement(Loader.java:1547)
	at org.hibernate.loader.Loader.doQuery(Loader.java:673)
	at org.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Loader.java:236)
	at org.hibernate.loader.Loader.loadCollection(Loader.java:1994)
	at org.hibernate.loader.collection.CollectionLoader.initialize(CollectionLoader.java:36)
	at org.hibernate.persister.collection.AbstractCollectionPersister.initialize(AbstractCollectionPersister.java:565)
	at org.hibernate.event.def.DefaultInitializeCollectionEventListener.onInitializeCollection(DefaultInitializeCollectionEventListener.java:63)
	at org.hibernate.impl.SessionImpl.initializeCollection(SessionImpl.java:1716)
	at org.hibernate.collection.AbstractPersistentCollection.initialize(AbstractPersistentCollection.java:344)
	at org.hibernate.collection.AbstractPersistentCollection.read(AbstractPersistentCollection.java:86)
	at org.hibernate.collection.PersistentSet.hashCode(PersistentSet.java:411)
	at store.POJO.Bilancio.hashCode(Bilancio.java:206)
	at java.util.HashMap.put(Unknown Source)
	at java.util.HashSet.add(Unknown Source)
	at java.util.AbstractCollection.addAll(Unknown Source)
	at org.hibernate.collection.PersistentSet.endRead(PersistentSet.java:329)
	at org.hibernate.engine.loading.CollectionLoadContext.endLoadingCollection(CollectionLoadContext.java:240)
	at org.hibernate.engine.loading.CollectionLoadContext.endLoadingCollections(CollectionLoadContext.java:222)
	at org.hibernate.engine.loading.CollectionLoadContext.endLoadingCollections(CollectionLoadContext.java:195)
	at org.hibernate.loader.Loader.endCollectionLoad(Loader.java:877)
	at org.hibernate.loader.Loader.initializeEntitiesAndCollections(Loader.java:865)
	at org.hibernate.loader.Loader.doQuery(Loader.java:729)
	at org.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Loader.java:236)
	at org.hibernate.loader.Loader.loadCollection(Loader.java:1994)
	at org.hibernate.loader.collection.CollectionLoader.initialize(CollectionLoader.java:36)
	at org.hibernate.persister.collection.AbstractCollectionPersister.initialize(AbstractCollectionPersister.java:565)
	at org.hibernate.event.def.DefaultInitializeCollectionEventListener.onInitializeCollection(DefaultInitializeCollectionEventListener.java:63)
	at org.hibernate.impl.SessionImpl.initializeCollection(SessionImpl.java:1716)
	at org.hibernate.collection.AbstractPersistentCollection.forceInitialization(AbstractPersistentCollection.java:454)
	at org.hibernate.engine.StatefulPersistenceContext.initializeNonLazyCollections(StatefulPersistenceContext.java:844)
	at org.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Loader.java:241)
	at org.hibernate.loader.Loader.doList(Loader.java:2213)
	at org.hibernate.loader.Loader.listIgnoreQueryCache(Loader.java:2104)
	at org.hibernate.loader.Loader.list(Loader.java:2099)
	at org.hibernate.loader.hql.QueryLoader.list(QueryLoader.java:378)
	at org.hibernate.hql.ast.QueryTranslatorImpl.list(QueryTranslatorImpl.java:338)
	at org.hibernate.engine.query.HQLQueryPlan.performList(HQLQueryPlan.java:172)
	at org.hibernate.impl.SessionImpl.list(SessionImpl.java:1121)
	at org.hibernate.impl.QueryImpl.list(QueryImpl.java:79)
	at store.TuttiCondomini.recuperaCondomini(TuttiCondomini.java:37)
	at executor.GestoreCondomini.<init>(GestoreCondomini.java:60)
	at executor.GestoreCondomini.getInstance(GestoreCondomini.java:38)
	at executor.Avvio.inizializzaAmICo(Avvio.java:39)
	at executor.Avvio.main(Avvio.java:28)
02-14 16:53:33 jdbc[2]: SQLException
org.h2.jdbc.JdbcSQLException: Constraint FKB7FEE67B96B1EC9F not found [90057-69]
	at org.h2.message.Message.getSQLException(Message.java:91)
	at org.h2.message.Message.getSQLException(Message.java:95)
	at org.h2.message.Message.getSQLException(Message.java:73)
	at org.h2.schema.Schema.getConstraint(Schema.java:260)
	at org.h2.command.ddl.AlterTableDropConstraint.update(AlterTableDropConstraint.java:33)
	at org.h2.command.CommandContainer.update(CommandContainer.java:69)
	at org.h2.command.Command.executeUpdate(Command.java:197)
	at org.h2.jdbc.JdbcStatement.executeUpdate(JdbcStatement.java:108)
	at org.hibernate.tool.hbm2ddl.SchemaExport.execute(SchemaExport.java:308)
	at org.hibernate.tool.hbm2ddl.SchemaExport.drop(SchemaExport.java:284)
	at org.hibernate.tool.hbm2ddl.SchemaExport.execute(SchemaExport.java:186)
	at org.hibernate.tool.hbm2ddl.SchemaExport.create(SchemaExport.java:133)
	at org.hibernate.impl.SessionFactoryImpl.<init>(SessionFactoryImpl.java:311)
	at org.hibernate.cfg.Configuration.buildSessionFactory(Configuration.java:1300)
	at store.util.HibernateUtil.<clinit>(HibernateUtil.java:8)
	at store.TuttiCondomini.recuperaCondomini(TuttiCondomini.java:34)
	at executor.GestoreCondomini.<init>(GestoreCondomini.java:60)
	at executor.GestoreCondomini.getInstance(GestoreCondomini.java:38)
	at executor.Avvio.inizializzaAmICo(Avvio.java:39)
	at executor.Avvio.main(Avvio.java:28)
02-14 16:57:50 database: opening C:\Documents and Settings\Federico\workspace\AmICo\DB\DataBase4Amico
org.h2.jdbc.JdbcSQLException: Database may be already in use: Locked by another process. Possible solutions: close all other connection(s); use the server mode [90020-69]
	at org.h2.message.Message.getSQLException(Message.java:91)
	at org.h2.message.Message.getSQLException(Message.java:95)
	at org.h2.message.Message.getSQLException(Message.java:73)
	at org.h2.store.FileLock.error(FileLock.java:316)
	at org.h2.store.FileLock.lockFile(FileLock.java:178)
	at org.h2.store.FileLock.lock(FileLock.java:74)
	at org.h2.engine.Database.open(Database.java:467)
	at org.h2.engine.Database.<init>(Database.java:203)
	at org.h2.engine.Engine.openSession(Engine.java:55)
	at org.h2.engine.Engine.getSession(Engine.java:104)
	at org.h2.engine.Session.createSession(Session.java:203)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:976)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:957)
	at org.h2.Driver.connect(Driver.java:57)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at org.hibernate.connection.DriverManagerConnectionProvider.getConnection(DriverManagerConnectionProvider.java:110)
	at org.hibernate.cfg.SettingsFactory.buildSettings(SettingsFactory.java:84)
	at org.hibernate.cfg.Configuration.buildSettings(Configuration.java:2073)
	at org.hibernate.cfg.Configuration.buildSessionFactory(Configuration.java:1298)
	at store.util.HibernateUtil.<clinit>(HibernateUtil.java:8)
	at store.TuttiCondomini.recuperaCondomini(TuttiCondomini.java:34)
	at executor.GestoreCondomini.<init>(GestoreCondomini.java:60)
	at executor.GestoreCondomini.getInstance(GestoreCondomini.java:38)
	at executor.Avvio.inizializzaAmICo(Avvio.java:39)
	at executor.Avvio.main(Avvio.java:28)
02-14 16:57:52 database: opening C:\Documents and Settings\Federico\workspace\AmICo\DB\DataBase4Amico
org.h2.jdbc.JdbcSQLException: Database may be already in use: Locked by another process. Possible solutions: close all other connection(s); use the server mode [90020-69]
	at org.h2.message.Message.getSQLException(Message.java:91)
	at org.h2.message.Message.getSQLException(Message.java:95)
	at org.h2.message.Message.getSQLException(Message.java:73)
	at org.h2.store.FileLock.error(FileLock.java:316)
	at org.h2.store.FileLock.lockFile(FileLock.java:178)
	at org.h2.store.FileLock.lock(FileLock.java:74)
	at org.h2.engine.Database.open(Database.java:467)
	at org.h2.engine.Database.<init>(Database.java:203)
	at org.h2.engine.Engine.openSession(Engine.java:55)
	at org.h2.engine.Engine.getSession(Engine.java:104)
	at org.h2.engine.Session.createSession(Session.java:203)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:976)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:957)
	at org.h2.Driver.connect(Driver.java:57)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at org.hibernate.connection.DriverManagerConnectionProvider.getConnection(DriverManagerConnectionProvider.java:110)
	at org.hibernate.tool.hbm2ddl.SuppliedConnectionProviderConnectionHelper.prepare(SuppliedConnectionProviderConnectionHelper.java:27)
	at org.hibernate.tool.hbm2ddl.SchemaExport.execute(SchemaExport.java:180)
	at org.hibernate.tool.hbm2ddl.SchemaExport.create(SchemaExport.java:133)
	at org.hibernate.impl.SessionFactoryImpl.<init>(SessionFactoryImpl.java:311)
	at org.hibernate.cfg.Configuration.buildSessionFactory(Configuration.java:1300)
	at store.util.HibernateUtil.<clinit>(HibernateUtil.java:8)
	at store.TuttiCondomini.recuperaCondomini(TuttiCondomini.java:34)
	at executor.GestoreCondomini.<init>(GestoreCondomini.java:60)
	at executor.GestoreCondomini.getInstance(GestoreCondomini.java:38)
	at executor.Avvio.inizializzaAmICo(Avvio.java:39)
	at executor.Avvio.main(Avvio.java:28)
02-14 16:57:54 database: opening C:\Documents and Settings\Federico\workspace\AmICo\DB\DataBase4Amico
org.h2.jdbc.JdbcSQLException: Database may be already in use: Locked by another process. Possible solutions: close all other connection(s); use the server mode [90020-69]
	at org.h2.message.Message.getSQLException(Message.java:91)
	at org.h2.message.Message.getSQLException(Message.java:95)
	at org.h2.message.Message.getSQLException(Message.java:73)
	at org.h2.store.FileLock.error(FileLock.java:316)
	at org.h2.store.FileLock.lockFile(FileLock.java:178)
	at org.h2.store.FileLock.lock(FileLock.java:74)
	at org.h2.engine.Database.open(Database.java:467)
	at org.h2.engine.Database.<init>(Database.java:203)
	at org.h2.engine.Engine.openSession(Engine.java:55)
	at org.h2.engine.Engine.getSession(Engine.java:104)
	at org.h2.engine.Session.createSession(Session.java:203)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:976)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:957)
	at org.h2.Driver.connect(Driver.java:57)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at org.hibernate.connection.DriverManagerConnectionProvider.getConnection(DriverManagerConnectionProvider.java:110)
	at org.hibernate.jdbc.ConnectionManager.openConnection(ConnectionManager.java:423)
	at org.hibernate.jdbc.ConnectionManager.getConnection(ConnectionManager.java:144)
	at org.hibernate.jdbc.JDBCContext.connection(JDBCContext.java:119)
	at org.hibernate.transaction.JDBCTransaction.begin(JDBCTransaction.java:57)
	at org.hibernate.impl.SessionImpl.beginTransaction(SessionImpl.java:1326)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.hibernate.context.ThreadLocalSessionContext$TransactionProtectionWrapper.invoke(ThreadLocalSessionContext.java:301)
	at $Proxy0.beginTransaction(Unknown Source)
	at store.TuttiCondomini.recuperaCondomini(TuttiCondomini.java:35)
	at executor.GestoreCondomini.<init>(GestoreCondomini.java:60)
	at executor.GestoreCondomini.getInstance(GestoreCondomini.java:38)
	at executor.Avvio.inizializzaAmICo(Avvio.java:39)
	at executor.Avvio.main(Avvio.java:28)
02-15 17:06:19 database: opening C:\Documents and Settings\Federico\workspace\AmICo\DB\DataBase4Amico
org.h2.jdbc.JdbcSQLException: Database may be already in use: Locked by another process. Possible solutions: close all other connection(s); use the server mode [90020-69]
	at org.h2.message.Message.getSQLException(Message.java:91)
	at org.h2.message.Message.getSQLException(Message.java:95)
	at org.h2.message.Message.getSQLException(Message.java:73)
	at org.h2.store.FileLock.error(FileLock.java:316)
	at org.h2.store.FileLock.lockFile(FileLock.java:178)
	at org.h2.store.FileLock.lock(FileLock.java:74)
	at org.h2.engine.Database.open(Database.java:467)
	at org.h2.engine.Database.<init>(Database.java:203)
	at org.h2.engine.Engine.openSession(Engine.java:55)
	at org.h2.engine.Engine.getSession(Engine.java:104)
	at org.h2.engine.Session.createSession(Session.java:203)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:976)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:957)
	at org.h2.Driver.connect(Driver.java:57)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at org.hibernate.connection.DriverManagerConnectionProvider.getConnection(DriverManagerConnectionProvider.java:110)
	at org.hibernate.cfg.SettingsFactory.buildSettings(SettingsFactory.java:84)
	at org.hibernate.cfg.Configuration.buildSettings(Configuration.java:2073)
	at org.hibernate.cfg.Configuration.buildSessionFactory(Configuration.java:1298)
	at store.util.HibernateUtil.<clinit>(HibernateUtil.java:8)
	at store.TuttiCondomini.recuperaCondomini(TuttiCondomini.java:34)
	at executor.GestoreCondomini.<init>(GestoreCondomini.java:60)
	at executor.GestoreCondomini.getInstance(GestoreCondomini.java:38)
	at executor.Avvio.inizializzaAmICo(Avvio.java:54)
	at executor.Avvio.main(Avvio.java:26)
02-15 17:06:22 database: opening C:\Documents and Settings\Federico\workspace\AmICo\DB\DataBase4Amico
org.h2.jdbc.JdbcSQLException: Database may be already in use: Locked by another process. Possible solutions: close all other connection(s); use the server mode [90020-69]
	at org.h2.message.Message.getSQLException(Message.java:91)
	at org.h2.message.Message.getSQLException(Message.java:95)
	at org.h2.message.Message.getSQLException(Message.java:73)
	at org.h2.store.FileLock.error(FileLock.java:316)
	at org.h2.store.FileLock.lockFile(FileLock.java:178)
	at org.h2.store.FileLock.lock(FileLock.java:74)
	at org.h2.engine.Database.open(Database.java:467)
	at org.h2.engine.Database.<init>(Database.java:203)
	at org.h2.engine.Engine.openSession(Engine.java:55)
	at org.h2.engine.Engine.getSession(Engine.java:104)
	at org.h2.engine.Session.createSession(Session.java:203)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:976)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:957)
	at org.h2.Driver.connect(Driver.java:57)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at org.hibernate.connection.DriverManagerConnectionProvider.getConnection(DriverManagerConnectionProvider.java:110)
	at org.hibernate.jdbc.ConnectionManager.openConnection(ConnectionManager.java:423)
	at org.hibernate.jdbc.ConnectionManager.getConnection(ConnectionManager.java:144)
	at org.hibernate.jdbc.JDBCContext.connection(JDBCContext.java:119)
	at org.hibernate.transaction.JDBCTransaction.begin(JDBCTransaction.java:57)
	at org.hibernate.impl.SessionImpl.beginTransaction(SessionImpl.java:1326)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.hibernate.context.ThreadLocalSessionContext$TransactionProtectionWrapper.invoke(ThreadLocalSessionContext.java:301)
	at $Proxy0.beginTransaction(Unknown Source)
	at store.TuttiCondomini.recuperaCondomini(TuttiCondomini.java:35)
	at executor.GestoreCondomini.<init>(GestoreCondomini.java:60)
	at executor.GestoreCondomini.getInstance(GestoreCondomini.java:38)
	at executor.Avvio.inizializzaAmICo(Avvio.java:54)
	at executor.Avvio.main(Avvio.java:26)
